### ISSUE TITLE
App is crashing when trying to insert files  

### ISSUE THREAD

**Issue by aniketsongara** [tneotia/html-editor-enhanced#10]
First of all thank you for the wonderful work I really appropriate. 
Whenever I am trying to uploading the files from editor file insertion it's crashing the application.

**Comment by tneotia** [comment]
Could you provide me your widget code to try and reproduce?

Also did you follow the "additional steps to allow file uploads" in the README?

I haven't encountered this issue in my testing so far.

**Comment by aniketsongara** [comment]
I simply follow your steps and try to run your simple example code, here what I am getting exactly while clicking on chose file is below : 

```

>  W/System.err(21226): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.test_new_editor.flutter_inappwebview.fileprovider
> W/System.err(21226): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:606)
> W/System.err(21226): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
> W/System.err(21226): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
> W/System.err(21226): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.getOutputUri(InAppWebViewChromeClient.java:1057)
> W/System.err(21226): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.getPhotoIntent(InAppWebViewChromeClient.java:929)
> W/System.err(21226): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.startPhotoPickerIntent(InAppWebViewChromeClient.java:886)
> W/System.err(21226): 	at com.pichillilorenzo.flutter_inappwebview.in_app_webview.InAppWebViewChromeClient.onShowFileChooser(InAppWebViewChromeClient.java:758)
> W/System.err(21226): 	at Kp.runFileChooser(PG:10)
> W/System.err(21226): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> W/System.err(21226): 	at android.os.MessageQueue.next(MessageQueue.java:336)
> W/System.err(21226): 	at android.os.Looper.loop(Looper.java:197)
> W/System.err(21226): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
> W/System.err(21226): 	at java.lang.reflect.Method.invoke(Native Method)
> W/System.err(21226): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> W/System.err(21226): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
> F/chromium(21226): [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
> F/libc    (21226): Fatal signal 5 (SIGTRAP), code -6 (SI_TKILL) in tid 21226 (test_new_editor), pid 21226 (test_new_editor)
> *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> Build fingerprint: 'samsung/m10ltedd/m10lte:10/QP1A.190711.020/M105FDDS4CTL2:user/release-keys'
> Revision: '4'
> ABI: 'arm'
> Timestamp: 2021-03-22 17:37:59+0530
> pid: 21226, tid: 21226, name: test_new_editor  >>> com.test_new_editor <<<
> uid: 10839
> signal 5 (SIGTRAP), code -6 (SI_TKILL), fault addr --------
> Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
> '
>     r0  00000000  r1  00000000  r2  7fffffff  r3  00000000
>     r4  ffb45094  r5  0000004f  r6  c645ebc0  r7  0000004f
>     r8  ffb454e0  r9  ffb454e4  r10 e5b48260  r11 ffb45094
>     ip  ffb45058  sp  ffb45080  lr  e5b373cd  pc  c4f5e1ec
> backtrace:
>       #00 pc 01c871ec  /system/app/TrichromeLibrary/TrichromeLibrary.apk!libmonochrome.so (offset 0x664000) (BuildId: 2b8667a6af5a7b970d7132510af80e0c28df0f4e)
> Lost connection to device.
> 

```

**Comment by tneotia** [comment]
Did you add this code in `AndroidManifest`?

```xml
​<​provider​
    ​android​:​name​=​"​com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider​"​
    ​android​:​authorities​=​"​${applicationId}.flutter_inappwebview.fileprovider​"​
    ​android​:​exported​=​"​false​"​
    ​android​:​grantUriPermissions​=​"​true​"​>
    <​meta-data​
        ​android​:​name​=​"​android.support.FILE_PROVIDER_PATHS​"​
        ​android​:​resource​=​"​@xml/provider_paths​"​ />
</​provider​>
```

**Comment by aniketsongara** [comment]
Thanks by adding  this app is now not crashing but giving exceptions : 

```
I/flutter ( 3373): editor focused
I/flutter ( 3373): image2692284481933197334.jpg
I/flutter ( 3373): 3823751
I/flutter ( 3373): image/jpeg
D/InputMethodManager( 3373): prepareNavigationBarInfo() DecorView@95adb58[MainActivity]
D/InputMethodManager( 3373): getNavigationBarColor() -855310
V/InputMethodManager( 3373): Starting input: tba=com.test_new_editor ic=wB@2f950c2 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
I/flutter ( 3373): 2021-03-22 18:28:15.177
D/InputMethodManager( 3373): startInputInner - Id : 0
I/InputMethodManager( 3373): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 3373): Input channel destroyed: 'ClientS', fd=160
E/flutter ( 3373): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Unable to load asset: path/to/image/image2692284481933197334.jpg
E/flutter ( 3373): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
E/flutter ( 3373): <asynchronous suspension>
E/flutter ( 3373): #1      _HtmlEditorExampleState.build.<anonymous closure> (package:test_new_editor/main.dart:116:38)
E/flutter ( 3373): <asynchronous suspension>
E/flutter ( 3373): 
```

> Did you add this code in `AndroidManifest`?
> 
> ```
> ​<​provider​
>     ​android​:​name​=​"​com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider​"​
>     ​android​:​authorities​=​"​${applicationId}.flutter_inappwebview.fileprovider​"​
>     ​android​:​exported​=​"​false​"​
>     ​android​:​grantUriPermissions​=​"​true​"​>
>     <​meta-data​
>         ​android​:​name​=​"​android.support.FILE_PROVIDER_PATHS​"​
>         ​android​:​resource​=​"​@xml/provider_paths​"​ />
> </​provider​>
> ```

**Comment by tneotia** [comment]
That exception is because you are using the sample code and path/to/image.jpeg doesn't exist, you will need to find the path on your own.

Glad to hear the code fixed it!

**Comment by jawadabbasi923** [comment]
I am getting this error when i add above cod ein manifest file.
Error parsing LocalFile: '/Users/jawadabbasi/Documents/Flutter/Company Projects/dealersgear_crm/android/app/src/main/AndroidManifest.xml' Please ensure that the android
manifest is a valid XML document and try again.

**Comment by tneotia** [comment]
@jawadabbasi923 could you send your manifest here - you must have formatted incorrectly.

**Comment by jawadabbasi923** [comment]
That was my mistake, file was not formatted correctly. Thankyou.

**Comment by tneotia** [comment]
No problem. However if you are using the latest version there is no need for modifying `AndroidManifest` as the webview is no longer used to upload the file, it is fully native Flutter now.

**Comment by jawadabbasi923** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.crm_app">
    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="DealersGear CRM"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">

            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:name="io.github.edufolly.fluttermobilevision.barcode.BarcodeCaptureActivity" />
        <activity android:name="io.github.edufolly.fluttermobilevision.ocr.OcrCaptureActivity" />
        <activity android:name="com.apptreesoftware.barcodescan.BarcodeScannerActivity"/>
        <​provider​
            ​android​:​name​=​"​com.pichillilorenzo.flutter_inappwebview.InAppWebViewFileProvider​"​
            ​android​:​authorities​=​"​${applicationId}.flutter_inappwebview.fileprovider​"​
            ​android​:​exported​=​"​false​"​
            ​android​:​grantUriPermissions​=​"​true​"​>
            <​meta-data​
            ​android​:​name​=​"​android.support.FILE_PROVIDER_PATHS​"​
            ​android​:​resource​=​"​@xml/provider_paths​"​ />
        </​provider​>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
-----------------------------------
This is my manifest code. it still gives error when i restart the app.
