### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by liangge013** [tneotia/html-editor-enhanced#101]
![IMG_1380](https://user-images.githubusercontent.com/11863286/128131317-05eaa464-42fc-465a-94be-e4aed003b116.PNG)

**Hello ，I found a problem
When the keyboard pops up and the font color or background color is selected, the palette display is incomplete**

**Comment by tneotia** [comment]
Thanks for the report, I fixed this - now the keyboard will be hidden when pressing the color button if the keyboard is active

**Comment by liangge013** [comment]
Which version fixes this problem? I use 2.2.0

**Comment by tneotia** [comment]
You'd have to use a git dependency on `master` , I didn't push it to a version yet

**Comment by tneotia** [comment]
Sorry I just realized, git dependency on the `2.2.0-dev.1` branch :)

**Comment by liangge013** [comment]
How can I hide the keyboard when pressing the color button?
