### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lgirolimetto** [tneotia/html-editor-enhanced#102]
**Describe the bug**
In web environment, when I insert Link, all text inserted is cleared.

**To Reproduce**
1. Digit some text in the editor
2. Click on Insert link icon
3. Enter the text and url
4. confirm
5. all text is cleared

**Device:**
I am testing on web(Chrome browser).

**Comment by tneotia** [comment]
When the text is cleared does the editor flash and appear to reload?

**Comment by lgirolimetto** [comment]
Yes, the editor flash and appear to reload. I am using flutter sdk 2.12.0.
Update: the text is cleared as soon as the link editor opens.

**Comment by tneotia** [comment]
Ah okay, this is an issue in flutter. You have two options:

1. Follow the fix here https://github.com/tneotia/html-editor-enhanced#important-note-for-web
2. Upgrade to Flutter Beta and the issue will go away

Let me know if it works!

**Comment by lgirolimetto** [comment]
With solution 1. works like a charme! Thanks a lot again

**Comment by tneotia** [comment]
No problem glad to hear it!
