### ISSUE TITLE
HtmlEditor embedded SingleChildScrollView sliding problem

### ISSUE THREAD

**Issue by XiaoAnXA** [tneotia/html-editor-enhanced#105]
Hello, the problem I am facing now is: HtmlEditor widget prevents SingleChildScrollView from sliding, how can I solve this problem?

**Comment by tneotia** [comment]
Unfortunately there is no solution because of how webviews work in Flutter. If this is a problem I would recommend creating a separate screen for the editor or some sort of popup dialog for the user to enter content. Sorry about that :(
