### ISSUE TITLE
[QUESTION]How to change the language?

### ISSUE THREAD

**Issue by liangge013** [tneotia/html-editor-enhanced#108]
<img width="233" alt="截屏2021-08-13 上午10 44 17" src="https://user-images.githubusercontent.com/11863286/129297789-d2c402d3-f0fb-4921-b8da-a91939389111.png">

How to change the title to Chinese? thank you~

**Comment by tneotia** [comment]
Please see #68 for more details on translation. Let me know if you have any questions!
