### ISSUE TITLE
web-renderer HTML

### ISSUE THREAD

**Issue by radvansky-tomas** [tneotia/html-editor-enhanced#109]
As per issue: https://github.com/flutter/flutter/issues/80524

And migration guide https://flutter.dev/docs/release/breaking-changes/platform-views-using-html-slots-web

Are you planning to migrate plugin to use it ? Its already in BETA

**Comment by tneotia** [comment]
I don't think anything in the plugin needs to be migrated to support the new rendering method... Are there any issues you are running into regarding these changes?
