### ISSUE TITLE
[QUESTION]Is it possible to expand html control height using expandwidget without specifying height

### ISSUE THREAD

**Issue by akmichael** [tneotia/html-editor-enhanced#112]
Hi quick question, it may not be related to your control. I am trying to fill html height using expandedWidget without specifying height. it doesnt work. any suggestion.

![expandHtml](https://user-images.githubusercontent.com/8349884/129673683-80e2798f-de4c-4d0e-8072-d7fb074c7695.png)

         ` body: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          mainAxisSize: MainAxisSize.max,
          children: <Widget>[
            Container(
              height: 100,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(6),
                color: Colors.red,
              ),
            ),
            Expanded(
                child: HtmlEditor(
                    controller: htmlController, //required
                    htmlEditorOptions: HtmlEditorOptions(
                      initialText: specUpdate.description,
                    ),
                    otherOptions: OtherOptions(
                      height: 400,
                    ),
                    htmlToolbarOptions:
                        HtmlToolbarOptions(defaultToolbarButtons: [
                      ParagraphButtons(lineHeight: false, caseConverter: false)
                    ]))),
            Container(
              height: 100,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(6),
                color: Colors.red,
              ),
            ),
          ],
        ),`

**Comment by tneotia** [comment]
Unfortunately no because of how webview works,I suggest you perform a calculation like `MediaQuery.of(context).size.height - 200 - appBarHeight` to set the proper height
