### ISSUE TITLE
html-editor-enhanced 1.3.0 callback not getting called

### ISSUE THREAD

**Issue by DishitaShah** [tneotia/html-editor-enhanced#113]
I am facing an issue with callback and onchange(text) method. When I type inside the html editor, the callback is not called.

**Comment by tneotia** [comment]
Could you provide more details about your issue? The HTML editor widget code will be helpful. Thanks :)

**Comment by DishitaShah** [comment]
`HtmlEditor(
          hint: "Your text here...",
          height: 300,
          callbacks: Callbacks(
            //onFocus: () => FocusScope.of(context).unfocus(),
            onChange: (String changed) {
              htmlText = changed;
              setState(() {
                _normalString = _parseHtmlString(htmlText);
                _dropdownShown = RegExps.kTaggingRex.hasMatch(_normalString);
              });
              if(_normalString.contains("@"));
              {
                String tagName = _normalString.substring(_normalString.indexOf('@'));
                searchTheUserList(tagName);
              }
            },

          )
      ),`

**Comment by DishitaShah** [comment]
Sure. Please check below code.

HtmlEditor(
          hint: "Your text here...",
          height: 300,
          callbacks: Callbacks(
            //onFocus: () => FocusScope.of(context).unfocus(),
            onChange: (String changed) {
              htmlText = changed;
              setState(() {
                _normalString = _parseHtmlString(htmlText);
                _dropdownShown = RegExps.kTaggingRex.hasMatch(_normalString);
              });
              if(_normalString.contains("@"));
              {
                String tagName = _normalString.substring(_normalString.indexOf('@'));
                searchTheUserList(tagName);
              }
            },

          )
      ),

**Comment by DishitaShah** [comment]
the first time I open the app and enter the page it calls the callback but later it never calls the callback again.

**Comment by tneotia** [comment]
That is odd... It seems you are using an older version of the plugin? Could you try the latest 2.2.0 version and see if the problem persists? There are some breaking changes in the 2.0.0+ versions but a migration guide is available to help you.

**Comment by DishitaShah** [comment]
As the project is not migrated to "null safety" and Flutter 2.0 yet so I will not be able to use the latest version. So, is there any possibility to fix this? or any solution to this?

**Comment by tneotia** [comment]
Ah okay. Can you upgrade to version 1.4.0 and make use of the new controller style API? I recommend in pub.dev to specifically look at v1.4.0 readme so you can understand how the API works. 

By the way if you just want to show a dropdown for mentions, the plugin supports this out of the box in the nullsafety versions.

**Comment by DishitaShah** [comment]
Cannot move to 1.4.0 as for that I need to upgrade my sdk. Also, I cannot stop the internal scroll of HtmlEditor. No physics property.

**Comment by DishitaShah** [comment]
![Screenshot 2021-08-18 at 4 58 07 PM](https://user-images.githubusercontent.com/22871294/129890365-dcebaa27-3fa1-40c4-a148-e5302d026935.png)

**Comment by tneotia** [comment]
> Cannot move to 1.4.0 as for that I need to upgrade my sdk. Also, I cannot stop the internal scroll of HtmlEditor. No physics property.

You can use

```
dependency_overrides:
   js: 0.6.2
```
In pubspec and now you should be able to use 1.4.0 version.
As for physics, I don't allow disabling editor scroll because then content longer than the editor box itself will not be able to scroll into view.

**Comment by DishitaShah** [comment]
Okay thanks for the help. But I wonder will this solve the issue of callback "onChange" method not getting called? Because version 1.4.0 also have callback method similar to 1.3.0

**Comment by tneotia** [comment]
It might not, I'm just suggesting you to try things because you are on a very old version and no one had reported that problem before - there were a lot of API changes in 1.4.0 so it is quite possible the callback will work.

**Comment by DishitaShah** [comment]
Okay I will try and revert if the issue is closed.

**Comment by DishitaShah** [comment]
It dint worked. I have noticed one more thing. Once the callback is called and once u terminate that page and move back to the page and try to type something in editor, callback is not called.

**Comment by DishitaShah** [comment]
Hi can u explain me how to set the editor to rich text view from code view?

I got something of use.
// Callback is Called whenever the HTML content of the editor is changed and the editor
  /// is in rich text view. There is currently no way to detect changes when
  /// the editor is in code view

**Comment by DishitaShah** [comment]
My editor is setting itself to code view mode due to which no callbacks are being called. I have got the cause. can u please help me find the solution @tneotia

**Comment by tneotia** [comment]
controller.toggleCodeview()

As for the callback not working I'm sorry I have no idea - I highly suggest migrating to nullsafety ASAP because this library has had many upgrades in the nullsafety versions.

**Comment by DishitaShah** [comment]
May I know how to hide the copy paste buttons at bottom? 
![Simulator Screen Shot - iPhone 8 - 2021-08-20 at 12 20 06](https://user-images.githubusercontent.com/22871294/130192357-ef7c74ba-7c60-46c5-a894-59ce2e0a8bc6.png)

**Comment by tneotia** [comment]
Sorry for the late response, I don't think I had added that capability in.... They are removed in later versions but obviously you will need nullsafety.
