### ISSUE TITLE
Use this library to import import'package:html_editor_enhanced/html_editor.dart'; error

### ISSUE THREAD

**Issue by 2530442368** [tneotia/html-editor-enhanced#117]
![image](https://user-images.githubusercontent.com/63909463/130357304-606a4923-8afc-491d-a5f6-7bafe6594efb.png)

**Comment by 2530442368** [comment]
The author may I ask if this problem is my own problem?

**Comment by tneotia** [comment]
Please try the solutions listed here: https://github.com/tneotia/html-editor-enhanced/issues/68#issuecomment-863369808

Hope it helps!

**Comment by 2530442368** [comment]
> 请尝试这里之前的解决方案：[#68（评论）](https://github.com/tneotia/html-editor-enhanced/issues/68#issuecomment-863369808)
> 
> 希望有帮助！

Thank you brother, thank you very much.
