### ISSUE TITLE
Hello, I want the framed place to be at the bottom by default, and follow the keyboard to pop up. What do I need to do?

### ISSUE THREAD

**Issue by 2530442368** [tneotia/html-editor-enhanced#118]
![image](https://user-images.githubusercontent.com/63909463/130471295-22c9b923-389d-4612-bf82-25bceb169605.png)

**Comment by tneotia** [comment]
You need to change the height of your editor box using MediaQuery to make it full size.

**Comment by 2530442368** [comment]
> 您需要使用 MediaQuery 更改编辑器框的高度以使其全尺寸。

Can you please give me the code for how to set it up? Thank you very much. I searched the document for a long time, but I didn’t find it. It may be that I don’t understand the document deeply.

**Comment by 2530442368** [comment]
> > 您需要使用 MediaQuery 更改编辑器框的高度以使其全尺寸。
> 
> 你能告诉我如何设置它的代码吗？非常感谢。找了半天文档，没找到。可能是我对文档的理解不深。

![image](https://user-images.githubusercontent.com/63909463/130480028-f6be0565-f371-41a4-a4f2-f7e3fbc73994.png)

**Comment by tneotia** [comment]
```dart
htmlEditorOptions: HtmlEditorOptions(
    height: MediaQuery.of(context).size.height - (MediaQuery.of(context).padding.top + kToolbarHeight)
    ...
)
```
should work for you

**Comment by 2530442368** [comment]
> ```dart
> htmlEditorOptions: HtmlEditorOptions(
>     height: MediaQuery.of(context).size.height - (MediaQuery.of(context).padding.top + kToolbarHeight)
>     ...
> )
> ```
> 
> should work for you

Hello, is the parameter given wrong but this OtherOptions parameter, I reported an error with the parameter you gave by the authorThe named parameter "height" is not defined. Try to correct the name to the name of an existing named parameter, or use the name "height" to define a named parameter. Open document

**Comment by 2530442368** [comment]
![795b6f64d7747645baadddb3ac05a80](https://user-images.githubusercontent.com/63909463/130482558-1262404d-616a-43a5-b05f-64760430d6f6.jpg)
I'm sorry to ask you one or two more questions, 1: Can this be removed where the arrow points? 2: Can the arrangement of the picture frame be arranged neatly?

**Comment by tneotia** [comment]
1. Yes, follow instructions from #42 
2. Hmm that is something I have to fix... it is a bug thank you for telling me.

**Comment by 2530442368** [comment]
> 1. Yes, follow instructions from [[QUESTION] How to remove dragbar  #42](https://github.com/tneotia/html-editor-enhanced/issues/42)
> 2. Hmm that is something I have to fix... it is a bug thank you for telling me.

Sorry, I still don’t understand how to delete the drag bar. Can you explain it in detail?

**Comment by tneotia** [comment]
```dart
HtmlEditor(
   controller: controller,
   callbacks: Callbacks(
      onInit: () {
         controller.setFullscreen();
      }
   )
)
```

Like this :)

**Comment by 2530442368** [comment]
> ```dart
> HTML编辑（
>    控制器：控制器，
>    回调： 回调（
>       的OnInit ：（）{
>          控制器。setFullscreen ;（）
>       } 
>    ）
> ）
> ```
> 
> 像这样:)

Thank you
