### ISSUE TITLE
Web page not found when inserting video url

### ISSUE THREAD

**Issue by aniketsongara** [tneotia/html-editor-enhanced#12]
Web page not found is showing in editor whenever I am trying to insert the video url from insert Video Url.
but when was checking Code view I got this : 
 
`<p><iframe frameborder="0" src="//www.youtube.com/embed/W1pNjxmNHNQ" width="640" height="360" class="note-video-clip"></iframe><br></p>`

In above I append `https:` in `src` then it's working fine. 

`<p><iframe frameborder="0" src="https://www.youtube.com/embed/W1pNjxmNHNQ" width="640" height="360" class="note-video-clip"></iframe><br></p>`
 
It's issue is coming only in mobile platform. on web it's working.  please add this changes in iframe of  lib/summernote/summernote-lite.min.js

**Comment by tneotia** [comment]
What is the URL you type into the "insert video" field? Does it start with "www" or directly "youtube.com"?

**Comment by aniketsongara** [comment]
Inserting youtube video url start with simple `https: `
url is `https://www.youtube.com/watch?v=W1pNjxmNHNQ`

**Comment by tneotia** [comment]
Thanks - this is apparently a known issue in Summernote: https://github.com/summernote/summernote/issues/3252

Let me see if I can modify the source to fix this.

**Comment by aniketsongara** [comment]
Welcome, You can do it  you just need to go in lib/assets/summernote-lite.min.js as I mentioned above and search the ifram code then append https: in that. Thanks  

> Thanks - this is apparently a known issue in Summernote: [summernote/summernote#3252](https://github.com/summernote/summernote/issues/3252)
> 
> Let me see if I can modify the source to fix this.

**Comment by tneotia** [comment]
Done, thanks for reporting!

**Comment by aniketsongara** [comment]
I am waiting for it.

> Done, thanks for reporting!
> 
> I am releasing 1.7.0+1 with the various fixes for the recent issues.

**Comment by tneotia** [comment]
It is uploaded and should be available now :)
