### ISSUE TITLE
[QUESTION] open link

### ISSUE THREAD

**Issue by liangge013** [tneotia/html-editor-enhanced#123]
When I insert a link and set isNewWindow to true, the link is still opened on the current page.
`controller.insertLink(linkName, linkUrl, true);`

How can I open it in Safari?

<img width="334" alt="截屏2021-08-30 下午2 26 12" src="https://user-images.githubusercontent.com/11863286/131295423-8b877d71-cb86-4408-86dc-47760c4a7bf6.png">

**Comment by tneotia** [comment]
You can follow the guide at https://github.com/tneotia/html-editor-enhanced/issues/88#issuecomment-878695455, use `url_launcher` package and return `NavigationActionPolicy.PREVENT` to open the links :)

**Comment by liangge013** [comment]
When I click on this link, can I jump directly instead of popping up this box?

<img width="337" alt="123" src="https://user-images.githubusercontent.com/11863286/131604847-c8c76cfb-ddda-49dd-a15a-410ec76e29ed.png">

**Comment by tneotia** [comment]
No unfortunately because the package provides the ability for the user to remove the hyperlink and just keep the google text. Pressing on it once more should open the link.

**Comment by liangge013** [comment]
Thank you for your answers. Unfortunately, I am currently using the stable version of flutter and cannot use 2.2.0+1-dev.1. I look forward to you updating the new version.

**Comment by tneotia** [comment]
> Thank you for your answers. Unfortunately, I am currently using the stable version of flutter and cannot use 2.2.0+1-dev.1. I look forward to you updating the new version.

2.2.0 is the same functionality as 2.2.0+1-dev.1 but yes I hope to push a new update soon. Maybe this week or next.

**Comment by Huanxin1997** [comment]
![image](https://user-images.githubusercontent.com/42678103/142092777-27215b47-ed38-42d1-aab2-727fc38c3303.png)
Hi, Can I forbid this behavior? When I click on this link, I don't want it popping up this box and I also don't want to jump.

**Comment by tneotia** [comment]
> Hi, Can I forbid this behavior? When I click on this link, I don't want it popping up this box and I also don't want to jump.

Yes you can remove this popup, in the `HtmlEditorOptions` parameter `customOptions` please use

```dart
"""
popover: {
  image: [
    ['image', ['resizeFull', 'resizeHalf', 'resizeQuarter', 'resizeNone']],
    ['float', ['floatLeft', 'floatRight', 'floatNone']],
    ['remove', ['removeMedia']]
  ],
  link: [],
  table: [
    ['add', ['addRowDown', 'addRowUp', 'addColLeft', 'addColRight']],
    ['delete', ['deleteRow', 'deleteCol', 'deleteTable']],
  ],
},
"""
```

As you can see in the string we set `link: []` which removes the display for the link popup only.

**Comment by Huanxin1997** [comment]
> As you can see in the string we set link: [] which removes the display for the link popup only.

Thank you for your reply. Can I only set like this? 
"""
popover: {
  link: []
},
"""``

**Comment by Huanxin1997** [comment]
> If you do like that then the buttons for resizing image on tap will disappear. This syntax is JavaScript syntax so it does not have a default value for every parameter.

OK, Thank you very much.
