### ISSUE TITLE
[BUG] cannot upload an image and other problem as well

### ISSUE THREAD

**Issue by husamhamu12** [tneotia/html-editor-enhanced#124]
There are no errors in the console, but you can see in the video how it behaves weird. And this is actually your demo code.
[https://youtu.be/7AcHHVegmCw](url)

**Comment by husamhamu12** [comment]
When i run the app with the following command : `flutter run -d chrome --web-renderer htmlevery` thing works nicely :)
here:

![image](https://user-images.githubusercontent.com/88487403/131485217-b944dbd0-e36c-443a-a50e-093d10e22e3b.png)

but there are still some exceptions that arise:

![image](https://user-images.githubusercontent.com/88487403/131485526-0d928180-c8a4-4f5c-bb8f-0868780ff5a4.png)

And how will this look like in production ?

**Comment by husamhamu12** [comment]
I just saw that you actually added this as an important note for web. I didn't see that. Sorry for the inconvenience. But does it mean that I have to use the HTML renderer for the whole app  and can't use the `auto` option somehow ?

**Comment by tneotia** [comment]
You can ignore the errors, it is the internal library for the html editor that does that. And yes you need to use html all the time or you can upgrade to beta flutter sdk and then auto will work as well.

**Comment by husamhamu12** [comment]
OK, thanks. I will close the issue then.
