### ISSUE TITLE
[QUESTION] Remove styles from StyleButtons

### ISSUE THREAD

**Issue by DasElias** [tneotia/html-editor-enhanced#127]
Is it possible to remove the "Quote" and the "Code" style from StyleButtons? Unfortunately, in the documentation I haven't found anything.

Thanks in advance.

**Comment by tneotia** [comment]
You can follow https://github.com/tneotia/html-editor-enhanced/issues/59#issuecomment-860104165 for this. That answer is structured for adding custom fonts, to remove them you only have to edit the dart code and remove the buttons you don't want for the drop-down. Make sure you use the callback to update the state of your dropdown to reflect the font in the editor. Let me know if you have issues with this!
