### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by mmanvar-parkstreet** [tneotia/html-editor-enhanced#128]
I want to add a custom font(Helvetica-nue) in the font family.  I am not able to find a way to add those custom font into defaultToolbarButtons. 
is it possible to add?

**Comment by tneotia** [comment]
Yes you can add, see https://github.com/tneotia/html-editor-enhanced/issues/59#issuecomment-860104165 for details on how to do this. Let me know if you have more questions.
