### ISSUE TITLE
[BUG] iOS keyboard

### ISSUE THREAD

**Issue by Beto-Beto-Salamander** [tneotia/html-editor-enhanced#129]
**Bug :** 
I'm using a M1 Macbook, I run the project with just copy paste the sample given but the keyboard not showing when I click the text box area
Using Command+K not showing the keyboard at all
Using mac keyboard for the input also not working

**Pubspec.yaml**
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  file_picker: ^3.0.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.4.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  html_editor_enhanced: ^2.2.0
  image_picker: ^0.8.3+2
  lint: ^1.5.3
  persistent_bottom_nav_bar: ^4.0.2
  staggered_grid_view_flutter: ^0.0.4

**Device:**
M1 Macbook Pro
iOS Simulator & Physical 

Any suggestion or fix will be appreciated, thank you !

**Comment by tneotia** [comment]
Please see #7 for a fix to this issue:)

**Comment by Beto-Beto-Salamander** [comment]
Thank you for your support :)

I've tried that before but it didn't work,
I found another solution for this case, I just need to disable "Connect hardware keyboard" from the Simulator I/O and it workss!

I'll close this issue ticket :)
Have a nice day!
