### ISSUE TITLE
[BUG]最新版本中，选择字体和字体背景颜色，并没有改变编辑区中的字体颜色

### ISSUE THREAD

**Issue by 157163178002** [tneotia/html-editor-enhanced#132]
最新版本中，选择字体颜色，并没有改变编辑区中的字体颜色

**Comment by tneotia** [comment]
Hi, I cannot reproduce on ios simulator:

![image](https://user-images.githubusercontent.com/50850142/132950582-acc5698a-ee22-44c5-8ffc-d82efebfb784.png)

What device are you testing on?

**Comment by 157163178002** [comment]
> 嗨，我无法在 ios 模拟器上重现：
> 
> ![图片](https://user-images.githubusercontent.com/50850142/132950582-acc5698a-ee22-44c5-8ffc-d82efebfb784.png)
> 
> 你在什么设备上测试？

在android模拟器上
![Screenshot_1631406225](https://user-images.githubusercontent.com/79408298/132966754-f583bdda-fed4-41f5-9616-10868615a360.png)

**Comment by 157163178002** [comment]
选择颜色时，编辑区会失去焦点，无法编辑，再次点击编辑区，会默认前面字体的样式。输入汉语更加明显。

**Comment by tneotia** [comment]
Fixed via e808d364b2d448ce248fd5934bb1228a15c02ead
