### ISSUE TITLE
[QUESTION] How to Display final output?

### ISSUE THREAD

**Issue by arbile26** [tneotia/html-editor-enhanced#133]
I want to display the final HTML output on the screen as a preview. I tried [flutter_html](https://github.com/Sub6Resources/flutter_html) but the result is not the same that I design in the editor (e.g. if I insert an image and resize or position it, it doesn't look the same in [flutter_html](https://github.com/Sub6Resources/flutter_html).

**Comment by tneotia** [comment]
Unfortunately there is no way to show it 1:1 in native Flutter, because it simply is not an HTML renderer. However you can use `flutter_inappwebview` and provide it with the HTML code, it should be able to render it like a browser would. Let me know if you have any questions with this!

**Comment by arbile26** [comment]
I tried  `flutter_inappwebview ` too, it doesn't display the HTML text of the editor correctly. see:

The text in the editor:
![IMG_2786](https://user-images.githubusercontent.com/74053601/132962895-057813a4-6e65-40b7-8b2f-ee230b605476.jpg)

the text in `flutter_inappwebview `
![IMG_2787](https://user-images.githubusercontent.com/74053601/132962914-d908fcca-b897-4060-831b-b37f802a2d74.jpg)

It seems smaller and even the font is not the same

**Comment by tneotia** [comment]
Can you post the HTML code of the output?

**Comment by arbile26** [comment]
`<p><font size="6">Test</font></p><p><ol><li><font size="5">test</font></li><li><font size="5">test</font></li></ol></p>
`
This is the code without the image, the text seems so small.

**Comment by arbile26** [comment]
> Can you post the HTML code of the output?
> 
> Edit: Just thought of something. The library isn't technically made to do this, but you can still do it.
> 
> ```dart
> AbsorbPointer(
>    absorbing: true,
>    child: HtmlEditor(
>       controller: controller, //required
>         htmlEditorOptions: HtmlEditorOptions(
>           initalText: text to render here,
>         ),
>       toolbarOptions: HtmlToolbarOptions(
>            toolbarPosition: ToolbarPosition.custom //to remove toolbar
>       ),
>    ),
> ),
> ```
> 
> This will create a webview container with the text content, and since it still uses the summernote library to display, it will look the exact same, plus since you did custom toolbar position it will remove the toolbar.

Brilliant idea, but `AbsorbPointer` will disable the scroll functionality.
Is there any way to use summernote library to display without its editing functionality?

**Comment by arbile26** [comment]
> Can you post the HTML code of the output?
> 
> Edit: Just thought of something. The library isn't technically made to do this, but you can still do it.
> 
> ```dart
> AbsorbPointer(
>    absorbing: true,
>    child: HtmlEditor(
>       controller: controller, //required
>         htmlEditorOptions: HtmlEditorOptions(
>           initalText: text to render here,
>         ),
>       toolbarOptions: HtmlToolbarOptions(
>            toolbarPosition: ToolbarPosition.custom //to remove toolbar
>       ),
>    ),
> ),
> ```
> 
> This will create a webview container with the text content, and since it still uses the summernote library to display, it will look the exact same, plus since you did custom toolbar position it will remove the toolbar.

Brilliant idea, but `AbsorbPointer` will disable the scroll functionality.
Is there any way to use summernote library to display without editing functionality?

**Comment by tneotia** [comment]
Oh I forgot about that, I think you can disable the editor using onInit callback (`controller.disable()`). I don't remember if this keeps scrolling functionality so you will have to test that.

**Comment by arbile26** [comment]
I figured out a way by disabling the editor by the controller.
But I get an error when the when `toolbarPosition: ToolbarPosition.custom`. The editor tries to disable the toolbar but It doesn't find it.
also, is there a way to trigger `controller.disable();` when the webView loads the html code?

**Comment by arbile26** [comment]
> Oh I forgot about that, I think you can disable the editor using onInit callback (`controller.disable()`). I don't remember if this keeps scrolling functionality so you will have to test that.

ohhh, I was about to say it 😂

**Comment by tneotia** [comment]
For the toolbar error maybe you can create a toolbar widget but put it inside a visibility widget and hide it. That way the widget thinks it is there but  the user cannot see it.

**Comment by arbile26** [comment]
> For the toolbar error maybe you can create a toolbar widget but put it inside a visibility widget and hide it. That way the widget thinks it is there but the user cannot see it.
> 
> This is getting to be very hacky but at least it is a solution 😂

Everything works perfectly now. But there is another thing. When I disable the editor, it changes it's colour. How can I change disabled color?

**Comment by tneotia** [comment]
> How can I change disabled color?

Hmmm.... it applies a gray mask but currently I have no way to change disabled color unfortunately. Maybe I can implement this in the future, but cannot guarantee anything.

**Comment by tneotia** [comment]
I couldn't find where the gray mask is set or how to change it :(

Flutter wasn't really made for rendering HTML content so I don't know how to solve this issue better. As such I will close it for now.
