### ISSUE TITLE
[BUG] I have tried a simple Flutter page editing HTML using the example available on pub.dev and showing the following error with package 2.3.0

### ISSUE THREAD

**Issue by tuemaytinh1981** [tneotia/html-editor-enhanced#134]
**Describe the bug**
I have tried a simple Flutter page editing HTML using the example available on pub.dev and showing the following error with package 2.3.0
**To Reproduce**
1. Go to pub.dev
2. Copy code example from pub.dev
3. try simple page editor html on flutter
4. See error:
Waiting for connection from debug service on Chrome...
../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.4.0/lib/src/hsv_picker.dart:731:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);
                            ^

**Expected behavior**
Error flutter_colorpicker-0.4.0  & html_editor_enhanced 2.3.0 

**Screenshots**
<img width="778" alt="Screen Shot 2021-09-12 at 17 24 36" src="https://user-images.githubusercontent.com/41774672/132984035-a8a0a7c7-a1af-4694-943e-90406d89b72f.png">

**Device:**
IOS, Web

**Comment by tneotia** [comment]
Please check the changelog, it has details to resolve this issue in case you are on flutter 2.5 and up :)

**Comment by tuemaytinh1981** [comment]
Thank Tanay Neotia very much!.
The WYSIWYG HTML library you made is great. Just need to improve a bit. I think a lot of people will use it.
I've added:
dependency_overrides:
  flutter_colorpicker: ^0.5.0
And was successful.
