### ISSUE TITLE
[FEATURE] Can you add onMediaDelete callback feature, link import Video?

### ISSUE THREAD

**Issue by tuemaytinh1981** [tneotia/html-editor-enhanced#135]
Summernote on php, javascript ... has onMediaDelete callback feature, import Video link
Example:

```
$(document).ready(function() {
    $('#summernote').summernote({
        height: "300px",
        callbacks: {
            onImageUpload: function(files) {
                uploadFile(files[0]);
            },

            onMediaDelete : function(target) {
                // alert(target[0].src) 
                deleteFile(target[0].src);
            }
        }
    });
});
```

**Describe the solution you'd like**
onFileUpload, onMediaDelete functions are quite important for an html editor. I think you did a great job adding a few features to support uploading image files, delete image files, upload video links, and it's great.

Thanks
Best Regards

**Comment by tneotia** [comment]
I will look into it, thanks for the suggestion. I didn't see it in the Summernote API documentation but maybe I missed it.

**Comment by tneotia** [comment]
I looked into the Summernote JavaScript and unfortunately the media delete callback only works when the user uses the popup button to delete an image. It does not work when using backspace, so I do not think it is a good idea to add this feature. I suggest you use the `onChange` callback and find the difference between the previous HTML string and the current HTML string, and determine if a media was deleted that way.
