### ISSUE TITLE
[BUG]could not create build - flutter_colorpicker dependency issues

### ISSUE THREAD

**Issue by kmusham** [tneotia/html-editor-enhanced#137]
**Describe the bug**

### **Could not create builds at all **

Running Gradle task 'assembleRelease'...                        
../../../../../.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.4.0/lib/src/hsv_picker.dart:731:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../../Library/Flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../../Library/Flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);
                            ^
FAILURE: Build failed with an exception.

Even if I added the following dependency override,  I till see the error  
dependency_overrides:
  flutter_colorpicker: ^0.4.0

$: flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

**Comment by JustonJ99** [comment]
@tneotia  Got the same error after upgraded to flutter version 2.5.
I did tried install the flutter_colopicker 0.60 but got this error 

pub get failed (1; So, because invoice_app depends on both html_editor_enhanced ^2.3.0 and flutter_colorpicker ^0.6.0, version solving failed.)

**Comment by tneotia** [comment]
You both need to use dependency overrides like this:

```yaml
dependency_overrides:
    flutter_colorpicker: ^0.6.0
```

and it should fix the issue. The reason this is like that is because the API for gestures changed in Flutter, and right now I don't want to constrain the package to 2.5.0 Flutter which recently came out. Please bear with this change for a bit longer, in maybe 1 month I will officially constrain package to require 2.5.0 and up, then this error will be gone for everyone.

**Comment by kmusham** [comment]
I added the dependency override as you suggested but I get into another build issue(s)
 
![image](https://user-images.githubusercontent.com/6372373/133276694-44e2136e-b41b-4f58-b937-b8aa367c03b9.png)

   ** BUILD FAILED **


Xcode's output:
↳
    <REMOVED>/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'connectivity' not found
    @import connectivity;
     ~~~~~~~^~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Encountered error while building for device.

I did a clean build ( flutter clean, pod install) still the same issue

**Comment by tneotia** [comment]
That is not related to this plugin, I often have pod build issues with xcode. Usually after researching there is something that makes it work but I can't remember off the top of my head. Try deleting that generated_plugin_registrant file? It will be regenerated so maybe it will fix itself.

**Comment by kmusham** [comment]
Wow!, Thank you for your recommendation.
I had to delete .m, .h, PodFile and .lock, podspec files to make it work.
It's always been a challenging to work with iOS builds.

**Comment by Abhishek-0912** [comment]
> You both need to use dependency overrides in pubspec like this:
> 
> ```yaml
> dependency_overrides:
>     flutter_colorpicker: ^0.6.0
> ```
> 
> and it should fix the issue. The reason this is like that is because the API for gestures changed in Flutter, and right now I don't want to constrain the package to 2.5.0 Flutter which recently came out. Please bear with this change for a bit longer, in maybe 1 month I will officially constrain package to require 2.5.0 and up, then this error will be gone for everyone.

I am on **stable channel** and I tried adding `dependency_overrides `in my `pubspec.yaml` but still it throws the same error.
does it work on stable channel or I need to change to any other, I am using this for my production ready app.
please provide solution for stable channel if possible I don't want to switch to any other.

**Comment by tneotia** [comment]
@Abhishek-0912 can you please share your pubspec file here?

**Comment by Abhishek-0912** [comment]
> @Abhishek-0912 can you please share your pubspec file here?
```name: devcom
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
 
  file_picker: 
  cached_network_image: ^3.1.0
  google_sign_in: 
  simple_animations:
  page_transition:  
  cupertino_icons: ^1.0.0
  firebase_auth: ^3.1.1
  # firebase_core_web:  
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter_image_compress: ^1.1.0
  location: ^4.3.0
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  uuid: ^3.0.4
  cloud_functions: 
  flutter_webrtc:
  cloud_firestore: 
  cloud_firestore_web:
  http: 
  url_launcher:
  # flutter_quill: 
  # to use html_editor_enhanced doesnt works on stable change to beta+ 
  # html_editor_enhanced: 2.2.0  

  flutter_svg: 
  get:
  supercharged: ^2.1.1

# dependency_overrides:
#   flutter_colorpicker: 
  
dev_dependencies:
  flutter_lints: 
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
  ```
  my `Pubspec.yaml` file

**Comment by Abhishek-0912** [comment]
@tneotia now its working thanks, the problem was with auto generated plugin file after deleting that and rebuilding it with `flutter create .` it works, and how can I include all the tools available in this plugin like is there any code to include all of them or do I have to include every options manually.

**Comment by tneotia** [comment]
> like is there any code to include all of them or do I have to include every options manually.

To include all the toolbar items you can use this:

```dart
Widget htmlEditor = HtmlEditor(
  controller: controller, //required
  //other options
  toolbarOptions: HtmlToolbarOptions(
    defaultToolbarButtons: [
      StyleButtons(),
      FontSettingButtons(),
      FontButtons(),
      ColorButtons(),
      ListButtons(),
      ParagraphButtons(),
      InsertButtons(),
      OtherButtons(),
    ],
  )
);
```

For the other doubt seems like you are using the plugin wrong. To get text you don't need to assign to `callbacks:` parameter, just call the `await controller.getText()` anywhere in your code.
