### ISSUE TITLE
[QUESTION] How to change the color of the selection handle

### ISSUE THREAD

**Issue by Knotworking** [tneotia/html-editor-enhanced#138]
Hi there, 

Is it possible to change the selection handle color from the default bright green?

I've tried searching through the documentation and github issues, but I can't seem to find an answer. I have also tried setting `selectionHandleColor` in the parent theme, but no luck.

Thanks for all of the work you've put into this package.

**Comment by tneotia** [comment]
Unfortunately because the package uses a WebView it doesn't confirm to flutter theming. If your handle color is fixed to one color no matter the theme, you might be able to do this: https://stackoverflow.com/a/65746919

I haven't tested it, so I can't say for sure.

**Comment by Knotworking** [comment]
It worked, thanks!

So for others who may be looking, try adding `<item name="android:colorControlActivated">#yourColorHere</item>` to the theme in `android/src/main/res/values/styles.xml`.
