### ISSUE TITLE
[QUESTION] Custom Link style

### ISSUE THREAD

**Issue by liangge013** [tneotia/html-editor-enhanced#140]
**I have customized the link dialog，When I click the button in Figure 1, the previous pop-up box still pops up**

<img width="334" alt="a" src="https://user-images.githubusercontent.com/11863286/133879599-0ec7dd6a-eb56-494c-83e6-ef1d4f62539a.png">
<img width="314" alt="b" src="https://user-images.githubusercontent.com/11863286/133879520-2329b4e6-50fa-46b3-a5c3-3f278f1adad5.png">
>

**Comment by tneotia** [comment]
Unfortunately that dialog is from summernote itself, so it shows in the webview, it is not built by Flutter. I *might* be able to override it so that it tells Flutter to open a custom dialog, but I will have to see. I will mark this as an enhancement opportunity.

**Comment by tneotia** [comment]
@vbaxan yes that can be possible, I will try and add it in the next update :)

For now you could use CSS to hide this tooltip, the class name is `note-popover popover in note-link-popover bottom`. If you use the `onInit` callback in the widget code, you can use javascript to set `display: none` on this class which should prevent it from being shown to the user.

**Comment by vbaxan** [comment]
@tneotia thanks for the reply. Could you please provide a working example? Can't get it to work...  Thank you.

**Comment by tneotia** [comment]
Added support for custom initialization options via a string, so the above is possible.

**Comment by vbaxan** [comment]
> Added support for custom initialization options via a string, so the above is possible.

It works. Thanks for adding this!

**Comment by Aruljebaraj** [comment]
need help here need to customise   image: [
    ['image', ['resizeFull', 'resizeHalf', 'resizeQuarter', 'resizeNone']],
    ['float', ['floatLeft', 'floatRight', 'floatNone']],
    ['remove', ['removeMedia']]
  ], need to another button
