### ISSUE TITLE
[BUG]  Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'

### ISSUE THREAD

**Issue by Abhishek-0912** [tneotia/html-editor-enhanced#142]
I am facing some strange error while using html-editor-enhanced plugin the error message is,

![image](https://user-images.githubusercontent.com/53706892/134259233-531779a4-18fe-4766-9e37-cc7b1e3eab02.png)

### Launching lib\main.dart on Chrome in debug mode...
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.4.0/lib/src/hsv_picker.dart:731:29: Error: The argument type 'PointerEvent' can't be assigned to the      
parameter type 'PointerDownEvent'.
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/C:/src/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/C:/src/flutter/packages/flutter/lib/src/gestures/events.dart').
    super.addAllowedPointer(event);
                            ^
Waiting for connection from debug service on Chrome...             55.0s
Failed to compile application.

please help solving this issue I am using this for my project and not able to solve this error and its been a week now no help

**Comment by tneotia** [comment]
Please check https://github.com/tneotia/html-editor-enhanced/issues/137#issuecomment-918685980 :)
