### ISSUE TITLE
Need more info about Media upload interception

### ISSUE THREAD

**Issue by darmie** [tneotia/html-editor-enhanced#143]
If I intercept and upload media to my servers, how do I tell the editor how to embed the server hosted file? The function provided only returns a boolean

**Comment by tneotia** [comment]
So you need to `return false` (this tells the plugin you handled by yourself) and then use `controller.insertNetworkImage()` to insert an uploaded image, for example. I recommend you check out this [example](https://github.com/tneotia/html-editor-enhanced#example-for-linkinsertinterceptor-medialinkinsertinterceptor-otherfilelinkinsert-mediauploadinterceptor-and-onotherfileupload) which will help you out to understand.

**Comment by darmie** [comment]
@tneotia Ah, thanks
