### ISSUE TITLE
New Feature : if user type more than certain character, user cant type anymore

### ISSUE THREAD

**Issue by bwrelawan** [tneotia/html-editor-enhanced#144]
Hello, very thanks for your fixing, Thats good! But, some people needs user cant type anymore when get limit max character. current condition, if user type more than certain character, we just do *controoler.disable()* then if we want enable, must add a trigger button for *controller.enable()* this UX feels wrong :( ... please keep up! thank you so much!!!! <3

**Comment by tneotia** [comment]
Fixed via 4286817f065152ca5d2b743470e70b3c483203ba

**Comment by mimiaopp** [comment]
我尝试了它,发现并没有作用.也可能是我使用的不对

**Comment by tneotia** [comment]
> 我尝试了它,发现并没有作用.也可能是我使用的不对

What is your `Html()` widget code? Make sure to set `characterCount` in the `htmlEditorOptions`.

**Comment by mimiaopp** [comment]
![image](https://user-images.githubusercontent.com/37366343/140248285-6876caf1-bf8f-401f-b7c2-b9d12046a4b3.png)
我用的是 html_editor_enhanced: 2.4.0,终端为安卓

**Comment by tneotia** [comment]
that seems right. Are you typing in Chinese text or English text? Maybe it is an issue with Chinese text but works okay in English text.

**Comment by mimiaopp** [comment]
用的是英语

**Comment by tneotia** [comment]
hmmm... I think I only tested for web if I remember correct. I will test for Android when I have time to try and fix it. Sorry for the inconvenience!

**Comment by mimiaopp** [comment]
好的,感谢

**Comment by tneotia** [comment]
Unfortunately after looking deeper, the character limit cannot be supported in Android with the current implementation. Every android keypress is recorded as key `229` so I cannot distinguish between backspace and some character press. 

I would recommend using callback `onChange` and checking character count, then providing an error when the user goes over the allowed character count.

**Comment by bwrelawan** [comment]
thank you so much for suggestion! i will try it thanksss!!!
