### ISSUE TITLE
Can't choose another shade of color (foregroundColor, highlightColor) [BUG]

### ISSUE THREAD

**Issue by HaNeefz** [tneotia/html-editor-enhanced#148]
**Describe the bug**
Can't choose another shade of color in ColorButtons(). I can only see/choose the default color because the keyboard is blocked.

**To Reproduce**
1. Enter some text.
2. Select/Highlight the text to change its color.
3. Click the Foreground Color / Highlight Color button.
4. I can only see/choose the default color because the keyboard is blocked.
5. Press "Done" to make the keyboard disappear to see other shades. But when the keyboard disappears, the text selected from item 2 is canceled, making it unable to change the text color.

**Expected behavior**
I need color dialog that can be scrolled up/down for able to see another shade of color. Or something else please suggest me.

**Screenshots**
![B384E1FA-2143-4A66-858F-3E7AB10048D1](https://user-images.githubusercontent.com/47207756/135587254-ce32a48d-95be-47f5-a713-b280eafad362.png)
![31187D3A-F334-421B-9EAE-310BA7635B6D](https://user-images.githubusercontent.com/47207756/135587270-ae001cc5-db43-40d0-9111-52e813870950.png)

**Device:**
All Emulator,  Real Device iPhone Xr iOS14.2

**Comment by tneotia** [comment]
Thanks for reporting, I will see what I can do - maybe I should switch this package out for a different one as I have had issues with it in different projects.

**Comment by HaNeefz** [comment]
I will wait for the next version. thank you 🤝

**Comment by tneotia** [comment]
Fixed via e808d364b2d448ce248fd5934bb1228a15c02ead
