### ISSUE TITLE
Upload and play audio and videos

### ISSUE THREAD

**Issue by kekko7072** [tneotia/html-editor-enhanced#151]
Hey I am using HTML EDITOR and I need to upload audio. 
I implemented correctly upload and show of photos and I'd like to do the same with audio and video.
Is just implemented as photos or I need to code It from scratch? 
How can I display audio in web view? 
Thanks for the help.

**Comment by kekko7072** [comment]
@tneotia thank you so much!

**Comment by kekko7072** [comment]
@tneotia 
Hey I have correctly uploaded the video in my server, but 
I have this issue when I try to show it in my html using : 

` controller.insertNetworkImage(await event.ref.getDownloadURL());`

```
ReferenceError: src is not defined
    at http://localhost:55506/assets/packages/html_editor_enhanced/assets/summernote-lite.min.js:2:62285
    at c (http://localhost:55506/assets/packages/html_editor_enhanced/assets/jquery.min.js:2:28294)
    at Object.fireWith [as rejectWith] (http://localhost:55506/assets/packages/html_editor_enhanced/assets/jquery.min.js:2:29039)
    at t (http://localhost:55506/assets/packages/html_editor_enhanced/assets/jquery.min.js:2:30422)

```
I understand networkImage is not the correct command to videos, but how can I upload the link to the html page? Thankyou

**Comment by kekko7072** [comment]
@tneotia thank you so much!

**Comment by tneotia** [comment]
I looked into this... unfortunately I can't figure out how to use the existing dialog, it seems tied to images only and I cannot find where exactly this is coded. One solution may be to make a custom dialog for uploading video, and when uploading you can provide the user with those options for sizing or changing the alignment.

I will close this for now but I am open to further discussion, and if you need help implementing the above let me know.
