### ISSUE TITLE
How to make editor read only?

### ISSUE THREAD

**Issue by mine223** [tneotia/html-editor-enhanced#156]
I am trying to display initial content in the editor. I was wondering if there is an options where I can make editor read only like where I can make text field read only or uneditable.

**Comment by tneotia** [comment]
You can use `controller.disable()` to prevent the editing. This does apply a gray mask to indicate it is read-only, but this may satisfy your use case.

**Comment by mine223** [comment]
I tried using `controller.disable()` but it's only disabling toolbar. 
This is the code used below.
`controller = HtmlEditorController();
    SchedulerBinding.instance!.addPostFrameCallback((timeStamp) {
      controller!.disable();
    });`

This is the screenshot:
![Screenshot_1635773734](https://user-images.githubusercontent.com/74305467/139680152-e8a544ec-1506-4991-992d-91b60f3fab65.png)

**Comment by tneotia** [comment]
Using `SchedulerBinding` will not accomplish because it takes longer than first frame for the editor to initialize. Instead use the `onInit` callback in the widget parameters to make the editor disabled.

**Comment by mine223** [comment]
I used in on initState.. It showed null value passed.

`@override
  void initState() {
    // TODO: implement initState
    super.initState();
   
    controller = HtmlEditorController();
    controller!.disable();
  }`

Screenshot of the Error
![image](https://user-images.githubusercontent.com/74305467/139690856-7b97b4fa-9bb5-46ca-ad4e-2d8ad890c583.png)]

![Screenshot_1635778097](https://user-images.githubusercontent.com/74305467/139690979-7c841f08-44f5-47b6-9a07-e77eb95f5c3c.png)

**Comment by tneotia** [comment]
Yes, inside widget code you need to do this:

```dart
 callbacks: Callbacks(
    onInit: () => controller.disable()),
```

**Comment by mine223** [comment]
Thank you for your help it really worked..

I will close this thread now.. Once again thank you for your help.

**Comment by ayberkcal** [comment]
> Yes, inside widget code you need to do this:
> 
> ```dart
>  callbacks: Callbacks(
>     onInit: () => controller.disable()),
> ```

I think, disabled parameter should added as paramater to HtmlEditor class constructor.

**Comment by tneotia** [comment]
> I think, disabled parameter should added as paramater to HtmlEditor class constructor.

Sure I can do that, if you could please make a separate ticket that would be appreciated :)
