### ISSUE TITLE
[QUESTION] - Is it possible to set content padding on the editor?

### ISSUE THREAD

**Issue by vbaxan** [tneotia/html-editor-enhanced#159]
What I want to achieve, is to display the toolbar at the bottom of the editor, but inside of it.
This means that the portion of the editor containing content should be limited by this toolbar at the bottom.

I would use a Stack for this and place the toolbar on top and to the bottom of the editor, but in this case I would need to specify a content padding for the editor, so that the toolbar doesn't overlap the content.

Is it possible to do this?
In case not, do you see another option of achieving what I am after?

Thanks.

**Comment by tneotia** [comment]
I am a little confused on your use case... does `ToolbarPosition.belowEditor` not accomplish what you are trying to do? 

If not then can you try and explain what you mean by

>at the bottom of the editor, but inside of it.

and let's see if we can find a solution :)

**Comment by vbaxan** [comment]
What I want to end up with is similar to this:
![rich_text_editor_with_expandable_toolbar](https://user-images.githubusercontent.com/64584645/140472131-bc9fb0e0-2e95-476d-86b5-7d89770cab28.png)
When clicking on the "A" button, the toolbar should expand.
I figured that I would use `ToolbarPosition.custom` and then use a custom `ToolbarWidget` ands configure the way it gets shown and then hidden.
But, in order to achieve this, I would need to place it on top of the editor, and then give the editor some padding.

Another possibility that I can think of is to wrap the editor in a container and set bottom padding on the container itself, and draw the border around the container and remove it from the editor.
But the editor always displays the little marker thingie at the bottom, even when the toolbar is not displayed:
<img width="318" alt="Screenshot 2021-11-05 at 09 19 47" src="https://user-images.githubusercontent.com/64584645/140473098-c2717768-1742-483d-b84f-84c028884070.png">
Would it at least be possible to hide this somehow?

Thank you.

**Comment by vbaxan** [comment]
But you know what, I've manage to achieve the following:
<img width="310" alt="Screenshot 2021-11-05 at 09 55 41" src="https://user-images.githubusercontent.com/64584645/140477223-bd2e7246-bc9a-4d4f-8d9f-71a24993506d.png">
with `ToolbarPosition.custom` set and wrapping the editor and a custom `ToolbarWidget` in a Column and the `Column` in a  `Container`.
Something similar to:
```dart
Container(
      padding: const EdgeInsets.all(2.0),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(8.0),
        border: Border.all(color: borderColor),
      ),
      child: Column(
        children: <Widget>[
          HtmlEditor(
            controller: editingController,
            htmlEditorOptions: HtmlEditorOptions(
              shouldEnsureVisible: true,
              initialText: initialText,
              customOptions: _customOptions,
            ),
            htmlToolbarOptions: const HtmlToolbarOptions(
              toolbarPosition: ToolbarPosition.custom,
            ),
            callbacks: Callbacks(),
            otherOptions: const OtherOptions(
              decoration: BoxDecoration(),
            ),
          ),
          Visibility(
            visible: true,
            child: Row(
              children: [
                Expanded(
                  child: ToolbarWidget(
                    controller: editingController,
                    htmlToolbarOptions: const HtmlToolbarOptions(
                      toolbarPosition: ToolbarPosition.custom,
                      defaultToolbarButtons: <Toolbar>[
                        FontButtons(
                          underline: false,
                          clearAll: false,
                          strikethrough: false,
                          superscript: false,
                          subscript: false,
                        ),
                        StyleButtons(),
                        ListButtons(listStyles: false),
                      ],
                    ),
                    callbacks: Callbacks(),
                  ),
                ),
                .........,
              ],
            ),
          ),
        ],
      ),
    );
```
So, ultimately, if you feel like looking for another option would require a lot of time, then maybe it's not worth it and we can leave this as is.

**Comment by tneotia** [comment]
Your screenshot looks similar to the result of `ToolbarPosition.belowEditor` but maybe I fail to see the difference. As for hiding the handle line, you can do that with `controller.setFullscreen()` - run this code in onInit callback.

**Comment by vbaxan** [comment]
It does look like `ToolbarPosition.belowEditor`, but I am using specific custom display of the toolbar, using animations as well, so I need more control over the positioning and display of the toolbar, this is why I am using `ToolbarPosition.custom`.

Thanks for the suggestion to invoke `controller.setFullscreen()` in `onInit()` - it does hide the bottom handle line. 
But there is another problem here - there is 1dp line that shows up in its place when setting focus on the editor.

Let's say that I can live with displaying the handle line at all times for now, so please feel free to close this ticket in case you don't have anything else to add here.

Thanks and kudos for this great library!
