### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by indjec** [tneotia/html-editor-enhanced#16]
Hi, how do we upload a file in the onImageUpload callback, it accepts a paramater of FileUpload type which does not includes the path of the image, so how can we make a dio request to upload the file using MultipartFile

**Comment by tneotia** [comment]
Hi, I am working on improving that because I noticed it as well. I plan to add two properties to the `FileUpload`, one for the base64 data and one for the path. 

I'll update here once it is complete.

**Comment by tneotia** [comment]
I've added base64 parameter to `FileUpload`, so now you can use `MultipartFile.fromBytes()` to upload. See an [example](https://github.com/tneotia/html-editor-enhanced#example-for-onimageupload-and-onimagelinkinsert). I will edit this message when 1.7.1 is pushed to pub, for now the changes are only on master.

**Comment by tneotia** [comment]
Closing this for now, let me know if you need more help with this. Thanks!
