### ISSUE TITLE
[BUG] Selecting header in Header Dropdown makes buttons on the toolbar dissapear

### ISSUE THREAD

**Issue by ahimbeault** [tneotia/html-editor-enhanced#162]
Running Example code on Flutter Web v2.5.1. When I select a header from the Header Dropdown and then go to a new line, most of the buttons on the toolbar will disappear. I cannot get them to show up again without reloading the page. 

Example of the issue:
![ToolbarGoesAway](https://user-images.githubusercontent.com/77300382/141826073-33347327-52ca-46de-9223-b8233ae2e63b.gif)

The other dropdown menus do not cause this issue, only the Header drop down.

**Comment by tneotia** [comment]
This is very odd, I haven't seen this bug before. Thanks for reporting!

Out of curiosity, are there any exceptions visible in the console window when this happens?

**Comment by ahimbeault** [comment]
There are no exceptions in the console window when it happens.

**Comment by tneotia** [comment]
I cannot reproduce this on Flutter 2.8, CanvasKit renderer, example code.
