### ISSUE TITLE
[BUG] Full screen the editor window

### ISSUE THREAD

**Issue by Huanxin1997** [tneotia/html-editor-enhanced#164]
![image](https://user-images.githubusercontent.com/42678103/142332302-52a4a863-f1ff-4b2b-9878-cc9186b31c67.png)
Is there any API to control window size in HTML_Editor_enhanced package? 
According to the requirements of our project, we want editor window **full screen** display before the keyboard bounces up

**Comment by tneotia** [comment]
Yes, you have to provide height of editor, so if you want fullscreen then use `MediaQuery.of(context).size.height - appBarHeight` to get the available screen space.
