### ISSUE TITLE
[BUG] Hide "Open in new window" in Insert link dialog

### ISSUE THREAD

**Issue by Huanxin1997** [tneotia/html-editor-enhanced#165]
![image](https://user-images.githubusercontent.com/42678103/142395265-f041953f-c8d2-4f2a-973f-cbf3605907da.png)
When I insert a link, a dialog will be shown. If I can hide this selection ?

**Comment by tneotia** [comment]
Please see https://github.com/tneotia/html-editor-enhanced/issues/69, it shows how to override the dialog opening so you can provide a custom dialog to suit your needs. Hope it helps! :)
