### ISSUE TITLE
[BUG] Inside Form can't validate and update entered data like TextformField onsaved callback

### ISSUE THREAD

**Issue by khallid-itdevtech** [tneotia/html-editor-enhanced#168]
I have added inside form I want to validation like TextformField and onSaved callback to update value entered inside editor
Can you help please how can I achieve this ?

**Comment by tneotia** [comment]
For validation I recommend adding validation code inside `onChanged` callback, and then if you want to update the value inside editor you can use `controller.setText` which replaces all the current text in the editor.
