### ISSUE TITLE
[BUG] Dark mode background color on iOS

### ISSUE THREAD

**Issue by Huanxin1997** [tneotia/html-editor-enhanced#169]
![image](https://user-images.githubusercontent.com/42678103/142801738-cf4b5498-c506-4848-9c67-5157422b744f.png)
The background color is white in dark mode on iOS. But on Android device, it's black. 
Can I set dark mode background color as black on iOS devices?

**Comment by Huanxin1997** [comment]
I have view the issue `https://github.com/pichillilorenzo/flutter_inappwebview/issues/695`.
Would you please provide a new version?

**Comment by tneotia** [comment]
Hi, what was your solution for this issue? It would be helpful in case I need to add a fix into the package for this.
