### ISSUE TITLE
Web and other support

### ISSUE THREAD

**Issue by princestha** [tneotia/html-editor-enhanced#17]
Type question here.
Wow amazing package and it works amazing right out of the gate. Just wondering if there will be web support in the future? Thank you

**Comment by tneotia** [comment]
Hi there, the package supports Web officially. No extra configuration required, it should work immediately. Let me know if you have any issues with the Web support. Thanks!

**Comment by akshay0542** [comment]
Hello Tanay,

I am using this in flutter web, but I am not able to get the Text which is written in Text Editor, I am using getText() method with Controller, It looks like its been not returning anything as the log below the getText() statement is also not printing.

Please Help.

**Comment by tneotia** [comment]
Hi, this is a known issue and fixed by a851bf7. I will push a new release today with the various fixes from the past week.

**Comment by akshay0542** [comment]
Thanks Tanay,

I am looking forward towards your latest release. Thanks You.
