### ISSUE TITLE
[QUESTION] How to pass filePath in flutter.web

### ISSUE THREAD

**Issue by Abenstex** [tneotia/html-editor-enhanced#170]
Hello everyone,

I really liked your HTML editor and I hope I can use it for my use case. What I'm trying to do is to include custom elements in HTML. So my approach is to include the element definition/script in an HTML file and pass it in the HtmlEditorOptions. However, I have no idea how to get the filePath of the HTML file (located in assets) when I use flutter web. Is there a way around this problem?

**Comment by tneotia** [comment]
Any files stored in your assets folder of your app can simply be accessed with `assets/file.html`, and you pass that as a string to the `filePath` option of `HtmlEditorOptions`.

**Comment by Abenstex** [comment]
Gosh, sometimes I don't see the forest for the trees. That's so obvious...anyway, thanks!
