### ISSUE TITLE
[BUG] Custom toolbar preview

### ISSUE THREAD

**Issue by zohreh-jamali** [tneotia/html-editor-enhanced#171]
**Describe the bug**
I create a custom toolbar . first time that I navigate to the page the toolbar preview as I customized it . but after that any time I navigate to that page the default toolbar preview . 
here is the code that I use:

```
HtmlEditorController _controller = HtmlEditorController();

HtmlEditor(
                    controller: _controller,
                    height: 200,
                    autoAdjustHeight: true,
                    showBottomToolbar: false,
                    toolbar: const [
                      ColorBar(buttons: const [ColorButtons.color]),
                      Font(buttons: const [FontButtons.bold, FontButtons.italic, FontButtons.underline]),
                      Style(buttons: const [StyleButtons.style]),
                      Paragraph(buttons: const [ParagraphButtons.paragraph, ParagraphButtons.ul]),
                    ],
                    initialText: initialText,
                    callbacks: Callbacks(
                      onChange: (text) {
                        print(text);
                      },
                    ),
                  )

```

**Device:**
Emulator pixel 3a XL ,physical device:  Sony xperia XA

and due to my project I use version 1.6.0

**Comment by zohreh-jamali** [comment]
This problem solve for me with this solution: 
1: remove the initialText parameter from HtmlEditor widget ,
2: add onInit call back to this widget and use controller.setText(myText); inside the callback

**Comment by tneotia** [comment]
I am going to reopen to investigate this, very odd that the toolbar resets to the default setting the second time.

**Comment by tneotia** [comment]
Seems like you are using a very old version of the library. I suggest upgrading and seeing if the issue is still present.
