### ISSUE TITLE
[QUESTION] Get clicked URL in flutter web

### ISSUE THREAD

**Issue by Abenstex** [tneotia/html-editor-enhanced#172]
Hello everyone,

is there a way to get the link URL that was clicked in flutter web? I saw that there is a onNavigationRequestMobile but apparently that works only on mobile platforms. So I'm curious if there's a way to get this information on web.
If not, I'd like to know if there's a possibility to pass data back from the editor to dart/flutter in general?
The reason I'm asking is, because I have an HTML custom element that extends HTMLAnchorElement to store some additional information. However, currently I don't see a way to get that information back from the editor.

**Comment by tneotia** [comment]
Currently there is no capability to listen to URL changes on web. This shouldn't be too hard, I can probably use JS `window.onLoad` to get URL changes and then provide a callback to listen to this behavior. I think preventing the default behavior might be a bit difficult though, but I will see what I can do.

As for passing data to and from, check [webInitialScripts](https://github.com/tneotia/html-editor-enhanced#webinitialscripts) documentation, you can ask the webview to run some JS and return a response back.

**Comment by Abenstex** [comment]
Thanks. If you can think of something regarding URL changes that would be great, but no worries.

**Comment by Abenstex** [comment]
I just did some digging and saw that you use flutter_inappwebview under the hood. flutter_inappwebview again fires an onConsoleMessage event. So I changed my custom element to issue a console message in a certain format to make it easily recognizable. In case catching URL events is too much work, maybe you could make an onConsoleMessage callback?

**Comment by tneotia** [comment]
The web implementation doesn't use flutter_inappwebview as WebView is not supported in flutter web. I use a custom IframeElement so I have to manually add JS callbacks, but they function with JS postMessage so it is similar to onConsoleMessage.

**Comment by tneotia** [comment]
I tried to implement this on Flutter Web but was unable to find a solution. The Summernote library creates the popup when clicking on the `<a>` tag so I have no way of overriding its behavior unfortunately.
