### ISSUE TITLE
[BUG] Toolbar dialog background in Dark Mode

### ISSUE THREAD

**Issue by Huanxin1997** [tneotia/html-editor-enhanced#173]
![image](https://user-images.githubusercontent.com/42678103/143159051-e09a7cb9-bcc4-4c0f-b48f-284d1d000f0d.png)
Hi author.
In dark mode, when I click toolbar button, and show dialog, the background color is white, and the font color is also white.
Currently, I tried setting alertDialog background color, it was work. If there is any other methods can change the background of dialog? 
![image](https://user-images.githubusercontent.com/42678103/143160056-f3298616-677e-47da-9374-15e94a39b621.png)

**Comment by tneotia** [comment]
Hi, try setting `dialogBackgroundColor` in your theme and it should follow that color.
