### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by InGuuuW** [tneotia/html-editor-enhanced#174]
You can run it before adding "html_editor_enhanced: ^2.4.0+1". After adding it, it fails.

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.6 20G165 darwin-arm, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.62.3)
[✓] Connected device (1 available)

• No issues found!

**Comment by tneotia** [comment]
Hi, please check https://stackoverflow.com/questions/67443265/error-regarding-undefined-method-map-for-nilnilclass-for-flutter-app-cocoap to see if it resolves your issue :)
