### ISSUE TITLE
How can i set the token to inAppWebView[QUESTION]

### ISSUE THREAD

**Issue by AceChen1** [tneotia/html-editor-enhanced#182]
Hi guys, i have a question, as you know , the image resource may be is internal, we may need use token to get the resource, looks like no any api or call back i can put the token to the header when visit the image by link

**Comment by tneotia** [comment]
Hi, please check https://github.com/tneotia/html-editor-enhanced/discussions/166, maybe one of the solutions described there can be good for your use case?
