### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by AceChen1** [tneotia/html-editor-enhanced#184]
can i select an image from mobile, then compress it then show it on the editor ?

**Comment by tneotia** [comment]
Yes, you can use the `mediaUploadInterceptor`, which will give the path of the picked image. Then you can compress it and insert the compressed base64 data into the editor.

See [here](https://github.com/tneotia/html-editor-enhanced#example-for-linkinsertinterceptor-medialinkinsertinterceptor-otherfilelinkinsert-mediauploadinterceptor-and-onotherfileupload) for example usage.

**Comment by AceChen1** [comment]
> Yes, you can use the `mediaUploadInterceptor`, which will give the path of the picked image. Then you can compress it and insert the compressed base64 data into the editor.
> 
> See [here](https://github.com/tneotia/html-editor-enhanced#example-for-linkinsertinterceptor-medialinkinsertinterceptor-otherfilelinkinsert-mediauploadinterceptor-and-onotherfileupload) for example usage.

OK, Get it, Thanks.
