### ISSUE TITLE
[QUESTION] how to modify foreColorSelected and backColorSelected in ToolbarWidget?

### ISSUE THREAD

**Issue by SheepYang1993** [tneotia/html-editor-enhanced#186]
It is a private variable

**Comment by tneotia** [comment]
Why are you needing to modify it?

**Comment by SheepYang1993** [comment]
> Why are you needing to modify it?

i need to translate the text on ColorPicker, so i customize ColorPickerDialog,  need to modify it at this time

**Comment by tneotia** [comment]
Yes this was an oversight on my part, I have added this feature and you can use in the next update without copying code from inside the package. Just use the `updateStatus`  function inside `onButtonPressed` and pass the color inside, like this:

```dart
onButtonPressed: (ButtonType type, bool? status,
                      Function? updateStatus) {
                    print(
                        "button '${describeEnum(type)}' pressed, the current selected status is $status");
                    //show dialog and get new color
                    updateStatus!(color);
                    return false;
                  },
```

**Comment by SheepYang1993** [comment]
Wait for your next update
Thank you!
