### ISSUE TITLE
Not Working on Safari

### ISSUE THREAD

**Issue by rutaba1** [tneotia/html-editor-enhanced#188]
Hi, I have been using using package but in my web app I have an overlay and inside this overlay there is rich text editor. But the editor itself is not clickable. I can't enter any data to it in safari and in other browsers making a selection or creating link causes text to flicker or dissapear completely. I'm not using html renderer for web because I want to use canvas kit for animations

**Comment by cksoft0807** [comment]
Working fine with safari (M1 Mac) and flutter 2.8 without overlay. Since Flutter has various problems with the display in the safari browser, this may not be a problem with the component. the option web-renderer html may help

**Comment by tneotia** [comment]
Using latest stable Flutter with canvaskit is supposed to work just fine, there should be no flickering or disappearing of elements anymore. Closing for now, feel free to comment if you have this issue still on Flutter 2.8.
