### ISSUE TITLE
How to remove html editor bar

### ISSUE THREAD

**Issue by iamkunalpitale** [tneotia/html-editor-enhanced#189]
![html](https://user-images.githubusercontent.com/26413565/145669225-b62b397d-7fba-4fbb-ad42-e617ba1e9e54.png)

How to remove this HTML Editor Bar (show in the image with black arrow) ?

**Comment by tneotia** [comment]
To remove the bottom bar with the resize handle call `controller.setFullscreen()` inside the `onInit` callback.
