### ISSUE TITLE
[QUESTION] Removing bottom toolbar, missing option?

### ISSUE THREAD

**Issue by robaolana** [tneotia/html-editor-enhanced#190]
I'm trying to remove the bottom toolbar since I just wanted the text editor to be full page. It seems the showBottomToolbar variable is no longer under HtmlEditorOptions()?

<img width="308" alt="Screen Shot 2021-12-11 at 13 38 51" src="https://user-images.githubusercontent.com/51477157/145687841-7f13b3b3-151c-4c12-852c-f928871dd08b.png">

Somehow related question, after removing the bottom toolbar, how can I make sure the editor takes up the full page? autoAdjustHeight: true seems to cap it somewhere in the middle of the screen. Thank you.

**Comment by tneotia** [comment]
To remove that gray bar with the resize handle, call `controller.setFullscreen()` inside the `onInit` callback. To make the editor fullscreen, you have to manually set the height inside `OtherOptions`. It defaults to `500` so it appears half the screen or so. For your use case you should use `MediaQuery.of(context).size.height - appBarHeight` (however tall your appbar is).
