### ISSUE TITLE
[QUESTION] Android physical machine paste is basically unsuccessful.

### ISSUE THREAD

**Issue by islinjj** [tneotia/html-editor-enhanced#191]
When I use the Android physical machine, the first copy and paste is successful, return to the previous page, enter the editor and paste other content, it will be pasted into the last copied content

**Comment by tneotia** [comment]
Hi, can you send a screen recording of the problem? I'm not able to understand your issue - what exactly you mean by "pasted into the last copied content". The editor should be empty if you go back and re-enter the editor screen, so I don't know why the last content is still showing.

**Comment by islinjj** [comment]
Uploading android cannot paste.mp4…

**Comment by islinjj** [comment]
https://user-images.githubusercontent.com/32004335/146164481-e738dcb7-13f7-47c4-bd6b-38d4a12c88f7.mp4

**Comment by tneotia** [comment]
I am unable to reproduce this on Flutter 2.8, Samsung Galaxy S10+ (Android 12) using Gboard. Paste behavior is not something modified by this package, I would check your keyboard and see if the behavior is present on other apps the same way.
