### ISSUE TITLE
[QUESTION] Embedded YouTube/Vimeo videos

### ISSUE THREAD

**Issue by Talgat777** [tneotia/html-editor-enhanced#193]
Hi!

Is there a way to embed a YouTube and/or Vimeo video? Is the a plugin that I can use? 

Thanks!

**Comment by tneotia** [comment]
The video chooser allows users to insert a video by URL if I remember correctly. So users can insert a youtube embed link, and it will show inside the editor window.

**Comment by Talgat777** [comment]
Works like a charm, thanks! For those who don't know you need to click on "insert Link" button and paste the iFrame link to "URL" and keep the "Text to display" textfield empty!
