### ISSUE TITLE
[BUG]It can only be used normally on the home page?

### ISSUE THREAD

**Issue by liaoxuewei** [tneotia/html-editor-enhanced#194]
**Describe the bug**
It can only be used normally on the home page?

**To Reproduce**
1. create a new HtmlEditorExample class like https://pub.flutter-io.cn/packages/html_editor_enhanced/example
2. create a home page class, with route to HtmlEditorExample
3. home page class triger to route HtmlEditorExample

**Expected behavior**
It can only be used on the sub page.

**Screenshots**
On home page(Normal):
![image](https://user-images.githubusercontent.com/970765/147035079-b55706c4-06be-45c9-b768-db18debbaef2.png)
On sub page(Absnormal):
![image](https://user-images.githubusercontent.com/970765/147035100-d55c2654-2b8a-4baa-8eac-2d9ae71ed731.png)

**Device:**
android 7.x

**Additional context**
If home page point to HtmlEditorExample, it work well.

**Comment by liaoxuewei** [comment]
Remove HtmlEditor widget define, the other widget work well.
![image](https://user-images.githubusercontent.com/970765/147035277-bad41996-5429-40a0-a20b-ff5eb279b17c.png)

**Comment by liaoxuewei** [comment]
It seems that it can run on the phone, but not the simulator.

**Comment by tneotia** [comment]
As long as you use different controllers and have the required permissions, it should function on all pages.

**Comment by liaoxuewei** [comment]
> 

Can you explain in more detail how to do it? Thank you!
Note: If it is on the home page, the simulator can also work normally. Does this mean that this situation should have nothing to do with permissions?
@tneotia
