### ISSUE TITLE
Hello, I want to implement such a custom UI. Can it be achieved?

### ISSUE THREAD

**Issue by 2530442368** [tneotia/html-editor-enhanced#195]
![image](https://user-images.githubusercontent.com/63909463/147042742-7e92908b-568e-4494-b821-0e31b1aea28a.png)

**Comment by tneotia** [comment]
Yes, you can provide custom buttons to do all this functionality. See https://github.com/tneotia/html-editor-enhanced#customtoolbarbuttons-and-customtoolbarbuttonsinsertionindices
