### ISSUE TITLE
[QUESTION] i want to resize about upload image

### ISSUE THREAD

**Issue by metatokengamer** [tneotia/html-editor-enhanced#200]
hello. thank you for your flutter package.
but i have problem.
when i upload image (in my device)
i can see image in text area
but image is very big.
maybe default image zoom is 100%
how can i change image size?(height, width)..

**Comment by tneotia** [comment]
I would suggest trying to use `mediaUploadInterceptor` and manually adding the width inside each `img` tag before it is inserted into the editor.

Check [here](https://github.com/tneotia/html-editor-enhanced#example-for-linkinsertinterceptor-medialinkinsertinterceptor-otherfilelinkinsert-mediauploadinterceptor-and-onotherfileupload) for how to use mediaUploadInterceptor.
