### ISSUE TITLE
[BUG] HTML editor is still loading but never loaded

### ISSUE THREAD

**Issue by ziasultan2** [tneotia/html-editor-enhanced#203]
**Describe the bug**
Whenever I try to select anything from tool it  throws error

```
2022-01-09 17:00:49.757401+0600 Runner[566:51451] [VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Exception: HTML editor is still loading, please wait before evaluating this JS: document.execCommand('formatBlock', false, 'h3');!
#0      HtmlEditorController._evaluateJavascript (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:262:9)
#1      HtmlEditorController.execCommand (package:html_editor_enhanced/src/html_editor_controller_mobile.dart:62:5)
#2      ToolbarWidgetState._buildChildren.<anonymous closure> (package:html_editor_enhanced/src/widgets/toolbar_widget.dart:598:26)
<asynchronous suspension>
2022-01-09 17:00:51.405622+0600 Runner[566:51451] flutter: {style: p, fontName: sans-serif, fontSize: 3, font: [false, false, false], miscFont: [false, false, false], color: [rgb(0, 0, 0), ], paragraph: [false, false], align: [true, false, false, false], lineHeight: normal, direction: ltr}
```
**Expected behavior**

**Screenshots**

**Device:**
all device

**Comment by tneotia** [comment]
Can you post your widget code please? And are there any other errors besides this one?

**Comment by ziasultan2** [comment]
Thank you for your quick response.
Here is my code that I copied from readme section
HtmlEditor(
        controller: controller, //required
        htmlEditorOptions: HtmlEditorOptions(
          hint: "Your text here...",
          //initalText: "text content initial, if any",
        ),   
        otherOptions: OtherOptions(
          height: 400,
        ),
    )

Would love to get a response ASAP
Thank you in advance

**Comment by tneotia** [comment]
Did you try and add internet permission to Android manifest? <uses-permission android:name="android.permission.INTERNET"/>

**Comment by ziasultan2** [comment]
It's occurring in iOS I didn't try in android

**Comment by editionc18** [comment]
I got same problem with same code..how to solve it?

**Comment by tneotia** [comment]
@editionc18 can you clone the repo and try example app, see if it gives same issue? I cannot reproduce this on my Mac Simulator.

**Comment by editionc18** [comment]
I solved problem
I run `flutter clean` and restart build, I got this message:

```
[!] App requires Multidex support
    Multidex support is required for your android app to build since the number of methods has exceeded 64k. You may
    pass the --no-multidex flag to skip Flutter's multidex support to use a manual solution.

    Flutter tool can add multidex support. The following file will be added by flutter:

        android/app/src/main/java/io/flutter/app/FlutterMultiDexApplication.java

Do you want to continue with adding multidex support for Android? [y|n]: y
```
And the editor worked in my app.

**Comment by tneotia** [comment]
Interesting... I didn't know that would be an issue. Will keep that in mind for future questions. Thanks!
