### ISSUE TITLE
Any button click in Dialog box on top of html editor is not working it is clicking in editor 

### ISSUE THREAD

**Issue by SainathThota** [tneotia/html-editor-enhanced#206]
**Describe the bug**
Any button click in Dialog box on top of html editor is not working it is clicking in editor 

**To Reproduce**

**Expected behavior**
Click on dialog should click the dialog button not underneath html editor  

**Screenshots**
![image](https://user-images.githubusercontent.com/13947829/149345311-6c2765b9-255e-4a31-a760-40c27be354e7.png)

**Device:**
Web

**Additional context**

**Comment by tneotia** [comment]
Please check https://github.com/tneotia/html-editor-enhanced/issues/157

**Comment by hariharadhamodaran** [comment]
Flutter 2.13.0-0.1.pre • channel beta 

working in above flutter beta version
