### ISSUE TITLE
1：Focus not showing on 111，2：How to remove this arrow

### ISSUE THREAD

**Issue by 2530442368** [tneotia/html-editor-enhanced#207]
1：Focus not showing on 111
![image](https://user-images.githubusercontent.com/63909463/149611557-d1e3662f-a998-48bc-a2de-6b1e3fcf0390.png)
2：How to remove this arrow
![image](https://user-images.githubusercontent.com/63909463/149611587-7baee818-6e50-40a1-a97e-504aa5864c79.png)

**Comment by tneotia** [comment]
Hi, please check https://github.com/tneotia/html-editor-enhanced/issues/24 for 1st issue.

for 2nd issue please set `toolbarType: ToolbarType.nativeScrollable`.
