### ISSUE TITLE
[QUESTION] Can i remove below option from the editor ? 

### ISSUE THREAD

**Issue by aniketsongara** [tneotia/html-editor-enhanced#208]
I don't want this 
![Screenshot 2022-01-17 at 6 07 37 PM](https://user-images.githubusercontent.com/59816309/149770886-fb6697d3-fbdf-4b61-8908-ca52a8f25232.png)

**Comment by aniketsongara** [comment]
Anything ?

**Comment by tneotia** [comment]
Sorry, this got lost in the stack. Unfortunately this is just standard iOS webview behavior so I don't have a way to control this. It seems you are using simulator, on a physical ios device the keyboard will be under this option, so users click done to hide the keyboard.
