### ISSUE TITLE
[BUG] Not working well with flutter tabs

### ISSUE THREAD

**Issue by gtu-myowin** [tneotia/html-editor-enhanced#213]
**Describe the bug**
Not working well with [flutter tab](https://docs.flutter.dev/cookbook/design/tabs). The content of the HtmlEditor reset when come back to the tab.

**To Reproduce**
1. Create 2 tabs
2. Put one `HtmlEditor` in each tab
3. Go to tab 2 and write something in `HtmlEditor`
4. Go to tab 1 and come back to tab 2
5. The content you have just written is gone

**Comment by sscast** [comment]
I had similar problem with Forms, then I found out that using a global key can help preserve the content when the widget is rebuild. I think it should works similar for tabs, you can give it a try.

**Comment by gtu-myowin** [comment]
I am using a form key since the start but it isn't helping.

```dart
class _EditPropertyState extends State<EditProperty> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
```

```dart
      body: SingleChildScrollView(
        child: Container(
          margin: const EdgeInsets.all(20),
          child: FittedBox(
            child: Form(
              key: _formKey,
              child: Column(
```

I am using like so.

**Comment by sscast** [comment]
> I am using a form key since the start but it isn't helping.
> 
> ```dart
> class _EditPropertyState extends State<EditProperty> {
>   final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
> ```
> 
>  ```dart
>       body: SingleChildScrollView(
>         child: Container(
>           margin: const EdgeInsets.all(20),
>           child: FittedBox(
>             child: Form(
>               key: _formKey,
>               child: Column(
> ```
> 
> I am using like so.

I believe in your case you need a key for the your HTMLEditor, as you want the content to be memorized in HTMLEditor. Something like: 
`HTMLEditor(
        key: _someKey,
...
)
`

**Comment by gtu-myowin** [comment]
I have assigned a different controller to each `HtmlEditor`. Isn't it enough? I have tried your recommendation as well but still not working. I am still trying around.

```dart
TabBarView(
  children: [
    Column(
      children: [
        InputField(controller: _myanmarTitleController, label: 'Myanmar Title'),
        rowSpacing,
        HtmlEditor(
          key: UniqueKey(),
          controller: _myDescriptionController,
          htmlEditorOptions: HtmlEditorOptions(
            hint: "Property description in Burmese",
            initialText: _myDescription,
          ),
        ),
      ],
    ),
    Column(
      children: [
        InputField(controller: _englishTitleController, label: 'English Title'),
        rowSpacing,
        HtmlEditor(
          key: UniqueKey(),
          controller: _enDescriptionController,
          htmlEditorOptions: HtmlEditorOptions(
            hint: "Property description in English",
            initialText: _enDescription,
          ),
        ),
      ],
    )
  ],
),
```

I tried to put the key at each `Column` widget as well but the result is the same.

**Comment by gtu-myowin** [comment]
I found the root of the cause! I am setting `initialText` content but not updating it when the input is change. So, I added the callback like so

```dart
HtmlEditor(
  controller: _myDescriptionController, //required
  htmlEditorOptions: HtmlEditorOptions(
    hint: "Property description in Burmese",
    shouldEnsureVisible: true,
    initialText: _myDescription,
  ),
  callbacks: Callbacks(
    onChangeContent: (String? changed) {
      if (changed != null && changed != _myDescription) {
        setState(() => _myDescription = changed);
      }
    }, 
  ),
),
```

But now, the `HtmlEditor` rebuilds every time I type and it is so inefficient. I am quite sure that the following part

```dart
if (changed != null && changed != _myDescription) {
  setState(() => _myDescription = changed);
}
```
 and the rebuilding issues should be handled by the package itself. What do you think?

**Comment by gtu-myowin** [comment]
It's been me the whole time. I forgot to delete the `UniqueKey()` I set on `TabBarView()`. That's why it is rebuilding every time the content is changed. Final working code looks like this

```dart
HtmlEditor(
  controller: _myDescriptionController, //required
  htmlEditorOptions: HtmlEditorOptions(
    hint: "Property description",
    initialText: _myDescription,
  ),
  callbacks: Callbacks(
    onChangeContent: (String? changed) {
      setState(() => _myDescription = changed);
    },
  ),
)
```

Thank you @sscast for your helps.
