### ISSUE TITLE
How to get rid of the resizing button at the bottom?

### ISSUE THREAD

**Issue by BurningAXE** [tneotia/html-editor-enhanced#216]
How can we get rid of this button and its bar:
![Screenshot (Feb 9, 2022 10_28_13 PM)](https://user-images.githubusercontent.com/5779978/153285024-194d9b45-1361-41a8-8982-b1a1e9131a4a.png)
It doesn't work so it only creates confusion. 
I didn't find an option out of the box. A little research led me to think it's part of the Summernote component which does have an option to remove it according to [this SO](https://stackoverflow.com/questions/39046537/summernote-remove-resize-bar)
The editor has `customOptions` which is intended to set options to Summernote, however I don't know the proper format this options should be put in. Can you provide a working example? Or please correct me if I am on a wrong vector. Thanks!

**Comment by tneotia** [comment]
See https://github.com/tneotia/html-editor-enhanced/issues/42
