### ISSUE TITLE
[BUG] Android Glitch when move to other page/screen 

### ISSUE THREAD

**Issue by weebsproject** [tneotia/html-editor-enhanced#217]
Hi i have some bug/glitch on UI.
if i open the htmleditor, then move to other page there's some glitch (see attached)
its only happen when i ran on android, 

https://user-images.githubusercontent.com/75978848/153698861-8af224f3-ae0a-47b1-9492-ce89935b30a7.mp4

below code that I copy and paste from example file

![carbon](https://user-images.githubusercontent.com/75978848/153699110-28d713f1-c7a8-407c-a8a6-9ff1bc954730.png)

**Comment by weebsproject** [comment]
here's a console logs

`W/ContentCatcher(22643): Failed to notify a WebView
D/EgretLoader(22643): EgretLoader(Context context)
D/EgretLoader(22643): The context is not activity
I/System.out(22643): recordForce value 6
W/ContentCatcher(22643): Failed to notify a WebView
I/flutter (22643): done
I/flutter (22643): init
W/ContentCatcher(22643): Failed to notify a WebView`

**Comment by tneotia** [comment]
This is likely due to the hybrid composition webview. You can use the `useHybridComposition: false` option to see if it removes the animation issue.

**Comment by weebsproject** [comment]
sorry, where is usehybirdcomposition located?

**Comment by tneotia** [comment]
Sorry I should have clarified, this is on master branch only (not released to pub.dev). You can use git dependency and it will be inside `HtmlEditorOptions`.
