### ISSUE TITLE
[BUG] HTML editor is still loading, please wait before evaluating this JS: 

### ISSUE THREAD

**Issue by ajay-zartek** [tneotia/html-editor-enhanced#221]
Shows error Exception: HTML editor is still loading, please wait before evaluating this JS..
When inserting HTML using `controller.insertHtml(<html text>);` and never updating the widget. 

Error:
`Exception: HTML editor is still loading, please wait before evaluating this JS: $('#summernote-2').summernote('pasteHTML', '<h1>test</h1>');!`

Widget:
```
 HtmlEditor(
          controller: controller,
          htmlEditorOptions: const HtmlEditorOptions(
            hint: "Type here",
          ),
        ),
```

**Comment by iluvgy** [comment]
Got the same error, managed to solve it by moving the controller declaration outside the build method.

From

`  
  @override
  Widget build(BuildContext context) {
  HtmlEditorController controller;

  @override void initState() {
    super.initState();
    controller = HtmlEditorController();
  }

  @override
  Widget build(BuildContext context) {
...
  `


to 

`  HtmlEditorController controller;

  @override void initState() {
    super.initState();
    controller = HtmlEditorController();
  }

  @override
  Widget build(BuildContext context) {`

**Comment by tneotia** [comment]
Yes, this is how it should be done. Please do not initialize the controller inside build method.

**Comment by stefan-weinand** [comment]
I still get this error, even if I initialize the controller outside the build method.

**Comment by tneotia** [comment]
This error also occurs if the webview is not initialized properly. Please make sure internet permission is added to androidmanifest, and test webview functionality yourself by instantiating an `InAppWebView` widget.

**Comment by kuyaC** [comment]
- I initialize my controller in initState(),
- I have Internet permission in my AndroidManifest.xml
- and I tested `return InAppWebView()` in my build() functions, without any Exceptions/Errors in the console.

But I still get:
Exception: HTML editor is still loading, please wait before evaluating this JS: $('#summernote-2').summernote('code', ...

**Comment by sunnyasr** [comment]
Getting same error 
![image](https://user-images.githubusercontent.com/32053743/218680994-29c6cea5-fce0-4c35-a620-512cd95b1176.png)
