### ISSUE TITLE
[BUG] iOS: Toolbar buttons don't show because "No Material Widget found"

### ISSUE THREAD

**Issue by ksilz** [tneotia/html-editor-enhanced#226]
**Describe the bug**
I don't use the Material Design widgets in my iOS app. That's why the toolbar buttons don't show and throw this error instead: "No Material widget found"

**To Reproduce**
1. Clone [this repo](https://github.com/ksilz/test_html_editor).
2. Run it on an iOS 15 simulator.

**Expected behavior**
The toolbar buttons show.

**Screenshots**
![image](https://user-images.githubusercontent.com/1061209/155608931-bebaed67-adc5-4250-83bc-d5e9644299e8.png)

**Device:**
iOS 15.2 simulator

**Additional context**
The set-up of this app is derived from my real production app. I think that everybody runs into this error when using toolbar buttons on iOS. So I think there should documentation on the proper setup.

I encountered this bug when trying to recreate #227 in a separate project.

**Comment by tneotia** [comment]
You can probably just wrap the HtmlEditor in a `Material` widget. This does nothing as for the appearance of the page / editor, just adds the required material dependencies that Icons and such need. Make sure to set the background color transparent, and you should be good.

**Comment by ksilz** [comment]
Yes - that worked!
