### ISSUE TITLE
[BUG] When i use controller.insertHtml(); method in web it doesn't work and throws this message. What can be reason

### ISSUE THREAD

**Issue by mamasd** [tneotia/html-editor-enhanced#23]
Type question here.
```
TypeError: Cannot read property 'includes' of null
                at handleMessage (about:srcdoc:47:30)
```

**Comment by tneotia** [comment]
Hmm this is a bug in the javascript code, I'll look into this. Could you post your widget code to make sure I can replicate it?

**Comment by tneotia** [comment]
I tried this using the example app but I could not reproduce (click the Insert HTML button below the editor).

**Comment by tneotia** [comment]
Without further details I will close this, let me know if it is still an issue. Thanks.

**Comment by Achudh** [comment]
> I tried this using the example app but I could not reproduce it (click the Insert HTML button below the editor).

I got this error when I'm loading the text in the init state
@tneotia  the issue still exists.
