### ISSUE TITLE
How can i remove below view?

### ISSUE THREAD

**Issue by CharanjeetRPOPS** [tneotia/html-editor-enhanced#231]
How can i remove below highlighted view, it appears on both on keyboard open/close ? @tneotia 

![Screenshot_1647372360](https://user-images.githubusercontent.com/36876618/158456190-9df3738f-67ca-4f19-82ee-baeb33925d55.png)
![Screenshot_1647372420](https://user-images.githubusercontent.com/36876618/158456199-3b362cea-91c5-4769-b3ca-09a98e96fcb7.png)

**Comment by tneotia** [comment]
Please see #42.

**Comment by CharanjeetRPOPS** [comment]
@tneotia 
Thanks for the response..
I applied the same, now i am able to see a divider and empty space as highlighted in attached image.
How can i remove that?


![Screenshot_1647439433](https://user-images.githubusercontent.com/36876618/158608449-52a3e664-711e-4524-a806-e94b3b016d12.png)

**Comment by CharanjeetRPOPS** [comment]
**_(As per my requirement it want to show toolbar options when keyboard gets visible so i have removed toolbar options,
and it gets visible on keyboard visibility)_**

**When i disabled editor using contorller.disable(), it turns out grey in color
Can it be kept with same color as original and not grey ?**

![Screenshot_1647457576 (1)](https://user-images.githubusercontent.com/36876618/158676049-87148e59-f7ef-49ea-82f2-3f9f1815b0e9.png)



**After disabling editor when i tap anywhere it shows white color background which popups out from bottom, as it is highlighted seen in image 
how can i get it removed?**

![Screenshot_1647458691](https://user-images.githubusercontent.com/36876618/158678215-44fcf23a-4f09-4fe3-adb7-d4861ba82b12.png)





**Thanks @tneotia**
