### ISSUE TITLE
[QUESTION]Is there any method to persist editor cursor/selection when keyboard is dismissed?

### ISSUE THREAD

**Issue by yuanqifd** [tneotia/html-editor-enhanced#236]
Hi,
May I ask a question about focus of the editor, that is, when keyboard is closed, the editor loses focus.
I have tried to restore the cursor/selection after closing keyboard in this way:

- save the selection range by invoking
   _evaluateJavascript(source: "\$('#summernote-2').summernote('saveRange');");
- focus the editor and restore the selection range by invoking
   _evaluateJavascript(source: "\$('#summernote-2').summernote('focus');"); 
   _evaluateJavascript(source: "\$('#summernote-2').summernote('restoreRange');");

But it does not work.
Is there any method to persist editor cursor/selection when keyboard is dismissed?
Btw, I dismiss keyboard by SystemChannels.textInput.invokeMethod<void>('TextInput.hide')

Thanks.

**Comment by tneotia** [comment]
Unfortunately no, this is related to #47, webview support on Flutter should handle this internally but it does not.
