### ISSUE TITLE
[BUG] Toolbar dropdown options are not clickable if they overlap the text box on Flutter 2.10.3

### ISSUE THREAD

**Issue by LucasBourne** [tneotia/html-editor-enhanced#237]
**Describe the bug**
We've been using this package for a few months now without issue, on Flutter version 2.5.0.

Since updating to the latest SDK version (2.10.3), we've been unable to select items from the toolbar dropdown menus (i.e. font size, text style). Clicking on the dropdown button opens the list up, but all dropdown options overlapping the text box aren't clickable.

**To Reproduce**
1. Navigate to HtmlEditor widget in application (Must have a dropdown button present in editor toolbar)
2. Click on dropdown button to expand dropdown options
3. Click one of the options towards the bottom of the list (must overlap the text box immediately below the toolbar).

See video for example.

**Expected behavior**
Clicked dropdown option should be selected.

**Screenshots**

https://user-images.githubusercontent.com/21283251/159734754-63e1ec02-6c8b-4eec-b485-d4f2f8f536eb.mp4

**Device:**
Chrome Version 97.0.4692.99 (Official Build) (64-bit)
Windows 10, I've also seen users experience the same behaviour on MacOS

**Additional context**
This has only been tested on Flutter Web, so I cannot confirm if this is happening on mobile applications too.

Keeping the codebase identical and rolling Flutter back to 2.5.0 seems to fix the issue. I've tried running the app on both versions of flutter from two different machines, and both times this issue is only present on 2.10.3.

**Comment by tneotia** [comment]
Can you try overriding the pointer_interceptor package version in pubspec:

```yaml
dependency_overrides:
    pointer_interceptor: 0.9.3
```

I need to update dependencies.... will try to get to that very soon.
