### ISSUE TITLE
[QUESTION] How to remove newline at the top of the editor?

### ISSUE THREAD

**Issue by radikz** [tneotia/html-editor-enhanced#238]
Hi, I want to ask is there any way to remove the newline at the top of the editor?

![html_enhance_question1](https://user-images.githubusercontent.com/10457723/159822695-0e2dedc4-4538-45b1-a9a4-b19aa5b602b0.png)

I want the cursor at the top of the editor when I click the editor for the first time like the image below.

![html_enhance_question2](https://user-images.githubusercontent.com/10457723/159823139-53812764-08ea-406b-92b2-4c13004eb2d5.png)

Here is the code that I used:
```dart
HtmlEditor(
  controller: _descriptionController,
  htmlEditorOptions: const HtmlEditorOptions(
    hint: "Your text here...",
  ),
  otherOptions: const OtherOptions(
    height: 300,
  ),
  htmlToolbarOptions:
      const HtmlToolbarOptions(defaultToolbarButtons: [
    FontButtons(
      strikethrough: false,
      subscript: false,
      superscript: false,
    ),
    ListButtons(listStyles: false),
    ParagraphButtons(
      alignCenter: false,
      alignJustify: false,
      alignLeft: false,
      alignRight: false,
      lineHeight: false,
      caseConverter: false,
      textDirection: false,
    )
  ]),
),
```

**Comment by tneotia** [comment]
Please see #24 for more details on this issue

**Comment by radikz** [comment]
Hi, tneotia. Thanks for the reply. I'll close this for now.
