### ISSUE TITLE
[QUESTION] How to give input as  manual html string and get output in editor as formatted text

### ISSUE THREAD

**Issue by Dharanipalani** [tneotia/html-editor-enhanced#242]
Type question here.
Hi @tneotia,

I have two questions.
**Query1**  Whether any way to give input as HTML string and get output as processed formatted text in the editor. I have checked the example, we are calling the toggleCodeView method. But this toggles the text in the editor to HTML and vice versa. But, I need to manually pass the HTML text as input and need to get the formatted text as output in the editor.

**Query2** There are only 3 types of font family and a few for font size. Is it possible to use various different kinds of fonts and font sizes?

**Comment by tneotia** [comment]
Query1 - not sure what you mean, you can definitely provide an HTML string in the `initialText` parameter, this will be loaded into the editor when it starts up

Query2 - see #59
