### ISSUE TITLE
[QUESTION] DarkMode ToolbarButtton

### ISSUE THREAD

**Issue by weebsproject** [tneotia/html-editor-enhanced#244]
is there a way to fix this on darkmode ?

![image](https://user-images.githubusercontent.com/75978848/161538077-1c5034f6-8105-41eb-9a40-cc642a698d40.png)

![WhatsApp Image 2022-04-04 at 18 50 24](https://user-images.githubusercontent.com/75978848/161537991-f4931c96-d91c-4c5d-82c4-ea99f24ed7d0.jpeg)

![WhatsApp Image 2022-04-04 at 18 50 27](https://user-images.githubusercontent.com/75978848/161537995-c81dd9c4-45d0-4e52-8fe9-c7ff42f9f465.jpeg)

**Comment by tneotia** [comment]
Hi, this is dependent on your theming properties. If I remember correctly, the package uses your `iconTheme` `iconColor`, so check in your dark mode theme if these values are set correctly.
