### ISSUE TITLE
v2.0.0 Community Feature Requests

### ISSUE THREAD

**Issue by tneotia** [tneotia/html-editor-enhanced#25]
Hey you! Yes, you! If you'd like to see a particular feature please feel free to leave a comment and I'll look into adding it into the v2.0.0 release!

Before requesting, please see the [v2.0.0 wiki](https://github.com/tneotia/html-editor-enhanced/wiki/Roadmap) for the current roadmap.

Roadmap updates will be available in the [README](https://github.com/tneotia/html-editor-enhanced#roadmap).

**Comment by Chanondler** [comment]
Hey, thanks for a great library. 
I would like if we can apply any themes from [https://github.com/DiemenDesign/summernote-themes](url)
I went through all the documentation, but didn't find any solution. I might have missed something. Please let me know if there is a way or this feature would be really cool.

Another feature if we would add custom styling to toolbar options.
Thanks in advance!

**Comment by tneotia** [comment]
> I would like if we can apply any themes from https://github.com/DiemenDesign/summernote-themes

Hi @Chanondler , thanks for your suggestions. The above should be possible in the current state by using the `filePath` parameter to provide a custom HTML file from your assets. A sample HTML file could look like this:

<details><summary>Sample HTML</summary>

```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="description" content="Flutter Summernote HTML Editor">
    <meta name="author" content="xrb21">
    <title>Summernote Text Editor HTML</title>
    <script src="packages/html_editor_enhanced/assets/jquery.min.js"></script>
    <!--summernote js and css-->
    <link href="packages/html_editor_enhanced/assets/summernote-lite.min.css" rel="stylesheet">
    <script src="packages/html_editor_enhanced/assets/summernote-lite.min.js"></script>

    <!--this is where you're going to put your CSS file-->
    <link href="path_to_your_css" rel="stylesheet">

    <!--darkCSS-->
</head>
<body>
<div id="summernote-2"></div>
<!--headString-->
<!--summernoteScripts-->
<!--minor styling to improve editor design-->
<style>
  body {
      display: block;
      margin: 0px;
  }
  .note-editor.note-airframe, .note-editor.note-frame {
      border: 0px solid #a9a9a9;
  }
  .note-frame {
      border-radius: 0px;
  }
</style>
</body>
</html>
```

</details>

If you're using any plugins you'll have to include their JS/CSS as well (see the `summernote.html` file in lib/assets)

Please note: I'm not 100% sure on how the `href`s and `src`s need to be formatted. I'm pretty sure the paths I provided are correct, and if you use the plugin on Web I'm pretty sure you need to add another 'assets/' at the beginning of those strings.

If the HTML editor refuses to load/show anything its very likely just that your paths are messed up somehow.

> Another feature if we would add custom styling to toolbar options.

I agree with this, I hope to overhaul the `HtmlEditorOptions` and split it into a couple of different sections, maybe `ToolbarOptions`, `EditorOptions`, and some sort of `MiscOptions` for now at least. With the new widget controls it should be much simpler to provide extremely granular styling options.

I'll add this to the Roadmap!

**Comment by tneotia** [comment]
Hi @Chanondler , quick update - I've added all the styling options possible into the `HtmlToolbarOptions` class - there's over 25 available. If you want, you can use the git dependency for the v2.0.0 migration and try them out! No web support yet, though. I'll be adding that within the coming days, but at the moment mobile should work fine.

**Comment by tneotia** [comment]
v2.0.0 has been released! Feature requests are still welcome, please file a new issue though :)
