### ISSUE TITLE
[QUESTION] how to disable select all, copy paste etc

### ISSUE THREAD

**Issue by alfaruqrizqi18** [tneotia/html-editor-enhanced#253]
Hi, want to ask how to disable select all, copy paste etc like in this article https://www.fluttercampus.com/guide/88/how-to-disable-copy-paste-cut-select-all-on-textfeield-widget-flutter/

**Comment by tneotia** [comment]
You can use `mobileContextMenu` option on `HtmlEditorOptions`. See the docs for `ContextMenu` class here: https://inappwebview.dev/docs/context-menu/basic-usage/
