### ISSUE TITLE
[BUG] No implementation found for method evaluateJavascript on channel

### ISSUE THREAD

**Issue by justintoth** [tneotia/html-editor-enhanced#254]
**Describe the bug**
When the HtmlEditor widget is within a ListView widget, when it scrolls into or out of view sometimes it throws this exception:

```
flutter:   DEBUG MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_2) | stack: #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:175
flutter:   DEBUG <asynchronous suspension>
flutter:   DEBUG #1      InAppWebViewController.evaluateJavascript
package:flutter_inappwebview/…/in_app_webview/in_app_webview_controller.dart:1420
flutter:   DEBUG <asynchronous suspension>
flutter:   DEBUG #2      _HtmlEditorWidgetMobileState.build.<anonymous closure>
package:html_editor_enhanced/…/widgets/html_editor_widget_mobile.dart:450
```

**To Reproduce**
Create a view with a ListView, then place the HtmlEditor widget within it, but further down where it's out of view. Try swiping up and down in the list, and notice that sometimes it throws the above exception.

**Expected behavior**
It shouldn't throw an exception.

**Screenshots**

<img width="445" alt="Screen Shot 2022-05-13 at 11 10 52 AM" src="https://user-images.githubusercontent.com/1443831/168313559-41cb154b-cefb-4a97-8234-9c9d0862946f.png">

**Device:**
iOS Simulator 15.4

**Comment by tneotia** [comment]
You'll need to prevent the listview from disposing widgets (using keepalives). This may help: https://stackoverflow.com/questions/52541172/flutter-listview-keepalive-after-some-scroll
