### ISSUE TITLE
[BUG] Unable to pass App Store review because of unsupported fonts

### ISSUE THREAD

**Issue by BurningAXE** [tneotia/html-editor-enhanced#255]
I use html_editor_enhanced v2.4.0 in my Flutter app that is deployed to Android and iOS. When I tried to pass App Store review for a beta build in TestFlight it got rejected with the following message:

> Dear Developer,
> 
> We identified one or more issues with a recent submission for TestFlight review for your app, "___" 7.0.0 (473). Please correct the following issues, then upload again.
> 
> ITMS-90853: Invalid font - There was an error validating the font at '___.app/Frameworks/App.framework/flutter_assets/packages/html_editor_enhanced/assets/font/summernote.woff'. Font not supported by platform.
> 
> ITMS-90853: Invalid font - There was an error validating the font at '___.app/Frameworks/App.framework/flutter_assets/packages/html_editor_enhanced/assets/font/summernote.woff2'. Font not supported by platform.
> 
> Best regards,
> 
> The App Store Team

When I researched it looks like this is a new check on the App Store. html_editor_enhanced does indeed have these two fonts in its assets folder. However, simply deleting them fails the build. 

Has anyone come across this issue? Any suggestions on solving it?

**Comment by tneotia** [comment]
I'll look into this.... I was able to submit a build to testflight around a month ago with this package. Maybe they changed something.
