### ISSUE TITLE
[BUG] When compiling the web application with web canvaskit, the editor part is not visible

### ISSUE THREAD

**Issue by tarja77** [tneotia/html-editor-enhanced#256]
When compiling the web application with web canvaskit, the editor part is not visible. If I compile with html, I cannot use other features I use, for example, photo keying.
![Ekran Resmi 2022-05-16 17 56 03](https://user-images.githubusercontent.com/7052223/168622506-831dbe55-66e7-4506-8594-ad7def9450ff.png)

**Comment by tneotia** [comment]
This is a limitation of platform views, they aren't well supported on web. We need to wait for Flutter to improve platform view situation.
