### ISSUE TITLE
[QUESTION] Apply a font size and a font family to the all content

### ISSUE THREAD

**Issue by Cteq3132** [tneotia/html-editor-enhanced#257]
Hello there, I use this lib to be able to write some content with styles such as bold, italic or color, but I don't want the user to be able to apply a different font size or font family than the values originally defined. The widget looks like the following :

<img width="703" alt="image" src="https://user-images.githubusercontent.com/87450402/168657614-921ea3f2-7b0c-482e-81e9-3be25d9a16df.png">

My problem is when the user is pasting some text from a text editor, I don't want the text to keep the style other than the color, the boldness or italicness. Without doing anything, the user is quite free in what he can paste : 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/87450402/168658156-f04df543-6c7a-4b17-92a7-551b6869ee1d.png">

The result I want when the user paste something is the following : 

<img width="710" alt="image" src="https://user-images.githubusercontent.com/87450402/168658334-42199f69-68f6-4bb5-9525-6ca6520e0d96.png">

Do you see any way of doing that ?

**Comment by tneotia** [comment]
You might be able to listen to the `onPaste` callback and then clean up the HTML pasted yourself (using the `html` package on pub). However as far as I know there is no way for the editor to ignore _certain parts_ of rich pasted text. It either uses the entire "richness" or pastes as plain text.

**Comment by Cteq3132** [comment]
I manage to do this using the `onPaste` callback this way : 

```dart
onPaste: () => controller.evaluateJavascriptWeb('setStyle')
```
I set the `setStyle` function in the `webInitialScripts` property of the `htmlEditorOptions` : 

```dart
HtmlEditor(
  webInitialScripts: UnmodifiableListView([
    WebScript(
      name: 'setStyle',
      script:
          // apply a font size of 16px and arial font family
          // to the all document when pasting
          '''
        document.querySelectorAll("*")
          .forEach((element) => element.style.fontFamily = "Arial"); 
        document.querySelectorAll("*")
          .forEach((element) => element.style.fontSize = "16px");''',
    )
  ])
)
```

There might be a cleaner way to do that, but this works great for my use case.

**Comment by priyankaarbr** [comment]
Is there a way to change the color too? 
on other hand, I've tried to change the font family to 'Montserrat' (the fonts are placed in the assets), doesn't work.
