### ISSUE TITLE
bugs after upgrade to flutter 3.0 [BUG]

### ISSUE THREAD

**Issue by MohammedErbia** [tneotia/html-editor-enhanced#261]
what I reserved 
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window-0.1.1+1/lib/src/widgets/mouse_state_builder.dart:60:30: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
              WidgetsBinding.instance!.addPostFrameCallback((_) {
                             ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.4.0+1/lib/utils/utils.dart:873:41: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
    final focusManager = WidgetsBinding.instance!.focusManager;
                                        ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.4.0+1/lib/utils/utils.dart:880:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../../../Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.4.0+1/lib/utils/utils.dart:882:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../../Desktop/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.focusManager
                   ^
This app is linked to the debug service: ws://127.0.0.1:63996/IrdcwA_4vBo=/ws
Debug service listening on ws://127.0.0.1:63996/IrdcwA_4vBo=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:63996/IrdcwA_4vBo=/ws
Flutter Web Bootstrap: Auto

 
<img width="1584" alt="Screen Shot 2022-05-19 at 5 05 15 PM" src="https://user-images.githubusercontent.com/38259096/169313038-e596a55e-a573-419c-970c-81e9a66a2b74.png">
 
Version (more information here):

Flutter Version:
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (9 days ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2

OS: Flutter web

html_editor_enhanced: ^2.4.0+1

**Comment by lucasdidur** [comment]
@tneotia Any update?

**Comment by tneotia** [comment]
They are just warnings and can be ignored, haven't had much time to come back to this package in a while, and I likely won't until August/September. PRs are definitely welcome, it is just a matter of removing the `!` operator next to the `WidgetsBinding` calls in the app.

**Comment by lucasdidur** [comment]
@tneotia , they already merged, I think it's just publish a new version

https://github.com/tneotia/html-editor-enhanced/pull/258

**Comment by justintoth** [comment]
@tneotia Are you able to publish a new version, so we can squash these warnings?

**Comment by tneotia** [comment]
v2.5.0 is released, really sorry for the delay guys. Thanks for waiting on this!
