### ISSUE TITLE
How to insert the preview for audio, image or other type of file in the editor.

### ISSUE THREAD

**Issue by Dharanipalani** [tneotia/html-editor-enhanced#267]
I need to insert the preview of the type of file which I upload in the custom place. Is it possible to do with this package?

Example:

The assignment is uploaded [audio file preview icon]. other stuff... next work is [video file preview icon]...

Like the above example, Can I insert the preview for different files in between the text of the editor?. 

The response  ASAP from you really help me to do with my current project. Thanks in advace.

Thanks,
Dharanitharan. P

**Comment by tneotia** [comment]
You would have to somehow insert HTML for the preview of these files. It is not supported by default in the editor.
