### ISSUE TITLE
[QUESTION] Is it possible to show read only mode in editor & enable it later

### ISSUE THREAD

**Issue by shihabmi7** [tneotia/html-editor-enhanced#269]
I am using this editor in a project. I need a read-only mode for a first-time user coming to this editor. Later i give an option to start editing by pressing the edit button. Is this feature available?

**Comment by AdelKanso** [comment]
up

**Comment by shihabmi7** [comment]
i got solutions. 
we can disable htmlEditorController in Callbacks onInit(). 
`htmlEditorController.disable(); `
later you can enable it 
` controller.htmlEditorController.enable();
`
