### ISSUE TITLE
[BUG] xarrow keys on physical keyboard not working on iOS

### ISSUE THREAD

**Issue by ideva-SAS** [tneotia/html-editor-enhanced#272]
Hi,
thank you for this great work ! 
but I still encounter a bug: 
Enter text and use the arrow keys. focus moves to previous TextFormField

can you help me ?

Thx,
Best regards

**Comment by tneotia** [comment]
This is most likely a bug with Flutter. The arrow keys should function as normal in the webview

**Comment by ideva-SAS** [comment]
ok but they don't work on ipad with a bluetooth keyboard

**Comment by marekhalmo** [comment]
I think that the Toolbar should be encapsuled in ExcludeFocus node. That is not a flutter bug.

I see no reason why it should be possible to tab to the toolbar. 
There are keyboard shortcuts that work (Ctri + U for underlined e.t.c.) and that should be enough. For example it is not possible to tab to the toolbar here on this page so i think that this is a good idea.

What do you think?

Testing this on my fork. Seems to work on in emulator but i need to test it on a real physical keyboard and device ..
https://github.com/marekhalmo/html-editor-enhanced

**Comment by marekhalmo** [comment]
@tneotia could you reopen this?
