### ISSUE TITLE
[FEATURE] Maximum size for images or image processing option

### ISSUE THREAD

**Issue by julienduchow** [tneotia/html-editor-enhanced#278]
**Is your feature request related to a problem? Please describe.**
Define a maximum size for images, to avoid having really big images due to large upload times.

**Describe the solution you'd like**
I would like to either have a direct option to set a maximum image size (If an image with a bigger size it uploaded it should be compressed to the specified maximum size) or handle image insertions manually. With the `mediaUploadInterceptor ` I can accept or decline images, but I can not process them and compress them manually.

**Comment by tneotia** [comment]
You can create a custom image upload button to control the entire uploading process, this should allow to do what you want.
