### ISSUE TITLE
[QUESTION] Boring text upload message in the top left corner of the page

### ISSUE THREAD

**Issue by andeersonluiz** [tneotia/html-editor-enhanced#28]
Hello, i'm using the html-editor and ever when do upload image in text edditing an text is showed in the top left side from page saying "Find file - NameFile ". How i remove it? The image bellow show the message in my page.

![Sem título](https://user-images.githubusercontent.com/42013276/115990227-72871700-a598-11eb-93b7-28d286bad76b.png)

My CustomHtmlEditor:

    return Theme(
      data: ThemeData(
          primaryColor: Colors.red,
          selectedRowColor: Colors.red,
          textTheme: Theme.of(context).textTheme.apply(
                bodyColor: Theme.of(context).primaryColor,
                displayColor: Theme.of(context).primaryColor,
                decorationColor: Theme.of(context).primaryColor,
              )),
      child: HtmlEditor(
        controller: controller,
        htmlEditorOptions: HtmlEditorOptions(
          hint: "Escreva o texto aqui...",
          initialText: initialText,
        ),
        otherOptions: OtherOptions(
            height: 400,
            ),
        callbacks: Callbacks(
          onChange: onChange,
        ),
        htmlToolbarOptions: HtmlToolbarOptions(
            buttonFocusColor: Theme.of(context).primaryColor,
            buttonColor: Theme.of(context).primaryColor,
            buttonBorderColor: Colors.black,
            buttonFillColor: Theme.of(context).backgroundColor,
            buttonSelectedColor: Theme.of(context).primaryColor,
            dropdownFocusColor: Theme.of(context).primaryColor,
            textStyle: Theme.of(context)
                .textTheme
                .caption!
                .copyWith(color: Theme.of(context).primaryColor),
            toolbarType: ToolbarType.nativeGrid,
            defaultToolbarButtons: [
              StyleButtons(),
              FontSettingButtons(fontSizeUnit: false),
              FontButtons(
                  clearAll: false, superscript: false, subscript: false),
              ParagraphButtons(
                  increaseIndent: false,
                  decreaseIndent: false,
                  textDirection: false,
                  lineHeight: false,
                  caseConverter: false),
              InsertButtons(
                otherFile: false,
              ),
            ]),
      ),
    );

**Comment by tneotia** [comment]
Hi, which web renderer are you using when building the page? I suggest to use the html web renderer.

See here: https://github.com/tneotia/html-editor-enhanced#important-note-for-web

If you are using the html renderer then let me know and I'll look into this. Thanks!

**Comment by andeersonluiz** [comment]
Yes, i'm using html render. I run the flutter with the following command:
`flutter run --web-renderer html` or `flutter build --web-renderer html`

**Comment by tneotia** [comment]
Hmm I tested with the example app and your widget code, but I cannot reproduce:

![image](https://user-images.githubusercontent.com/50850142/116020462-4e691b80-a614-11eb-8100-0da6823d7381.png)

As you can see I inserted an image there but I don't see any "pick file" button in the top left.

Would you be able to share the code of your entire page? This way I can exactly test your use case and see what the issue is. Thanks for the reply!

**Comment by andeersonluiz** [comment]
Remove the AppBar, in my version mobile the error not occured because the appBar overlap the message the "picked file".

Version mobile without appBar :

![versionMobile](https://user-images.githubusercontent.com/42013276/116022381-78283f80-a620-11eb-8e9f-0f1a35413abb.png)

Case the error not show for you, i will send the project.

**Comment by tneotia** [comment]
Thanks for this detail. I will check in the morning on this issue, if you want to send the project that will be fine also.

**Comment by andeersonluiz** [comment]
Okay, thanks for support!!

**Comment by tneotia** [comment]
I tried again without app bar but I cannot reproduce still. I think the project will be helpful in this matter if possible.

![image](https://user-images.githubusercontent.com/50850142/116098829-5effad00-a679-11eb-89cb-e68fc85f3d4f.png)

**Comment by andeersonluiz** [comment]
Hello! Sorry for  answering for late, i do some changes in the exemple project, i removed the appBar and added my custom theme, the bug probably resides in some settings of theme.
![bug](https://user-images.githubusercontent.com/42013276/116635259-abc2dc80-a934-11eb-8476-0d4d76c18136.png)

The files of project above:
[example.zip](https://github.com/tneotia/html-editor-enhanced/files/6402424/example.zip)

**Comment by tneotia** [comment]
Yep, the issue is the theme. You have the line `scaffoldBackgroundColor: brownLight,`. The `brownLight` color causes the issue.

If you remove the opacity from `brownLight` you cannot see the choose file button anymore. Because your background is slightly transparent, you see the choose file button there. So for example `static Color brownLight = Color.fromRGBO(191, 169, 138, 1);` fixes your issue.

**Comment by andeersonluiz** [comment]
Nice! Problem resolved. Thanks for support!!
