### ISSUE TITLE
How to do Text editor convert to Text Widget? 

### ISSUE THREAD

**Issue by DazzlingCVa** [tneotia/html-editor-enhanced#280]
Type question here.

**Comment by Ashish-Raturi** [comment]
You can use enable and disable.

HtmlEditorController controller = HtmlEditorController();

//Text widget 
widget.curController.disable();

//Text editor
widget.curController.enable();

**Comment by DazzlingCVa** [comment]
A TextField Widget that allow you to convert easily what's in the TextField to with custom texteditor toolbar

**Comment by DazzlingCVa** [comment]
A TextField Widget that allow you to convert easily what's in the TextField to with custom texteditor toolbar @Ashish-Raturi

**Comment by Ashish-Raturi** [comment]
@DazzlingCVa 
I got it, you want a text field and the user can change font style, bold italic, and other stuff. right?
You need a custom HTML editor then.
