### ISSUE TITLE
[QUESTION] How to init font size in editor

### ISSUE THREAD

**Issue by ironfactory8684** [tneotia/html-editor-enhanced#284]
Hi, Thank you guys for your awesome package
I want to init fontSize 12 to 14 in the editor. 
Can you tell me how I can do it?

**Comment by ironfactory8684** [comment]
thanks your answer 
i tried evaluateJavascript function 
my controller doesn't have evaluateJavascript 
but has evaluateJavascriptWeb instead.
can you guide evaluateJavascriptWeb usage me

**Comment by tneotia** [comment]
Please see the readme for usage guide on web eval JS. You use the same summernote JS code.
