### ISSUE TITLE
Unable to change the Keyboard type 

### ISSUE THREAD

**Issue by marslannasr7koncepts** [tneotia/html-editor-enhanced#285]
Unable to change the Keyboard type

**Comment by marslannasr7koncepts** [comment]
> Did you try the keyboard type API in the editor? What is your editor code?

`                    HtmlEditor(
                      controller: controller,
                      htmlEditorOptions: HtmlEditorOptions(
                        hint: 'Your text here...',
                        shouldEnsureVisible: false,
                        //shouldEnsureVisible: true,
                        //initialText: "<p>text content initial, if any</p>",
                      ),
                      htmlToolbarOptions: HtmlToolbarOptions(
                        toolbarPosition: ToolbarPosition.aboveEditor,
                        //by default
                        toolbarType: ToolbarType.nativeScrollable,
                        onButtonPressed: (ButtonType type, bool? status,
                            Function()? updateStatus) {
                          // print(
                          //     "button '${describeEnum(type)}' pressed, the current selected status is $status");
                          return true;
                        },
                        onDropdownChanged: (DropdownType type, dynamic changed,
                            Function(dynamic)? updateSelectedItem) {
                          // print(
                          //     "dropdown '${describeEnum(type)}' changed to $changed");
                          return true;
                        },
                        mediaLinkInsertInterceptor:
                            (String url, InsertFileType type) {
                          print(url);
                          return true;
                        },
                        // mediaUploadInterceptor:
                        //     (PlatformFile file, InsertFileType type) async {
                        //   print(file.name); //filename
                        //   print(file.size); //size in bytes
                        //   print(file.extension); //file extension (eg jpeg or mp4)
                        //   return true;
                        // },
                      ),
                      otherOptions: OtherOptions(height: 400),
                      callbacks: Callbacks(
                        onBeforeCommand: (String? currentHtml) {
                          print('html before change is $currentHtml');
                        },
                        onChangeContent: (String? changed) {
                          print('content changed to $changed');
                        },
                        onChangeCodeview: (String? changed) {
                          print('code changed to $changed');
                        },
                        onChangeSelection: (EditorSettings settings) {
                          print('parent element is ${settings.parentElement}');
                          print('font name is ${settings.fontName}');
                        },
                        onDialogShown: () {
                          print('dialog shown');
                        },
                        onEnter: () {
                          print('enter/return pressed');
                        },
                        onFocus: () {
                          print('editor focused');
                        },
                        onBlur: () {
                          print('editor unfocused');
                        },
                        onBlurCodeview: () {
                          print('codeview either focused or unfocused');
                        },
                        onInit: () {
                          print('init');
                        },
                      ),
                      // plugins: [
                      //   SummernoteAtMention(
                      //       getSuggestionsMobile: (String value) {
                      //         var mentions = <String>['test1', 'test2', 'test3'];
                      //         return mentions
                      //             .where((element) => element.contains(value))
                      //             .toList();
                      //       },
                      //       mentionsWeb: ['test1', 'test2', 'test3'],
                      //       onSelect: (String value) {
                      //         print(value);
                      //       }),
                      // ],
                    ),`

**Comment by tneotia** [comment]
I don't see the keyboard type being used. Please try that option and see if it works.
