### ISSUE TITLE
[BUG] No text on the insert image from file button

### ISSUE THREAD

**Issue by L15V** [tneotia/html-editor-enhanced#29]
**Describe the bug**
When i click the image icon in the toolbar. There is a button available without text.

**To Reproduce**
1. Click on the image icon on the toolbar

**Expected behavior**
Show a text like "upload" inside the button.

**Screenshots**
![image](https://user-images.githubusercontent.com/25549902/116563286-2fb0a080-a904-11eb-91a7-d8947a098427.png)

**Device:**
Windows 10 Google Chrome

**Comment by tneotia** [comment]
The upload button is "select from files", when you press that the file dialog should open.

**Comment by L15V** [comment]
@tneotia 
In that case, the text is above the button.

See the image below:
![buttun_bug](https://user-images.githubusercontent.com/25549902/116579281-8624db80-a912-11eb-9071-d782335ebda3.jpeg)

**Comment by tneotia** [comment]
Ah I see. I noticed this earlier and I think I fixed it with https://github.com/tneotia/html-editor-enhanced/commit/f77a2ece3b6c83a66fd78d4276d879e5514e7687#diff-f3291b40e9806a0a7676e69281c30fa62fbcb09924a698eb070996e678ca15f1R1412

Could you provide me with your theme code and your widget code? I would need your `Theme.of(context).textTheme.bodyText1?.color`.

**Comment by L15V** [comment]
It was indeed a problem with my theme. It's fixed now. Thanks for your help.

![image](https://user-images.githubusercontent.com/25549902/116590269-d5243e00-a91d-11eb-8076-33275fb49d66.png)
