### ISSUE TITLE
Css Styles are not applied to the html editor

### ISSUE THREAD

**Issue by Dharanipalani** [tneotia/html-editor-enhanced#294]
I have used the **initialText** parameter to load my HTML string to get the formatted text. But, the style I applied to the html is not applied in the editor.

```html
<html><head><style> .paragraph{color: #008000;} </style></head><body><p>Dharani</p>
</body></html>
```

I also tried using the separate style.css file and mapping it to the HTML and that too does not works.

Is any way to achieve this.

Thanks in advance.

**Comment by alfaruqrizqi18** [comment]
> ```
> <style> .paragraph{color: #008000;} </style>
> ```

try to change from ` .paragraph{color: #008000;}` to ` p {color: #008000;}`
