### ISSUE TITLE
Please update file picker and flutter svg[BUG]

### ISSUE THREAD

**Issue by sameer320** [tneotia/html-editor-enhanced#295]
It is still depend on 
file_picker: ^4.6.1
flutter_svg: ^0.23.0+1
Please update these dependenticies

**Comment by kostas95** [comment]
Can you please update the `file_picker` library to the latest version?

My app depends also on the `file_picker` library and because of that I can't update to the latest version (5.0.0 at this moment)

**Comment by sameer320** [comment]
@tneotia please check this version issue

**Comment by ksilz** [comment]
@sameer320 @kostas95 I forked this editor and updated three dependencies to their latest version. Please use my fork and see if that works for you. Put this into your `pubspec.yaml`:

```
  html_editor_enhanced:
    git:
      url: https://github.com/ksilz/html-editor-enhanced
```

**Comment by kostas95** [comment]
@ksilz Thank you

**Comment by tneotia** [comment]
Done
