### ISSUE TITLE
How to upload images by default to 50%

### ISSUE THREAD

**Issue by jianguo888** [tneotia/html-editor-enhanced#296]
Type question here.
<img width="449" alt="image" src="https://user-images.githubusercontent.com/66907438/181663082-d33bdad6-d8a6-4b26-a044-fb0b22a61f47.png">

**Comment by tneotia** [comment]
You can capture the image upload with mediaUploadInterceptor and scale it down before inserting into editor.

**Comment by Bidhanrai** [comment]
How to scale down the image
