### ISSUE TITLE
[QUESTION] Problems with drawer over text editor

### ISSUE THREAD

**Issue by andeersonluiz** [tneotia/html-editor-enhanced#30]
Hello, i'm with an bug when open drawer and the buttons is above of the text editor. Not get click on button because the cursor stay like were editting (focused) text and when clicked is possible write text with drawer open. Is there a way to solve problem?

Inside the red box is not possible click on drawer buttons.

![bug2](https://user-images.githubusercontent.com/42013276/116658163-f14bcd80-a965-11eb-846e-81b3dced9f47.png)

link of the example project that reproduces the problem: https://drive.google.com/file/d/1LRvKS8xs2-rtDHOjP99IWth7EPIx5FFq/view?usp=sharing

**Comment by tneotia** [comment]
Ah yes I should have added a note about this in the README. You have to use the pointer interceptor package: https://pub.dev/packages/pointer_interceptor

Wrap your drawer tiles with that widget and it will work again. This is an issue with Flutter at the moment.

**Comment by andeersonluiz** [comment]
Good!! Resolved
