### ISSUE TITLE
[FEATURE] Upgrade file_picker to version 5.x.x

### ISSUE THREAD

**Issue by Eric-Liqiafeng** [tneotia/html-editor-enhanced#304]
Hello, now most of the plugins that depend on ffi have been upgraded to ffi v2.0, and the version used by html-editor-enhanced -> file_picker(v4.6.0) -> ffi(v1.1.2) is too low to be compatible with other plugins are compatible, causing conflicts.

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/27261737/183842988-0ee78214-2d8d-43e4-993f-ef589f051534.png">

Please help to upgrade the file_picker to version 5.x.x.

Thanks.

**Comment by kimmanwky** [comment]
I have the same issue. Please emphasis on pushing this out.

**Comment by tneotia** [comment]
Done
