### ISSUE TITLE
[BUG] Show black screen when open editor on drawer.

### ISSUE THREAD

**Issue by lek-sennalabs** [tneotia/html-editor-enhanced#309]
**Describe the bug**
when i open editor on drawer it's show black screen.

example video:

https://vimeo.com/739525433

example code: 
`HtmlEditor(
    controller: _htmlController,
    otherOptions: const OtherOptions(height: 140),
    htmlEditorOptions: const HtmlEditorOptions(
     autoAdjustHeight: true,
     hint: null,
     shouldEnsureVisible: true),
    htmlToolbarOptions: const HtmlToolbarOptions(
     toolbarPosition:
     ToolbarPosition.custom, //by default
     toolbarType: ToolbarType.nativeScrollable //by default
    ),
    callbacks: Callbacks(onFocus: () { }, onChangeContent: (String? value) {  }))
    ]),`

**Comment by tneotia** [comment]
Flutter issue with webviews, unfortunately. Any weird rendering glitches are from Flutter.
