### ISSUE TITLE
[BUG] stylebutton options does not work

### ISSUE THREAD

**Issue by anamak9** [tneotia/html-editor-enhanced#31]
**Describe the bug**
1. the editor resets when trying to change options on any of the defaultToolbarButtons. 
2. If some text is selected and then trying apply styles on it (for e.g, 'Header-1') does not work.

**To Reproduce**
1. Open app in chrome
2. Click on stylebutton options
3. Scroll down to 'Header-1'
4. See error:
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
Flutter: restoring WebGL context.
done

**Expected behavior**
1. selected option should remain steady and be applied to the text in scope

**Device:**
Chome 

**Other context**
Version: 
html_editor_enhanced: ^2.0.1

**Comment by tneotia** [comment]
Hi there, when running your app are you using `--web-renderer=html`?

**Comment by tneotia** [comment]
Closing this for now... Please keep following https://github.com/flutter/flutter/issues/80524 for updates on a fix.
