### ISSUE TITLE
[ Flutter WEB ] Can't click toolbar options which are on top of html editor [BUG]

### ISSUE THREAD

**Issue by tstrg** [tneotia/html-editor-enhanced#313]
**Describe the bug**
The options that are overlaying the editor (e.g. insert link dialog or font size selector) are not clickable. 

**To Reproduce**
1. open web build
2. click on the insert link button (or on the font size toolbar button)
3. try to interact with options that are overlaying on the editor, those options are not clickable

**Expected behavior**
Elements overlaying the editor are clickable.

**Screenshots**
https://www.awesomescreenshot.com/video/10789811?key=c7a56136a64ef5a3e5ca1942f011722c

**Additional context**
Flutter Channel stable, 3.0.5
html_editor_enhanced 2.5.0
In my case, the html editor is inserted inside a bottom sheet.

**Comment by vsheffer** [comment]
I _may_ be seeing the same thing when I popup an **AlertDialog** box.  When I do that the OK button is not clickable.  Are these two related?

**Comment by tneotia** [comment]
Yes, it is all related. Please see other tickets opened for the exact same issue. It is a Flutter bug.
