### ISSUE TITLE
[QUESTION] Input type checkbok

### ISSUE THREAD

**Issue by beocaca** [tneotia/html-editor-enhanced#315]
Hello, i have problem with the Input tag type checkbox 
Is there any ways to make the input with reactive,  
get value by checked or none please ?!
<img width="822" alt="image" src="https://user-images.githubusercontent.com/51392704/187898846-d0c23a12-b234-4c44-b3ad-dc262555a46e.png">

**Comment by beocaca** [comment]
@tneotia

**Comment by tneotia** [comment]
This is currently not supported, sorry.

**Comment by A7MeDG0L0L** [comment]
@beocaca  found any solutions ?
