### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by evalsxonted** [tneotia/html-editor-enhanced#316]
**Describe the bug**
not working, I cannot write anything.
**To Reproduce**
```
` class Start extends ConsumerWidget {
  const Start({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      
      home: WidgetTester(),
    );
  }
}

class WidgetTester extends ConsumerStatefulWidget {
  const WidgetTester({
    Key? key,
  }) : super(key: key);

  @override
  ConsumerState createState() => _WidgetTesterState();
}

class _WidgetTesterState extends ConsumerState<WidgetTester> {
  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      body: Center(
          child: Container(
            padding: EdgeInsets.all(ref.read(sizesProvider).paddingM),
            margin: EdgeInsets.all(ref.read(sizesProvider).paddingM),
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(
                  ref.read(sizesProvider).inputRadius),
              border: Border.all(
                  color: ref.watch(colorsProvider).hint,
                  width: ref.read(sizesProvider).borderWidth),
            ),
            child: HtmlEditor(
              controller: HtmlEditorController(
                processInputHtml: true,
                processOutputHtml: true,
                processNewLineAsBr: true
              ), //required
              htmlEditorOptions: const HtmlEditorOptions(
                hint: "Your text here...",
                initialText: "text content initial, if any",
              ),
htmlToolbarOptions: HtmlToolbarOptions(toolbarPosition: ToolbarPosition.belowEditor),
            ),
          ),),
    );
  }
}`
```
**Expected behavior**
I expect that i can write something
**Screenshots**

**Device:**
Emulator ( nexus 4 api 30)
**Additional context**
I use riverpod package
**Error**
E/flutter ( 5255): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: com.pichillilorenzo/flutter_inappwebview
E/flutter ( 5255): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:189)
E/flutter ( 5255): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter ( 5255): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter ( 5255): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 5255): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 5255): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/flutter ( 5255): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter ( 5255): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 5255): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 5255): 	at android.os.Looper.loop(Looper.java:223)
E/flutter ( 5255): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 5255): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5255): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 5255): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 5255): , null, null)
E/flutter ( 5255): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 5255): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 5255): <asynchronous suspension>
E/flutter ( 5255): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1134:18)
E/flutter ( 5255): <asynchronous suspension>
E/flutter ( 5255): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:762:5)
E/flutter ( 5255): <asynchronous suspension>
E/flutter ( 5255): #4      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1062:7)
E/flutter ( 5255): <asynchronous suspension>
E/flutter ( 5255): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:179:29)
E/flutter ( 5255): <asynchronous suspension>
E/flutter ( 5255): 
E/PlatformViewsController( 5255): Sending touch to an unknown view with id: 0

**Comment by evalsxonted** [comment]
edit code

**Comment by tneotia** [comment]
Please check and make sure you followed the initialization code required for webviews to function.
