### ISSUE TITLE
[QUESTION]How can I remove the upload section from Insert buttons?

### ISSUE THREAD

**Issue by rakib205** [tneotia/html-editor-enhanced#317]
Hi there, I don't need this upload section from the picture. I need only the insert URL option. How can I remove only the upload section? 

![Screenshot 2022-09-04 at 3 12 09 PM](https://user-images.githubusercontent.com/34546369/188306351-3a9636c4-8bd5-4367-8bfc-da7796deceb1.png)

**Comment by tneotia** [comment]
You will need to override the whole media insert workflow and provide a custom dialog. Currently there are no parameters to remove this button.

**Comment by rakib205** [comment]
Got it. Thanks
