### ISSUE TITLE
[QUESTION] HtmlEditorController doesn't have evaluateJavascript

### ISSUE THREAD

**Issue by ironfactory8684** [tneotia/html-editor-enhanced#319]
Hi, Thank you guys for your awesome package
i want use evaluateJavascript function 
but htmlEditorController doesn't have evaluateJavascript
just has evaluateJavascriptWeb function 
how to change evaluateJavascriptWeb to evaluateJavascript?
Can you tell me how I can do it?

**Comment by tneotia** [comment]
evaluate javascript is inside the InAppWebViewController exposed in HtmlEditorController.
