### ISSUE TITLE
characterLimit Whether this field supports Android？

### ISSUE THREAD

**Issue by 1136346879** [tneotia/html-editor-enhanced#320]
Type question here.

![image](https://user-images.githubusercontent.com/15826462/191400391-7ce70b3e-fb3c-4e15-99b0-8d8dbb8ae664.png)

  /// Adds a character limit to the editor.
  ///
  /// NOTE: ONLY WORKS ON iOS AND WEB PLATFORMS!!
  final int? characterLimit;

**Character limit, can Android set?**？？？

**Comment by tneotia** [comment]
No, android is currently not supported.
