### ISSUE TITLE
Can you guide me on how to implement html editor widget in view page?

### ISSUE THREAD

**Issue by Govindbetterlives** [tneotia/html-editor-enhanced#323]
Type question here.
Hi, please guide me on how to implement this widget. I tried but showing an empty page like this. 
I am html_editor_enhanced: ^1.6.0 this version.

![image](https://user-images.githubusercontent.com/81243940/192755162-02f514c9-fffc-4632-b142-acf6dd978632.png)

**Comment by nadialvy** [comment]
facing the same issue the hint text is not shown and i cant type a word
![image](https://user-images.githubusercontent.com/80080969/193758123-a6ea38e5-7561-4d1f-baec-d6f960e702c1.png)

**Comment by tneotia** [comment]
Please make sure you initialized the webview correctly (internet permission in manifest).
