### ISSUE TITLE
[BUG]Fail to compile

### ISSUE THREAD

**Issue by flex1005** [tneotia/html-editor-enhanced#331]
**Describe the bug**
When I compiled, I got this message(screenshot 1), the code that I used was https://pub.dev/packages/html_editor_enhanced/example
I added (screenshot 2) assets:       - packages/html_editor_enhanced/summernote.html to the pubspec.yaml, but I still got the same message.

**To Reproduce**
1. create a new flutter project
2. run flutter pub add html_editor_enhanced
3. copy the code in https://pub.dev/packages/html_editor_enhanced/example to main.dart
4. compile

**Expected behavior**
Compile successfully

**Screenshots**
![bug1](https://user-images.githubusercontent.com/115200715/194459177-5f475c9f-5588-4310-a5bb-72c456bbc189.PNG)
![bug2](https://user-images.githubusercontent.com/115200715/194459234-b905eb0a-66b8-472f-adc5-4a9f729212f5.PNG)
**Device:**
Running a web application.

**Comment by LefebvreIlyas** [comment]
Hello @flex1005 , you don't need to do anyting, it's a mistake in the package itself, you can use my fork if you want, I fix the bug in this commit: https://github.com/LefebvreIlyas/html-editor-enhanced/commit/b7d6faff50d1a88a1ce48372e50b5220fff08dd0

**Comment by flex1005** [comment]
> 



> Hello @flex1005 ,
> 
> You don't need to do anyting, it's a mistake in the package itself, you can use my fork if you want, I fix the bug in this commit: [LefebvreIlyas@b7d6faf](https://github.com/LefebvreIlyas/html-editor-enhanced/commit/b7d6faff50d1a88a1ce48372e50b5220fff08dd0)
> 
> ```yaml
>   html_editor_enhanced:
>     git: https://github.com/LefebvreIlyas/html-editor-enhanced
> ```

is this the old version? it showed "The named parameter 'htmlToolbarOptions' isn't defined."

**Comment by 25LucasAnselmo** [comment]
I updated flutter and had same problem. Seems older versions dealt with pubspeck.yaml package issue
Thanks @LefebvreIlyas, i made my fork too, for now is the solution
https://github.com/25LucasAnselmo/html-editor-enhanced

**Comment by tneotia** [comment]
Please open a PR so it can be fixed in the official version, thanks :)

**Comment by ndelanou** [comment]
I also have this issue when I upgrade Flutter from the beta channel.
3.4.0-17.2.pre: ✅
3.4.0-34.1.pre: ❌ => `No file or variants found for asset: packages/html_editor_enhanced/summernote.html.`
