### ISSUE TITLE
[QUESTION] Is there any means of checking whether or not the editor has loaded yet?

### ISSUE THREAD

**Issue by Archais** [tneotia/html-editor-enhanced#337]
Hi. I've recently started using the editor and it seems to work great however, I have an issue with setting premade HTML into it- when I call the `setText()` method on the controller it returns:

```[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: HTML editor is still loading, please wait before evaluating this JS: $('#summernote-2').summernote('code', [HTML_TEXT])```

The only way that I can currently find to avoid this error is by using `Future.delayed()`, which of course adds waiting period for the user. So, per the title, is there any way of detecting when the editor has been loaded? (My platform is Android and IOS btw)

**Comment by ptran-dev** [comment]
I am getting the same error intermittently when using the iOS simulator, but seems to be persistent on an actual device running iOS 15.5 - attempting to call getText, but this seems to occur for anything that uses _evaluateJavascript in html_editor_controller_mobile.dart

I have noticed that flutter_inappwebview fixed an issue in a recent version where on iOS the completion handler isn't called, could this be the issue? https://github.com/pichillilorenzo/flutter_inappwebview/issues/1221

**Comment by Archais** [comment]
I don't think that the issue has anything do with IOS specific programming as most of my testing has been on a physical device running Android 12. What I've resolved to do for the time being is to wrap the `setText()` call with a `Future.delayed()` with a duration of 2 seconds. This works however, it is quite janky as it isn't relying on knowing that the editor has loaded and is rather relying on an estimation (which could be completely wrong on a different device).

**Comment by TheCarpetMerchant** [comment]
I'm encountering the same problem. It is quite weird that the callback `onInit` is called _before_ initialization is actually done.
The documentation needs to be clearer and tell that we need to await `editorController.isLoading`.
It is also very weird that I call `setFullscreen` without problems, but then `setText` provokes the error.

Anyway, I implemented this horrendous-looking function to deal with the problem :
```dart
/// Crashlytics gave some errors that the editor hasn't finished loaded, so we wait for that here before doing stuff.
Future<void> awaitEditorLoading() async {
  while(await (htmlEditorController.editorController as InAppWebViewController?)?.isLoading() ?? false) {
    await Future<void>.delayed(const Duration(milliseconds: 100));
  }
}
```

**Comment by Archais** [comment]
My goodness. I will try your solution, thank you for sharing! I can see what you mean about the function looking odd, unfortunately I don't think there is any way to make it more succinct.

**Comment by Archais** [comment]
@TheCarpetMerchant I've had a look at your solution and it looks like it should work however, in my case the  `html_enhanced_editor` package defaults to the **unsupported** library despite the fact that the `dart:io` package is definitely available. Have you encountered this issue?

**Comment by TheCarpetMerchant** [comment]
@Archais no, haven't got that. My hack mentioned above does its work in production, but I now have this :
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: MissingPluginException(No implementation found for method evaluateJavascript on channel com.pichillilorenzo/flutter_inappwebview_2). Error thrown null.
       at MethodChannel._invokeMethod(platform_channel.dart:294)
       at InAppWebViewController.evaluateJavascript(in_app_webview_controller.dart:1420)
       at _HtmlEditorWidgetMobileState.build.<fn>(html_editor_widget_mobile.dart:449)
```
Yeah... Great...

**Comment by Archais** [comment]
@TheCarpetMerchant Oh, goodness. That's a painful one. The exception isn't even occurring within your own code. 😭

**Comment by Archais** [comment]
@TheCarpetMerchant I've found a solution to both the setting text issue and another related issue that I had (the editor contents disappearing when changing tabs) here it is 

[[BUG] Not working well with flutter tabs](https://github.com/tneotia/html-editor-enhanced/issues/213#issuecomment-1030801282)
```
HtmlEditor(
  controller: _myDescriptionController, //required
  htmlEditorOptions: HtmlEditorOptions(
    hint: "Property description",
    initialText: _myDescription,
  ),
  callbacks: Callbacks(
    onChangeContent: (String? changed) {
      setState(() => _myDescription = changed);
    },
  ),
)
```
In my case, the editor is the result of a `build()` method on a custom class that has the following property defined:
```
  final TextEditingController _textController = TextEditingController();
```
So I have my `value` getter fetch the value of `_textController.text` and set it as the `initialText` property. It's possible that switching to this solution instead of using `setText()` may resolve your new issue as well (I was previously getting that error infrequently). Hope this helps.
