### ISSUE TITLE
How to avoid reset after losing focus? [QUESTION]

### ISSUE THREAD

**Issue by casysso** [tneotia/html-editor-enhanced#35]
Hello, and thanks for the great widget.

I have three tabs on a flutter web widget (within a scaffold/tabcontroller). Every tab hosts an HtmlEditor with its onw controller. Whenever I switch between tabs, the context of the editor gets lost and the initial value is restored (the widget is redrawn). Can I save the content and set the initial value on losing focus or is it possible to simply keep the changes cached? I had a look at the callbacks already and the settext methods, but I could not find any solution that suited my needs.

Your help would be greatly appreciated.
Thanks, casysso

**Comment by tneotia** [comment]
Web has been very finnicky to use because of how the editor `iframe` rendering is handled by Flutter at the moment. Question - are you running your app with the `--web-renderer=html` flag?

**Comment by tneotia** [comment]
Closing this for now... Please keep following https://github.com/flutter/flutter/issues/80524 for updates on a fix.
