### ISSUE TITLE
incompatible with flutter version 3.7

### ISSUE THREAD

**Issue by Hiwa-Shaloudegi** [tneotia/html-editor-enhanced#379]
Hi,
I just upgraded the flutter SDK to **3.7** and when I run my project I get this error:
"No file or variants found for asset: packages/html_editor_enhanced/summernote.html."
It was working fine with my last version of flutter, so i guess this package is incompatible with flutter version 3.7 and needs to be updated.

**Comment by sun-jiao** [comment]
> Solved it! compatible versions are: file_picker: ^5.2.5 html_editor_enhanced: ^2.5.1

Hi, I'm facing the same problem. According to this issue (https://github.com/sarbagyastha/youtube_player_flutter/issues/138#issuecomment-1067792904), It's not related with the package version. Just clean the project cache, the problem will get resolved.
