### ISSUE TITLE
how to persist everything gotten from the Editor into sql and firebase [QUESTION]

### ISSUE THREAD

**Issue by mathiasgodwin** [tneotia/html-editor-enhanced#38]
Sorry guys, I'm new to this Flutter thing.

How do I record everything entered into the editor (image, video, sound, text) into SQLite and Firebase?
Storing media like videos is not an ideal idea in SQL, any workaround?

Thanks in advance.

**Comment by tneotia** [comment]
I don't have much experience with this, I imagine it is similar to any other upload method into SQL or Firebase. Probably need Firebase Storage or something like that. If you can figure out the uploading part then implementing with the editor is very easy.

**Comment by tneotia** [comment]
Take a look at #45 for an example using firestore, maybe it can help you out. Closing this for now.
