### ISSUE TITLE
[QUESTION] : How to remove this ?

### ISSUE THREAD

**Issue by taimoor522** [tneotia/html-editor-enhanced#390]
I want to remove this adjuster with a horizontal line. The horizontal line below the adjuster in intentionally added and don't want to remove this. Only the adjuster and the line above it.

![image](https://user-images.githubusercontent.com/76042739/220847538-a5824663-c3a6-45d1-8f24-6393fc69b41a.png)

**Comment by taimoor522** [comment]
@sunnyasr Same Result. Noting Changed.
![image](https://user-images.githubusercontent.com/76042739/221092361-7b00f1fe-b292-479c-817f-4d97cd273e80.png)

**Comment by sunnyasr** [comment]
@taimoor522 Try to do this with the below line of code.
callbacks: Callbacks(onInit: () {
                  controller.editorController.setFullScreen();
              
                })

**Comment by taimoor522** [comment]
@sunnyasr Thank you so much... It worked 👍👍👍
