### ISSUE TITLE
[QUESTION] Widget resets hover IconButton/InkWell

### ISSUE THREAD

**Issue by andeersonluiz** [tneotia/html-editor-enhanced#41]
I have a problem, when i hover over the IconButton or InkWell icon , the widget editor is restarted, but when using GestureDetector the problem does not occur. Is there a way to resolve this?

I'm run the project with --web-renderer=html.

Video showing the problem (Red is GestureDeteector and white is InkWell):

https://user-images.githubusercontent.com/42013276/118200928-aaada700-b42c-11eb-995c-63f5c8682613.mp4

**Comment by tneotia** [comment]
Hmm it seems related to the mouse cursor. With gesture detector it doesn't change to the hand, but with inkwell it does. I think again this is an issue you have to wait for that PR I mentioned earlier until we can determine whether it is an issue with Flutter or the editor itself. 

That PR is close to merge (it is approved) so hopefully within next few weeks it will be available to people.

**Comment by andeersonluiz** [comment]
Okay, i'll wait, thanks for the support!!
