### ISSUE TITLE
For Second Item in Bullet point uses lowercase  -- IOS

### ISSUE THREAD

**Issue by Aruljebaraj** [tneotia/html-editor-enhanced#421]
it works flawless for Android in IOS 
second item in bulletpoints begins with Lowercase
In Bulletpoint -->First Letter should be in Uppercase

**Comment by saurabhmore** [comment]
I tried using the Google keyboard it works fine and gives 1st letter capitalized but the ios default keyboard does not give the first letter of a word capitalized.
