### ISSUE TITLE
[FEATURE] Upgrade flutter_inappwebview dependency

### ISSUE THREAD

**Issue by danielmurcia** [tneotia/html-editor-enhanced#432]
**Is your feature request related to a problem? Please describe.**
I want to upgrade the version of `flutter_inappwebview` to the new [6.0.0 version] (https://pub.dev/packages/flutter_inappwebview/versions/6.0.0-beta.23) in my project, but I can't do it as I use the `html-editor-enhanced` repo and it uses only 5.X.X versions.

**Describe the solution you'd like**
Would it be possible to have a beta version of the package that depends on the newest `flutter_inappwebview` for people like me that want to make use of the newest features of it?

**Additional context**
I'm open to fork and contribute for it, but I'd like to know if it would be worth doing.

**Comment by Rishab-ms** [comment]
@danielmurcia heyy, did you find a solution to it?

**Comment by danielmurcia** [comment]
Nope, sadly 😞

**Comment by tneotia** [comment]
New version uploaded, sorry for the wait guys

**Comment by Rishab-ms** [comment]
Thank you ! 👍🏻 Grateful for your help!
