### ISSUE TITLE
Unhandled Exception: Exception: HTML editor is still loading, please wait before evaluating this JS [BUG]

### ISSUE THREAD

**Issue by imrajdev** [tneotia/html-editor-enhanced#434]
Hi, 
Getx Flutter project, I am using HtmlEditor in bottomsheet. When i'm going to home page to create screen this error shown on debug mode. How to fix this? Is there issue happen if ignore this issue?

**Screenshots**
![image](https://github.com/tneotia/html-editor-enhanced/assets/122859337/92329ea1-789e-416f-b21a-5be4008eae12)

**Device:**
Pixel 4 API 31

**Comment by aminJamali** [comment]
you needs to call htmlController.setText in GetxController onReady function not in onInit func

**Comment by LeToyek** [comment]
how is it, Can u send me ur code?
