### ISSUE TITLE
[QUESTION] Note-statusbar

### ISSUE THREAD

**Issue by dangmt-se** [tneotia/html-editor-enhanced#437]
Hello, can anyone tell me how to omit the note-statusbar below the html editor for webview?
I've been flipping over files to fine its location and try to modify it but still haven't achieved the goal.
Please let me know how to omit that bar if anyone of you has already successfully done it.
Thank you so much!!!
Please help out the flutter dummy me!!!

**Comment by MarkStepp** [comment]
looking for the same solution
