### ISSUE TITLE
Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing characters. See: https://flutter.dev/docs/cookbook/design/fonts[BUG]

### ISSUE THREAD

**Issue by a4ekw** [tneotia/html-editor-enhanced#44]
Could not find a set of Noto fonts to display all missing characters. Please add a font asset for the missing characters. See: https://flutter.dev/docs/cookbook/design/fonts

**To Reproduce**
1. Go to https://pub.dev/packages/html_editor_enhanced
2. Get example code
3. Run example code
4. See logs

**Expected behavior**
no errors under "Done"

![image](https://user-images.githubusercontent.com/43097648/118810806-f8a32e80-b8b4-11eb-8819-de7666eeb7f4.png)

**Device:**
Chrome

This is not critical in debug mode.
But, if I use "flutter build web" and run, I see that Controller.getText () doesn't work and the method immediately breaks down

**Comment by tneotia** [comment]
Any error when you use `controller.getText()` on release mode? Or does it just fail to do anything?

Also which version of the plugin are you using?

**Comment by a4ekw** [comment]
html_editor_enhanced: ^2.1.0+1
Flutter 2.0.6 • channel stable
Dart 2.12.3
![image](https://user-images.githubusercontent.com/43097648/118850599-a0325800-b8d9-11eb-85eb-565f3690e4bc.png)
That's all I have

**Comment by tneotia** [comment]
The type error is the real issue there. I don't think the fonts affect any of the editor methods and those messages can be ignored.

**Comment by tneotia** [comment]
> Seems like `handleMessage` was receiving null args, probably should check for that in code

Fixed this in the recent commit. If you can, please try using the git dependency to see if your issue is still present. I can't reproduce it.

**Comment by a4ekw** [comment]
Thank you. I'll write about the results later

**Comment by a4ekw** [comment]
Thank you. Everything works without problems. Good job.
When will you be able to submit the new version to pub. dev?

**Comment by tneotia** [comment]
I want to try and figure out #46 and then I'll publish to Pub. Glad to know it's working!

**Comment by tneotia** [comment]
I'm publishing to pub later today. Thanks for the bug report!

**Comment by tneotia** [comment]
Pushed to Pub.
