### ISSUE TITLE
How to save in a database , the content of an html editor ? [QUESTION]

### ISSUE THREAD

**Issue by Mouss94** [tneotia/html-editor-enhanced#480]
Hello !
I use flutter and iam testing the great html_editor_enhanced library . Could you explain me the different steps , i need to follow to save the content of an html_editor_enhanced page . I would like to save the text and images in the database.
I would like to use Firestore/firebase as database . 

Thank you for your help

**Comment by graemep-nz** [comment]
Images are encoded as base64 text within the html so the whole thing is just one big text file.  Firebase firestore database has a limit of 1MB document size so if the size of the text was more than 1MB you would need to split it up or use a different database.  - or keep the html doc in cloud storage and link to it from the database.

**Comment by Mouss94** [comment]
Thank you very much , it's clear for me . May be if i pay i can store more than 1 mb per document .
Have a great day , thank you again .I will close this question .
