### ISSUE TITLE
Upgrade dependency to flutter_inappwebview: ^6.0.0

### ISSUE THREAD

**Issue by jerperdue** [tneotia/html-editor-enhanced#500]
I am hoping for a package dependency update to flutter_inappwebview: ^6.0.0, which includes support for macOS. Any idea when we might see this dependency updated?

**Comment by jerperdue** [comment]
Looks like there are several other issues asking for dependency updates too.

**Comment by tneotia** [comment]
New version uploaded, sorry for the wait guys
