### ISSUE TITLE
html_editor_enhanced not compatible with flutter 3.22 [BUG]

### ISSUE THREAD

**Issue by soufianebenyaala** [tneotia/html-editor-enhanced#509]
**Describe the bug**
old text Theme  must make compatible with flutter 3.22 

**To Reproduce**
just upgrade to latest flutter version

**Screenshots**
![image](https://github.com/tneotia/html-editor-enhanced/assets/59481648/9442e726-d31e-4815-b8f5-3a8a75b0c5f9)

**Comment by blue492** [comment]
same problems here

**Comment by ygoncharenkofwd** [comment]
easy fix tho, hope the package will be updated soon

**Comment by felipeduarte26** [comment]
same problem, there is already a PR, it needs to be approved, @tneotia

**Comment by adithyank** [comment]
+1 @tneotia 
Please merge PR and publish new version in pub.dev pls

**Comment by sahmed-uas** [comment]
+1 @tneotia Please approve and merge PR

**Comment by RicBau2610** [comment]
@SteveShaw9899 Thank you for the Pull https://github.com/tneotia/html-editor-enhanced/pull/510

You can put the git repository in your pubspec, than you can run your Projects with Flutter 3.22.
```
  html_editor_enhanced:
    git: https://github.com/carmigo/html-editor-enhanced
```

**Comment by tneotia** [comment]
New version uploaded, sorry for the wait guys

**Comment by hakama99** [comment]
@tneotia 
I upgrade to flutter 3.22.2,and upgrade html_editor_enhanced version 2.6.0, my web platform has error in console, web shows with empty.

```
Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')

A message on the flutter/lifecycle channel was discarded before it could be handled.
This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the
ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get
discarded:
  https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html
```


but it fine on  https://github.com/carmigo/html-editor-enhanced.
``` 
html_editor_enhanced:
    git: https://github.com/carmigo/html-editor-enhanced
```

**Comment by hakama99** [comment]
@tneotia 
I used Flutter 3.19.6 and html_editor_enhanced 2.5.1 without any issues.
I upgrade to flutter 3.22.2, my web platform has error with html_editor_enhanced version 2.6.0, web shows with empty.
I update to html_editor_enhanced version 2.6.0 has same ques.

![aa](https://github.com/user-attachments/assets/1f781a5c-bad8-4c9f-b9d0-d71f7eb5dcb3)


```
Rejecting promise with error: TypeError: Cannot set properties of undefined (setting 'nativeCommunication')

A message on the flutter/lifecycle channel was discarded before it could be handled.
This happens when a plugin sends messages to the framework side before the framework has had an opportunity to register a listener. See the
ChannelBuffers API documentation for details on how to configure the channel to expect more messages, or to expect messages to get
discarded:
  https://api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html
```


but it fine on  https://github.com/carmigo/html-editor-enhanced.
``` 
html_editor_enhanced:
    git: https://github.com/carmigo/html-editor-enhanced
```
