### ISSUE TITLE
[QUESTION] show images that require authentication in initialText

### ISSUE THREAD

**Issue by sumitbhanushali** [tneotia/html-editor-enhanced#51]
I have a use case where I require cookie header to load image, is this possible? if yes, how to implement that?

**Comment by tneotia** [comment]
I found this on SO: https://stackoverflow.com/a/60727290

Maybe you can use this and the `html` package I suggested to you earlier to add the `onerror` to the images? I don't have much experience with network requests in HTML and JS, so I don't know for sure if it will work.

**Comment by tneotia** [comment]
Closing this for now... to be honest this is probably difficult to implement. You might have to add some scripts into the plugin to allow this to work, but scripts are only supported on mobile at the moment.
