### ISSUE TITLE
[BUG] PlatformException Unknown feature SUPPRESS_ERROR_PAGE

### ISSUE THREAD

**Issue by urielexis64** [tneotia/html-editor-enhanced#517]
**Describe the bug**
When attempting to use the HtmlEditor, it crashes, rendering it non-interactive. This issue only arises on Android, not on iOS.

**To Reproduce**
1. Just add HtmlEditor in any page and then try to open that page

**Expected behavior**
I expect a functional component like in iOS

**Screenshots**
![image](https://github.com/tneotia/html-editor-enhanced/assets/47485144/c4f46ca9-8013-4775-bc49-a10533bdb675)

**Device:**
Physical device Samsung A33, android 14

Flutter doctor:
![image](https://github.com/tneotia/html-editor-enhanced/assets/47485144/fee8a6eb-b6f8-4898-b43d-7dc30e52a1f2)

I'm using the latest version of the dependency (2.6.0)

**Comment by naumanmir** [comment]
Yes, i have encountered same error after flutter upgrade. Any solution to this?

**Comment by Zeelsarvadhi** [comment]
Yes, i'm facing same error on Web after flutter upgrade in latest version. Any solution to this?

**Comment by LiLatee** [comment]
Same here on Android.

**Comment by naumanmir** [comment]
Still no solution.

**Comment by dharmbirkapylon** [comment]
Same here, Suddenly stopped working on android even working fine in iOS.

**Comment by slowlow79464** [comment]
For me, solved according this link:
https://github.com/pichillilorenzo/flutter_inappwebview/issues/2150#issuecomment-2132114530

**Comment by cd89101112** [comment]
Add the following configuration to your app build.gradle.

```groovy
allprojects {
    configurations.all {
        resolutionStrategy {
            force 'androidx.webkit:webkit:1.8.0'
        }
    }
}

**Comment by urielexis64** [comment]
> On Android，Add the following configuration to your app build.gradle.
> 
> ```groovy
> allprojects {
>     configurations.all {
>         resolutionStrategy {
>             force 'androidx.webkit:webkit:1.8.0'
>         }
>     }
> }
> ```

It works! Thank you so much!
