### ISSUE TITLE
I am attempting to use multiple htmleditors on a single page, but a white overlay covers the page [QUESTION]

### ISSUE THREAD

**Issue by connectuRecruiting** [tneotia/html-editor-enhanced#53]
I am using multiple html editors on a single page. They appear to be acting regular in a sense where I can edit the text in them individually and use them with no errors. However, when I have multiple on one page, there is a white overlay that covers the screen. Is there a correct way to implement multiple on one page?

**Comment by tneotia** [comment]
What device do you test on? (Web/android/ios)? Also a screenshot would be helpful :)

**Comment by connectuRecruiting** [comment]
I am testing on android. I can also test on ios and let you know if that changes the results. Figured it was an implementation error.

The first is an example when there are multiple on the page. 
![image](https://user-images.githubusercontent.com/65565675/119900708-e0658c00-bf12-11eb-862d-fecf20840c93.png)

The second is an example of a single object on the page.
![image](https://user-images.githubusercontent.com/65565675/119900745-ece9e480-bf12-11eb-8925-8d80196d568d.png)

**Comment by connectuRecruiting** [comment]
After playing with them a little more I am realizing that each additional HTMLEditor object makes the entire page have a little more of a white overlay. In the stack they are in a listview and in a sized box.

**Comment by tneotia** [comment]
If you don't mind me asking - if you just want text editing functionality then why don't you go with a regular TextField widget? If you need it to go as HTML code in the api request just add `<p>` tags to the beginning and end of the string.

I'll still look into this though!

**Comment by connectuRecruiting** [comment]
The API the company I am working with right now wants the full WYSIWYG feel so they can use the same text online. Your editor does a great job at that so I was attempting to use your package

**Comment by tneotia** [comment]
I understand. So if I am reading correctly your widget tree looks kind of like this correct?

```dart
ListView(
   children: [
      //Other widgets
      SizedBox(child: HtmlEditor()),
      SizedBox(child: HtmlEditor()),
      HtmlEditor(),
      //Other widgets
   ]
)
```
To be honest I still don't quite understand what you mean by white overlay, in your screenshot it looks to me like both editors are functional (can input text), just one has a hint and the other does not.

**Comment by connectuRecruiting** [comment]
So they are both functional, but if you look at the gold title, there is a white overlay on the text and the others. I can send you a version with no HTML editors to show how deep the difference gets.

**Comment by tneotia** [comment]
Ah I see the difference.... That is really strange, don't know why that would be the case. I'll look into this today or tomorrow.

**Comment by connectuRecruiting** [comment]
Okay, thank you! I am wondering if it has to do with the parent widgets.

**Comment by connectuRecruiting** [comment]
After a great amount of attempting to reproduce, the issue appears to be in a color filter on the background image. Here is a reproducible code: 

`import 'package:flutter/material.dart';
import 'package:html_editor_enhanced/html_editor.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  HtmlEditorController oneController = HtmlEditorController();

  HtmlEditorController twoController = HtmlEditorController();

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
        appBar: AppBar(
          // Here we take the value from the MyHomePage object that was created by
          // the App.build method, and use it to set our appbar title.
          title: Text(widget.title),
        ),
        body: Stack(
          children: [
            //this method return the blue background globe image that is lightly shown under the application, this also return the slightly tinted overview for it.
            Padding(
              padding: EdgeInsets.fromLTRB(0, 0, 0, 0),
              child: ColorFiltered(
                colorFilter: ColorFilter.mode(
                    Colors.white.withOpacity(0.25), BlendMode.dstATop),
                child: Image.asset(
                  "assets/pagebackground.png",
                  fit: BoxFit.cover,
                  height: double.infinity,
                  width: double.infinity,
                ),
              ),
            ),
            ListView(
              children: [
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Text(
                    "TESTING TITLE",
                    style: TextStyle(
                        color: Colors.yellow, fontWeight: FontWeight.bold),
                  ),
                ),
                HtmlEditor(
                  controller: oneController,
                  htmlToolbarOptions: HtmlToolbarOptions(
                      toolbarPosition: ToolbarPosition.custom),
                ),
                HtmlEditor(
                  controller: twoController,
                  htmlToolbarOptions: HtmlToolbarOptions(
                      toolbarPosition: ToolbarPosition.custom),
                )
              ],
            )
          ],
        ) // This trailing comma makes auto-formatting nicer for build methods.
        );
  }
}
`

**Comment by tneotia** [comment]
Hmm that is really odd, could be due to how `WebView` `PlatformView`s work on Flutter. Thanks for the insight - I had tried to test this but I couldn't reproduce so this is helpful.

Is your initial issue resolved (is it alright to close this ticket)?

**Comment by connectuRecruiting** [comment]
You can close the ticket. Hopefully, this provides some insight into other things maybe? Side note, I still get some null safety warnings with the 2.1.1 version, is that normal?

**Comment by tneotia** [comment]
I see those, I will fix them today.

**Comment by tneotia** [comment]
Fixed via 8923d247aced2bf9ca3c0fde39182b95fad6f781.

**Comment by connectuRecruiting** [comment]
Great work on this API, love using it!

**Comment by tneotia** [comment]
Thanks, glad you like it!! :)
