### ISSUE TITLE
Is there dispose method?

### ISSUE THREAD

**Issue by akmichael** [tneotia/html-editor-enhanced#56]
On parent widget closing (back button click), html_editor keep dispayed for few seconds and disappears. How to avoid this? is there any dispose method?

**Comment by tneotia** [comment]
I think this is an issue with `flutter_inappwebview` (displays the editor box) - I have this issue in my production app using the same plugin:

https://user-images.githubusercontent.com/50850142/120941471-f03e5680-c6f0-11eb-8196-34ee5e87ed28.mp4

The WebView component hovers on the screen after the animation for a split second. I think this has to do with using Hybrid Composition rendering so this could even be a Flutter issue.

**Comment by tneotia** [comment]
I still see this issue but I am going to close it because I cannot do anything to fix this, it is a `flutter_inappwebview` or a Flutter issue. Thanks for the report.
