### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by raghavan-mookiah** [tneotia/html-editor-enhanced#6]
**Describe the bug**
VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'double' is not a subtype of type 'int?' in type cast
#0      _HtmlEditorWidgetMobileState.build.<anonymous closure>
package:html_editor_enhanced/…/widgets/html_editor_widget_mobile.dart:294
<asynchronous suspension>

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device:**
Add device details here.

**Additional context**

**Comment by tneotia** [comment]
Fixed via cd823453d020a97ee9a401e1e67f28d596693035, thanks for reporting!
