### ISSUE TITLE
[BUG] Crash on Android

### ISSUE THREAD

**Issue by hungcaohnc** [tneotia/html-editor-enhanced#60]
**Describe the bug**
I am trying to launch the example code on Android but it crashes on startup. The iOS runs well

**Comment by hungcaohnc** [comment]
This is the error output I got: 

Build fingerprint: 'google/sdk_gphone_x86_64/generic_x86_64_arm64:11/RSR1.201211.001/7027799:user/release-keys'
Revision: '0'
ABI: 'x86_64'
Timestamp: 2021-06-10 16:22:06+0700
pid: 19231, tid: 19231, name: nhanced_example  >>> com.tanayneotia.html_editor_enhanced_example <<<
uid: 10154
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    rax 0000000000000000  rbx 0000000000004b1f  rcx 00007a89b67ef2a8  rdx 0000000000000006
    r8  0000000000000010  r9  0000000000000010  r10 00007ffc0f955480  r11 0000000000000246
    r12 0000000000000000  r13 00007a87517cece8  r14 00007ffc0f955478  r15 0000000000004b1f
    rdi 0000000000004b1f  rsi 0000000000004b1f
    rbp 00007ffc0f955668  rsp 00007ffc0f955468  rip 00007a89b67ef2a8

**Comment by hungcaohnc** [comment]
This is flutter doctor:

[✓] Flutter (Channel master, 2.3.0-2.0.pre.191, on macOS 11.2.2 20D80 darwin-x64, locale en-VN)
    • Flutter version 2.3.0-2.0.pre.191 at /Users/hungcao/Documents/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 855ada1d95 (4 weeks ago), 2021-05-13 17:13:03 -0700
    • Engine revision c118a134fb
    • Dart version 2.14.0 (build 2.14.0-112.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/hungcao/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • HTC Butterfly 2 (mobile)   • HT58EWZ00242                         • android-arm    • Android 6.0.1 (API 23)
    • sdk gphone x86 64 (mobile) • emulator-5554                        • android-x64    • Android 11 (API 30) (emulator)
    • iPhone 11 Pro (mobile)     • BB53CC4C-9AFE-4ABF-8A50-F5FB1D3632C1 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 91.0.4472.77
    ! Error: Hung’s iPhone is not connected. Xcode will continue when Hung’s iPhone is connected. (code -13)

**Comment by tneotia** [comment]
Hmm looks like you are using the Android emulator. I use a physical device and I don't have any issues, could you try it on a physical Android if possible? Sometimes the emulator is weird with webviews and such.

**Comment by hungcaohnc** [comment]
> Hmm looks like you are using the Android emulator. I use a physical device and I don't have any issues, could you try it on a physical Android if possible? Sometimes the emulator is weird with webviews and such.

Hi, thank you for your reply. I checked on Bluestack and an Android phone as well (my phone is HTC) and I got crashes all the cases. Which physical device did you use?

**Comment by tneotia** [comment]
I have 2 Samsung phones - S8 and S10, the plugin works fine on both. I haven't had any reports of crashes on Android, the logs you posted are not very helpful... are there different logs on your physical device?

**Comment by hungcaohnc** [comment]
> I have 2 Samsung phones - S8 and S10, the plugin works fine on both. I haven't had any reports of crashes on Android, the logs you posted are not very helpful... are there different logs on your physical device?

Hmm, the logs are the same for all of mine. Let me check that again with another physical device and let you know then. Thanks so much, it is really a great plugin

**Comment by tneotia** [comment]
Now that I think about it, the crash might be because of using Flutter master. I use beta and everything works fine, if you can downgrade and try it that works be good.

**Comment by hungcaohnc** [comment]
> Now that I think about it, the crash might be because of using Flutter master. I use beta and everything works fine, if you can downgrade and try it that works be good.

Yes, you are correct. It works well when I switched to beta. Could you check what's wrong with mater channel? Also, after switching to beta and back to master, then upgrade to latest Flutter version, I got another issue now. Maybe we need to update flutter_colorpicker also?

 ../../.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.4.0/lib/src/hsv_picker.dart:731:29: Error: The argument type
    'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'.
     - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart'
     ('../Development/flutter/packages/flutter/lib/src/gestures/events.dart').
     - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart'
     ('../Development/flutter/packages/flutter/lib/src/gestures/events.dart').
        super.addAllowedPointer(event);

**Comment by tneotia** [comment]
@hungcaohnc there isn't any update for color picker yet so once the breaking change moves to dev/beta they will probably fix it.

As for fixing the crash on master, I don't think it's a great idea to look into it because it could be a bug in Flutter - master channel is often like that, then they polish it up every week and create a dev release. If the crash is on dev I will try to fix it but it's rather not check the bugs on master since it isn't the most reliable branch.

**Comment by tneotia** [comment]
@hungcaohnc I have published v2.2.0+1-dev.1 with the new `flutter_colorpicker` changes.
