### ISSUE TITLE
Does this plugin support Web development?

### ISSUE THREAD

**Issue by astudilloalex** [tneotia/html-editor-enhanced#61]
In the development page it does not mark for Web, but in GitHub it tells us that it is.
![image](https://user-images.githubusercontent.com/48831301/121542380-b8276400-c9cd-11eb-8a26-7a744a3bc9e2.png)

**Comment by tneotia** [comment]
Yes it does support web, Pub isn't super smart when it comes to showing the supported platforms. Try it out! :)

**Comment by astudilloalex** [comment]
Thank you!
