### ISSUE TITLE
html_editor_enhanced: ^2.1.1[BUG] 

### ISSUE THREAD

**Issue by kizinho** [tneotia/html-editor-enhanced#62]
**Describe the bug**
bug on the latest version null safety

**To Reproduce**
1. After installing the package just hot restart
FlutterApplication/flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.1.1/lib/src/widgets/toolbar_widget.dart:2286:74: Warning: Operand of null-aware operation '!' has type 'String' which excludes null.   result!.files.single.name!;

**Expected behavior**
not error

**Device:**
both real and emulator

**Comment by tneotia** [comment]
Hi, this is a known bug and was fixed by 8923d247aced2bf9ca3c0fde39182b95fad6f781. I hope to push a new version to pub.dev soon, then this warning will go away. It does not cause any errors, you can use the package as normal.

**Comment by kizinho** [comment]
I love the editor , will be waiting for the update soon , just that the
error annoys me though no effect

>
