### ISSUE TITLE
[FEATURE] Update flutter_colorpicker

### ISSUE THREAD

**Issue by rmasarovic** [tneotia/html-editor-enhanced#64]
The new flutter SDK in beta channel have same breaking change. Its possible update flutter_colorpicker to 0.5.0? and create beta package?

**Comment by tneotia** [comment]
Sure, I will publish v2.2.0+1 with updated color picker today.

**Comment by tneotia** [comment]
I have published v2.2.0+1-dev.1 with the new changes.
