### ISSUE TITLE
Compile error on Flutter 2.2.2

### ISSUE THREAD

**Issue by MichelFortes** [tneotia/html-editor-enhanced#68]
**Describe the bug**
Compile error on Flutter 2.2.2

**Config**
Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (6 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [versÃ£o 10.0.19041.1052], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2021.1)
[√] Connected device (3 available)

**Error**
Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 'PointerDownEvent', which does not match the corresponding type, 'PointerEvent', in the overridden method, 'DragGestureRecognizer.addAllowedPointer'.
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('/C:/src/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('/C:/src/flutter/packages/flutter/lib/src/gestures/events.dart').
Change to a supertype of 'PointerEvent', or, for a covariant parameter, a subtype.

**Comment by MichelFortes** [comment]
I just realized this is a flutter_colorpicker-0.5.0 package issue.

"(...).pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.5.0/lib/src/hsv_picker.dart:730:43: Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 'PointerDownEvent' "

**Comment by tneotia** [comment]
Try these:

1. Downgrade to v2.2.0 instead of v2.2.0+1-dev.1

If that doesn't work then

2. Set pubspec to 
```yaml
dependencies:
   html_editor_enhanced: ^2.2.0

dependency_overrides:
   flutter_colorpicker: ^0.4.0
```

**Comment by MichelFortes** [comment]
Those changes fixed the issue.
Everything is working great now.
Thank you.

**Comment by tneotia** [comment]
Good to hear, sorry for the inconvenience.
