### ISSUE TITLE
Unable to run on web with Flutter 2.2.2 • channel beta 

### ISSUE THREAD

**Issue by pakbachelors** [tneotia/html-editor-enhanced#70]
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.2.0+1-dev.1/lib/src/widgets/toolbar_widget.dart:7:8: Error: Error when reading '../../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.5.0/lib/flutter_colorpicker.dart': No such file or directory
import 'package:flutter_colorpicker/flutter_colorpicker.dart';
       ^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.2.0+1-dev.1/lib/src/widgets/toolbar_widget.dart:1111:36: Error: The method 'ColorPicker' isn't defined for the class 'ToolbarWidgetState'.
 - 'ToolbarWidgetState' is from 'package:html_editor_enhanced/src/widgets/toolbar_widget.dart' ('../../../../flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.2.0+1-dev.1/lib/src/widgets/toolbar_widget.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ColorPicker'.
                            child: ColorPicker(
                                   ^^^^^^^^^^^
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.2.0+1-dev.1/lib/src/widgets/toolbar_widget.dart:1113:44: Error: The getter 'PaletteType' isn't defined for the class 'ToolbarWidgetState'.
 - 'ToolbarWidgetState' is from 'package:html_editor_enhanced/src/widgets/toolbar_widget.dart' ('../../../../flutter/.pub-cache/hosted/pub.dartlang.org/html_editor_enhanced-2.2.0+1-dev.1/lib/src/widgets/toolbar_widget.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'PaletteType'.
                              paletteType: PaletteType.hsv,
                                           ^^^^^^^^^^^
Failed to compile application.

**Comment by tneotia** [comment]
See this answer: https://github.com/tneotia/html-editor-enhanced/issues/68#issuecomment-863369808

**Comment by pakbachelors** [comment]
> See this answer: [#68 (comment)](https://github.com/tneotia/html-editor-enhanced/issues/68#issuecomment-863369808)
> 
> I guess flutter beta also has this issue. Sorry for the inconvenience.

is there way to run on web? because i see your web screenshot. Thanks.

**Comment by tneotia** [comment]
Yes it works like a normal plugin on web, no extra configuration required.

**Comment by tneotia** [comment]
Closing for now, let me know if you have any other questions.
