### ISSUE TITLE
[BUG] Error Domain=packages/html_editor_enhanced/assets/summernote-no-plugins.html asset file cannot be found! Code=0 "

### ISSUE THREAD

**Issue by hockleongloh** [tneotia/html-editor-enhanced#73]
- Error Domain=packages/html_editor_enhanced/assets/summernote-no-plugins.html asset file cannot be found! Code=0 "(null)" #0
  - super: NSObject

When using physical device (iPhone) to test, it will prompt following error in my log and keyboard won't show up when click for HtmlEditor. Android is working fine, even iOS emulator also can. But it seems only iOS physical device encounter this issue.

**Expected behaviour**
A keyboard prompt up and allow user to type in the wording he/she desired

**Device:**
iPhone XS (Version: 14.6)

**Package version using**
2.2.0

**Comment by tneotia** [comment]
Hmm that is strange. Did you try clean install? 

Never had this issue, I use this plugin in a production app and my iOS testers didn't get this issue. If it works on Simulator I don't know why it wouldn't work on physical.

**Comment by hockleongloh** [comment]
I have try run flutter clean and install again but it's still the same. Wondering what caused for this issue.

**Comment by tneotia** [comment]
Just curious, this may be fixable by using `filePath` and providing your own HTML. filepath is documented in the readme, please check there. If you need help implementing it let me know and I can send an example later. If the filepath method works then it may be a bug in the package.

**Comment by hockleongloh** [comment]
It would be better if you can send me an example and try for it. Thanks

**Comment by tneotia** [comment]
Okay here is the working example:

Create assets folder and add:

`summernote.html`:
```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="description" content="Flutter Summernote HTML Editor">
    <meta name="author" content="tneotia">
    <title>Summernote Text Editor HTML</title>
    <script src="jquery.min.js"></script>
    <link href="summernote-lite.min.css" rel="stylesheet">
    <script src="summernote-lite.min.js"></script>
    <!--darkCSS-->
</head>
<body>
<div id="summernote-2"></div>
<!--headString-->
<!--summernoteScripts-->
</body>
</html>
```
Also copy paste `summernote-lite.min.css`, `summernote-lite.min.js`, and `jquery.min.js` from this project `lib/assets` into the same directory.

Then add to pubspec.yaml:
```yaml
assets:
    - assets/
```
and finally in your view file:
```dart
HtmlEditor(
                controller: controller,
                htmlEditorOptions: HtmlEditorOptions(
                  filePath: "assets/summernote.html"
                ),
),
```

Please check to see if this method works. I know it is a little bit of a hassle because you need to add some files but it might be a good solution. It works fine on the Simulator for me.

**Comment by tneotia** [comment]
@hockleongloh was this able to solve your issue?

**Comment by hockleongloh** [comment]
Hi @tneotia , it seems Its due to local network privacy permission in iOS14. I'm able to fix it by following the guideline.
Thanks for your help.

https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions

**Comment by tneotia** [comment]
@hockleongloh hope you were able o solve your issue. Closing for now, let me know if you need anything else.
