### ISSUE TITLE
How to add LaTeX or any math formula support to my HTML editor?

### ISSUE THREAD

**Issue by alirezaemami** [tneotia/html-editor-enhanced#74]
I need to add LaTeX (or any other approach) to add formula in my HTML

**Comment by tneotia** [comment]
I don't know how LaTeX works in HTML, is there some JS/CSS you have to add? How would you add LaTeX support to a normal HTML document? This will help me figure out a way to support it in the editor.

**Comment by alirezaemami** [comment]
To add LaTex or MathJax, we only need to be able to add a script to the iframe head.
`

          initialText: r"""
           <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
          <script type="text/javascript" id="MathJax-script" async
            src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
          </script>
           Look at this: \(ax^2 + bx + c = 0\) \(\sqrt{x}\)"""
                      
 


`

[http://docs.mathjax.org/en/latest/web/examples.html](url)


<img width="879" alt="Screen Shot 2021-06-27 at 14 46 57" src="https://user-images.githubusercontent.com/23387774/123540986-1fc40a00-d757-11eb-88a5-2b85588c6024.png">

This code is obviously not a good approach but, it is working.
We need to remove the script from the initialText and move it somewhere else(but we don't know where).

**Comment by alirezaemami** [comment]
There is another problem with RTL
By switching LTR to RTL, MathJaX will fail and will not work again.
<img width="473" alt="Screen Shot 2021-06-27 at 14 59 40" src="https://user-images.githubusercontent.com/23387774/123541167-4e8eb000-d758-11eb-84bb-a0241fe48288.png">

**Comment by tneotia** [comment]
Okay thanks for the detail.  Change your app like this:
`pubspec.yaml`:
```yaml
flutter:
  assets:
    - assets/
```
create `assets/summernote.html`:
```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="description" content="Flutter Summernote HTML Editor">
    <meta name="author" content="tneotia">
    <title>Summernote Text Editor HTML</title>
    <script src="file:///android_asset/flutter_assets/packages/html_editor_enhanced/assets/jquery.min.js"></script>
    <link href="file:///android_asset/flutter_assets/packages/html_editor_enhanced/assets/summernote-lite.min.css" rel="stylesheet">
    <script src="file:///android_asset/flutter_assets/packages/html_editor_enhanced/assets/summernote-lite.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
    </script>
</head>
<body>
<div id="summernote-2"></div>
</body>
</html>
```
`HtmlEditor`:
```dart
HtmlEditor(
  controller: controller,
  htmlEditorOptions: HtmlEditorOptions(
    filePath: "assets/summernote.html",
  ),
),
```

This should work but I haven't tested it. As for RTL, don't really know, maybe because the browser reads the entered characters backwards which breaks LaTeX parsing? Try it again with the above method and if it doesn't work I'd suggest disabling RTL direction.

**Comment by tneotia** [comment]
Thanks for the detail, just noticed you are using Flutter Web. I know how to implement this and will provide a solution for you soon.

**Comment by tneotia** [comment]
@alirezaemami can you try this:

Create a custom HTML file in your assets:

```html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="description" content="Flutter Summernote HTML Editor">
    <meta name="author" content="tneotia">
    <title>Summernote Text Editor HTML</title>
    <script src="jquery.min.js"></script>
    <link href="summernote-lite.min.css" rel="stylesheet">
    <script src="summernote-lite.min.js"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
    </script>
    <!--darkCSS-->
</head>
<body>
<div id="summernote-2"></div>
<!--headString-->
<!--summernoteScripts-->
<style>
  body {
      display: block;
      margin: 0px;
  }
  .note-editor.note-airframe, .note-editor.note-frame {
      border: 0px solid #a9a9a9;
  }
  .note-frame {
      border-radius: 0px;
  }
</style>
</body>
</html>
```

Then pass the file location in your `HtmlEditor` > `HtmlEditorOptions` > `filePath` parameter to load it.

Let me know if it doesn't work or you need more help.

**Comment by alirezaemami** [comment]
Thank you for paying attention to this issue.
I understand that users are not comfortable writing formulas and I am combining libraries to provide a suitable solution for my project.
I am currently using the [math_keyboard](https://pub.dev/packages/math_keyboard) library to get formulas from users and convert formulas to LaTeX, and I want to display the LaTeX output in [html-editor-enhanced](https://github.com/tneotia/html-editor-enhanced).
I hope I can create a good UX for users.

I'm currently developing part of an online testing project called Wikiazma, and I want my users able to design complex questions freely. I need a WYSIWYG editor for this, but unfortunately, Flutter is still weak in this, and after reviewing dozens of libraries, HTML seems to work better than Markdown, Quill, and etc.

**Comment by tneotia** [comment]
Yes you are correct, the wysiwyg functionality in Flutter is very lacking, especially because their webview support is not great. Hopefully it gets better in the future.

If you have any other questions feel free to ask. Thanks!

**Comment by adithyank** [comment]
is it possible to use `controller.insertText()` or `controller.insertHtml()` to insert an expression dynamically?

**Comment by AnjanaKolipati** [comment]
I am using the html_editor_enhanced package in my Flutter application to insert and edit math equations using MathJax. While the equations display correctly, when I try to edit the content, extra HTML code gets added to the original data. How can I prevent this issue?

Here's the relevant part of my code:

HtmlEditor(
  controller: controller,
  htmlEditorOptions: HtmlEditorOptions(
    shouldEnsureVisible: true,
    hint: "Enter Description ...",
  ),
  htmlToolbarOptions: HtmlToolbarOptions(
    customToolbarButtons: [
      CustomMathButton(controller: controller),
    ],
    defaultToolbarButtons: [
      FontButtons(),
      ListButtons(),
      ParagraphButtons(),
      ColorButtons(),
      InsertButtons(
        video: true,
        audio: true,
        otherFile: true,
      ),
    ],
  ),
  otherOptions: OtherOptions(
    height: 200,
  ),
  callbacks: Callbacks(
    onChangeContent: (String? content) {
      state.didChange(content);
    },
  ),
),

I also use the following script for loading MathJax in the editor.This is my input:

<p><span class="math-tex">\(x = {-b \pm \sqrt{b^2-4ac} \over 2a}\)</span>&nbsp;sample11</p>  <script type="text/javascript">
    (function() {
      if (!window.MathJax) {
        var script = document.createElement("script");
        script.type = "text/javascript";
        script.src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML";
        script.onload = function() {
          MathJax.Hub.Config({
            tex2jax: {
              inlineMath: [['\\(', '\\)']],
            }
          });
          MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
        };
        document.head.appendChild(script);
      } else {
        MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
      }
    })();
  </script>
