### ISSUE TITLE
[BUG] White background color on text when pressing backspace on existing text

### ISSUE THREAD

**Issue by craigspicer** [tneotia/html-editor-enhanced#76]
**Describe the bug**
In dark mode, when backspace is pressed at the beginning of a line, white background color is inserted.

**To Reproduce**
1. Enable dark mode.
2. Click at the beginning of a line where the line is preceded by an empty line above.
3. Click back space.
4. White background appears.

**Expected behavior**
The document should be moved up one line with no html inserted.

**Screenshots**
1. https://paste.pics/6f4d478a40c84b11b1510507b6a362b7
2. Backspace is pressed: https://paste.pics/3a06dfd8e760a4e4f9e5f42414108eaf
3. White background color has been inserted: https://paste.pics/7876bebab4f4bda676dff27d35495eb1

**Device:**
Tested on multiple devices included on web. Screenshots from Android emulator Pixel 3a running Android 7 (API level 25).

**Comment by tneotia** [comment]
Hmm I wonder why it sets white as the background color of the span... I'll have to look into the editor JS to see if its a problem there. Thanks for the report!

**Comment by craigspicer** [comment]
Thanks for the quick response! The editor is great by the way. Really nice work! This also happened on occasion when I pasted in text. Difficult to reproduce but I'll look out for it. It was possibly text that was pasted in from a web page that had white background set in the html.

**Comment by tneotia** [comment]
Did some more testing and the Bootstrap version of Summernote doesn't have this issue which leads me to believe the issue is in fact with Summernote... I'm thinking of migrating away from Summernote and making a custom `contenteditable` due to some of the big issues it has.

**Comment by Huanxin1997** [comment]
> Did some more testing and the Bootstrap version of Summernote doesn't have this issue which leads me to believe the issue is in fact with Summernote... I'm thinking of migrating away from Summernote and making a custom `contenteditable` due to some of the big issues it has.

Hi, we meet this issue too. How is the progress of this issue now ?

**Comment by tneotia** [comment]
Unfortunately there hasnt been any progress. For now I recommend disabling the dark mode on the editor window if this is an issue. I have been busy with other projects so haven't had much time to maintain this one, I would like to go fully native eventually with version 3.0.0 removing need for WebView and summernote.

**Comment by Huanxin1997** [comment]
> Unfortunately there hasnt been any progress. For now I recommend disabling the dark mode on the editor window if this is an issue. I have been busy with other projects so haven't had much time to maintain this one, I would like to go fully native eventually with version 3.0.0 removing need for WebView and summernote.

Thanks for your reply. 
I try review summernote（[https://summernote.org/](url)） demo, this bug will not appear. After our investigation, it is the CSS that has a problem. 
Do these two lines of CSS do anything special? Once removed, this bug will not appear.
![image](https://user-images.githubusercontent.com/42678103/143375826-9f77cffe-eae3-443a-8d34-b313ebd21311.png)

**Comment by tneotia** [comment]
> Do these two lines of CSS do anything special? Once removed, this bug will not appear.

I don't think so - I didn't add this CSS, it is the way the Summernote non-Bootstrap version came. If this is the problem, in the next update I will remove these two lines. Nice find!!!
