### ISSUE TITLE
[BUG] SummernoteAtMention isn't working as expected

### ISSUE THREAD

**Issue by Barry0501** [tneotia/html-editor-enhanced#77]
Hi author, it's me again :)). It always has a whitespace between "@" and "username" if the element is not the first one in the array. See my video below for getting more information

https://user-images.githubusercontent.com/34902237/123768100-3bafe300-d8f2-11eb-8421-f7e7e0be6822.mov

](url)

**Comment by Barry0501** [comment]
I think it would be great if the keyboard still shows after the user tapped some element in the list suggestion

**Comment by tneotia** [comment]
Let me see what I can do with these... Don't know why this behavior is so buggy lol. Thanks for reporting.

**Comment by tneotia** [comment]
I fixed the main issue.... however the keyboard thing I cannot solve, it is an issue with the webview plugin. It thinks that the user is tapping away from the editor and the "editable" section so it wants to hide the keyboard. Really unfortunate :(

**Comment by Barry0501** [comment]
Thank you for your time. I think it would be great if I can add background color for text which is mention user
<img width="224" alt="Screen Shot 2021-06-30 at 15 38 49" src="https://user-images.githubusercontent.com/34902237/123929713-4b462f00-d9b9-11eb-9905-561ecedbeaa9.png">

**Comment by tneotia** [comment]
I will look into that though I don't think it will be possible because the mentions plugin simply inserts the text after the @ symbol, it doesn't add any coloring or border to the text.

**Comment by tneotia** [comment]
I looked into this earlier and it is too complex to change the colors. I'm not experienced enough in JavaScript to be able to do this. If anyone seeing this feels they can do it, a PR would be gladly appreciated.
