### ISSUE TITLE
[QUESTION] How to add a font?

### ISSUE THREAD

**Issue by phaylali** [tneotia/html-editor-enhanced#78]
I already have a font that I use in my entire app , it's called Tajawal, an Arabic font but it's also a google font, so there more ways to implement it, the question is, how to add any custom font, whether by google fonts or directly, to the list of fonts choices in the editor toolbar?

**Comment by tneotia** [comment]
Check the discussion I had for the exact same question at #59. If you have any other questions let me know! :)
