### ISSUE TITLE
dependency_overrides required in web

### ISSUE THREAD

**Issue by alirezaemami** [tneotia/html-editor-enhanced#80]
why we should override flutter_colorpicker to use  `html-editor-enhanced` in web?

**Comment by tneotia** [comment]
I messed up when creating a release and accidentally released a version with a beta version of color_picker that requires Flutter dev. If you accidentally upgraded to plugin v2.2.0+1-dev.1 then you will have an issue when building. Using dependency_overrides fixes the issue temporarily, and won't be necessary once the breaking changes in Flutter dev version make their way to Flutter stable.

**Comment by alirezaemami** [comment]
Thanks for your clear explanation.

**Comment by alirezaemami** [comment]
I use` html_editor_enhanced: ^2.2.0` but still now working without overriding `flutter_colorpicker: ^0.4.0`

**Comment by tneotia** [comment]
Downgrading does not fix the issue after you have already upgraded for some reason so the dependency override is still necessary unfortunately.

**Comment by tneotia** [comment]
Closing for now... The dependency_override will fix this issue for sure. In a later release of flutter it will not be necessary.
