### ISSUE TITLE
[BUG] Lose focus on editor (version 2.2.0+1-dev.1)

### ISSUE THREAD

**Issue by foxbunlong** [tneotia/html-editor-enhanced#84]
**Describe the bug**
Lost focus on editor (in a bottomsheet) after picking color. So user cannot continue to type with color format.

**To Reproduce**
1. Open bottomsheet with html editor
2. Type something
3. Click on change color and select correct color
4. Continue to type, no text is applied

**Expected behavior**
Html editor should show new text with color format

**Device:**
Virtual machine Android 8.0

**Comment by tneotia** [comment]
Yep this is another bug with focus on the editor. Can't do anything here because when the user clicks on a button it will remove focus from the WebView for some reason.

**Comment by bhanu-under25** [comment]
Can we use focus node to manually contoll focus in editor

**Comment by tneotia** [comment]
Unfortunately no because the editor is a webview, it does not have a focus node.

**Comment by cksoft0807** [comment]
So there is no way to regain focus once it is lost?

**Comment by tneotia** [comment]
The original issue has been fixed, but for tracking focus issues please see #47

**Comment by foxbunlong** [comment]
@tneotia thank you I will update to newest version and give it a try. Thanks 👍
