### ISSUE TITLE
Remove unnecessary label

### ISSUE THREAD

**Issue by Barry0501** [tneotia/html-editor-enhanced#85]
Hi author, I think it is better if we remove a label (see picture below to getting more information)
![Simulator Screen Shot - iPhone 11 - 2021-07-05 at 14 26 51](https://user-images.githubusercontent.com/34902237/124442544-0d754c00-dda7-11eb-8a5e-5b98aaf2da4e.png)

**Comment by Barry0501** [comment]
<img width="499" alt="Screen Shot 2021-07-05 at 15 39 31" src="https://user-images.githubusercontent.com/34902237/124442709-34338280-dda7-11eb-8c3f-a0cbd885b4ec.png">

**Comment by tneotia** [comment]
That label is there from summer note, use controller.setFullscreen to remove it

**Comment by tneotia** [comment]
@Barry0501 hope that code helped you. If you have any questions, as always let me know!
