### ISSUE TITLE
How to set the image width to 100% by default

### ISSUE THREAD

**Issue by scandalYang** [tneotia/html-editor-enhanced#86]
45/5000 
The default width of pictures and videos is very wide. You can set the width to 100% after clicking. How to make the default width of them be 100%

**Comment by tneotia** [comment]
Hi there, once I get home I will post an example for you here. :)

**Comment by tneotia** [comment]
Sorry for the delay, something like this should work:

```dart
Widget editor = HtmlEditor(
    controller: controller,
    toolbarOptions: ToolbarOptions(
      mediaUploadInterceptor: (PlatformFile file, InsertFileType type) async {
         if (type == InsertFileType.image) {
              String base64Data = base64.encode(file.bytes!);
              String base64Image =
              """<img src="data:image/${file.extension};base64,$base64Data" data-filename="${file.name}" width="your_width_here"/>""";
              controller.insertHtml(base64Image);
            }
      },
    ),
  );
```

You can apply a hardcoded width or from `MediaQuery` to suit your needs inside the HTML string there.

**Comment by tneotia** [comment]
Hope the above answer helped you, closing for now. Let me know if you have further questions.
