### ISSUE TITLE
[BUG] Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 'PointerDownEvent', which does not match the corresponding type, 'PointerEvent', in the overridden method, 'DragGestureRecognizer.addAllowedPointer'.

### ISSUE THREAD

**Issue by agorneo** [tneotia/html-editor-enhanced#87]
Hello,
A wonderful and amazing day for all of us

I am trying your package (I am new to Flutter and Dart)...

**Describe the bug**
When I try to run the flutter app I get:
`Waiting for connection from debug service on Chrome...
../../../../apps/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.5.0/lib/src/hsv_picker.dart:730:43: Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 'PointerDownEvent', which does not match the corresponding type, 'PointerEvent', in the overridden method, 'DragGestureRecognizer.addAllowedPointer'.
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../apps/flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../../../apps/flutter/packages/flutter/lib/src/gestures/events.dart').
Change to a supertype of 'PointerEvent', or, for a covariant parameter, a subtype.
  void addAllowedPointer(PointerDownEvent event) {`

**To Reproduce**
Packages
`  cupertino_icons: ^1.0.2

  dio: ^3.0.10
  faker: ^1.2.1
  flutter_launcher_icons: ^0.9.0
  rxdart:
  rxform:
  sprinkle:
    path: ../../_forked/sprinkle/
  logger: ^0.7.0
  logger_flutter: ^0.7.1
  url_launcher:
  intl: ^0.17.0
  confirm_dialog: ^1.0.0
  font_awesome_flutter: ^9.1.0
  html_editor_enhanced: ^2.2.0+1-dev.1
`

**Device:**
I am running the app in the Chrome (Web)

**Additional context**
Try to use color_picker v0.4.0 but `html_editor_enhanced: ^2.2.0+1-dev.1` depends on `color_picker v0.5.0`

Any suggestions?

I wish yo all the World all the best :)

**Comment by tneotia** [comment]
Please try the solutions listed here: https://github.com/tneotia/html-editor-enhanced/issues/68#issuecomment-863369808

Hope it helps!

**Comment by agorneo** [comment]
I am sure it will work
I did a fork in the html-editor-enhanced, in order fix the dependencies my self, but in the latest (master) source it is already fixed
`  html_editor_enhanced:
    path: ../../_forked/html-editor-enhanced/
`
Thank you for the quick response
