### ISSUE TITLE
[QUESTION] Link opening

### ISSUE THREAD

**Issue by JEuler** [tneotia/html-editor-enhanced#88]
Is there any possibility to manually specify how to open the links? It is an opening the link on the same page where the editor is opened for now.

**Comment by tneotia** [comment]
As of right now the library does not have this feature but it is not difficult to implement. I will try to add this today or tomorrow, and once it's done I will post an example for you :)

**Comment by JEuler** [comment]
Thank you very much! 🍻

**Comment by tneotia** [comment]
@JEuler added this to the library. You can use a git dependency on `2.2.0+1-dev.1` and implement like this:

```dart
callbacks: Callbacks(
   onNavigationRequestMobile: (String url) {
      print(url);
      return NavigationActionPolicy.ALLOW;
   },
```

`NavigationActionPolicy.CANCEL` if you want to stop the URL from loading in the webview. Hope it helps :)

**Comment by JEuler** [comment]
It is working, thank you very much! :)

**Comment by tneotia** [comment]
Thanks for the confirmation. If you have any other questions let me know!

**Comment by TrangLT-64** [comment]
I can't implement onNavigationRequestMobile.  I'm using dependency on 2.2.0+1-dev.1 but no callback function is onNavigationRequestMobile. @tneotia  Can you help me?

**Comment by JEuler** [comment]
@TrangLT-64 try to use the GIT reference
```
  html_editor_enhanced:
    git:
      url: https://github.com/tneotia/html-editor-enhanced.git
      ref: 2.2.0+1-dev.1
```

**Comment by SomaPrasanna4037** [comment]
if i enter any link and click spacebar or any normal text then the link is not show as link it display as a text
