### ISSUE TITLE
HTML element property changes are not retained

### ISSUE THREAD

**Issue by cushingbf** [tneotia/html-editor-enhanced#91]
When using version 2.2.0 of the the html-editor-enhanced package, I'm having trouble with HTML property changes not being saved. This particularly happens when I've inserted HTML input elements, make changes through the editor and then get the resulting markup text.

**To Reproduce**
1. Insert HtmlEditor on a page
2. Add custom toolbar buttons to insert HTML controls like this:
    `controller.insertHtml("<input type='text' value='test'/>");`
    `controller.insertHtml("<input type='radio' name='grp' checked='checked'>Yes<input type='radio' name='grp'>No");`
2. Make changes to HTML controls through editor window like clicking on No radio button or changing text input value from "test" to "foobar".
3. Retrieve the HTML markup from the controller like this:
    `String? txt = await controller.getText();`
4. See that HTML changes are not reflected in markup text.

**Expected behavior**
HTML property changes should be reflected in the back-end markup just as they are on the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/84947224/125828953-4a6483aa-6ffa-4518-9bb1-6be43b605577.png)
![image](https://user-images.githubusercontent.com/84947224/125829052-fbcce3d2-04c5-4185-98b4-42538d9be533.png)

**Device:**
This error was tested using the default Pixel_3a_API_30_x86 Android emulator that comes with Android Studio. Flutter code was compiled and run through VS Code. HTML markup was retrieved through another custom toolbar button in order to print it to the screen.

**Additional context**
N/A

**Comment by tneotia** [comment]
This seems like a limitation of the package I use for the editor. If you go on their site and input those HTML and make changes, they are not reflected. Unfortunately this isn't something that can be fixed at this time.
