### ISSUE TITLE
[QUESTION] How do I change background color of the toolbar without changing the the color of the editor area?

### ISSUE THREAD

**Issue by sigmapie8** [tneotia/html-editor-enhanced#94]
Type question here.

**Comment by tneotia** [comment]
You should be able to simply wrap the `HtmlEditor` in a `Container` and give that the `color:` argument. This won't affect the editor area because it uses a webview so the color is not dependent through Flutter.

**Comment by sigmapie8** [comment]
Thanks! That worked for me. Although I feel stupid after knowing the answer :sweat_smile:
