### ISSUE TITLE
A word counter or character counter function is needed [FEATURE]

### ISSUE THREAD

**Issue by taqi92** [tneotia/html-editor-enhanced#96]
**Is your feature request related to a problem? Please describe.**
I have a feature in app where i have to set a payment based on word count so i feel that it would be better to have a word counter

**Describe the solution you'd like**
In HTML editor function there can be a function called word counter which will keep track of typed characters

**Additional context**

**Comment by tneotia** [comment]
I can add that in. It may be a day or two before I get to it though :)

For my reference: https://github.com/summernote/summernote/issues/63#issuecomment-325061343

**Comment by tneotia** [comment]
I added a character counter in `master`, just do `controller.characterCount`!

**Comment by nguyenlamzx** [comment]
Hi @tneotia,

I'm having trouble with the value I get from the call to `controller.characterCount`, it seems to be one beat behind what changed in the editor (HtmlInputType.text, not html)

For example, if I type a character first, the value I get from characterCount is 0, instead of 1. Then, I delete the character I just entered and I get characterCount with a value of 1, instead of 0.

I can reproduce this issue right on the example from this package.

Could you help to check and provide us an update?

Many thanks,

**Comment by tneotia** [comment]
When are you calling `controller.characterCount` to test it?

**Comment by lam-nv** [comment]
> When are you calling controller.characterCount to test it?

Hi @tneotia, I was test it within these callbacks:
```
...

class _TextEditorPageState extends State<TextEditorPage> {
  final HtmlEditorController controller = HtmlEditorController();
...


              child: HtmlEditor(
                controller: controller,
                htmlToolbarOptions: HtmlToolbarOptions(
...
                callbacks: Callbacks(
                  onChangeContent: (String? changed) {
                    log('message ${controller.characterCount}');
                  },
                  onKeyUp:  (int? keyCode) {
                    //print('$keyCode key downed');
                    log('current character count: ${controller.characterCount}');
                  },
                ),
...
```
And get the same result:

> I'm having trouble with the value I get from the call to controller.characterCount, it seems to be one beat behind what changed in the editor (HtmlInputType.text, not html)

Hope your help.

**Comment by tneotia** [comment]
Out of curiosity if you add a slight delay `await Future.delayed(Duration(milliseconds: 500))` does it fix the issue?

**Comment by lam-nv** [comment]
> Out of curiosity if you add a slight delay `await Future.delayed(Duration(milliseconds: 500))` does it fix the issue?

In fact I tried with that and still had the same problem as mentioned above you can also reproduce this problem with for example this package.

Hope to receive your updates, @tneotia.
