### ISSUE TITLE
[BUG-Web] Showing dialog above html editor uses editors focus events

### ISSUE THREAD

**Issue by acheronian** [tneotia/html-editor-enhanced#98]
If a dialog is shown above an html editors edit space, you could not use the dialogs buttons or other pointer events.

1. Create view with html editor, expand it over the whole viewport
2. Open dialog with buttons
3. Try to click button

**Comment by tneotia** [comment]
Please see https://github.com/tneotia/html-editor-enhanced/issues/30 for the fix. This is an issue with Flutter :)

**Comment by acheronian** [comment]
Must have missed this entry, but thanks a lot, worked right away :)
